// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         eventId: "evt_01j2y8m6jcc9tt24af5pw9x1bc"
 *     }
 */
export interface GetEventsRequest {
  eventId: string;
  /** Defaults to the API key organization. A platform may select a practice or pharmacy only with an explicit webhook grant in this mode. This changes the webhook owner, not the caller or event subscriptions. */
  "X-Affinity-Organization-Id"?: string;
}
