// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         orderId: "ord_01j2y8m6jcc9tt24af5pw9x1bc",
 *         mode: "automatic",
 *         scenario: "successful"
 *     }
 */
export interface UpdateOrderTestSimulationRequest {
  orderId: string;
  "Idempotency-Key": string;
  mode: UpdateOrderTestSimulationRequest.Mode;
  scenario: UpdateOrderTestSimulationRequest.Scenario;
  action?: UpdateOrderTestSimulationRequest.Action | null;
}

export namespace UpdateOrderTestSimulationRequest {
  export const Mode = {
    Automatic: "automatic",
    Manual: "manual",
  } as const;
  export type Mode = (typeof Mode)[keyof typeof Mode];
  export const Scenario = {
    Successful: "successful",
    PharmacyRejection: "pharmacy_rejection",
    CancellationDeclined: "cancellation_declined",
  } as const;
  export type Scenario = (typeof Scenario)[keyof typeof Scenario];
  export const Action = {
    Accept: "accept",
    Process: "process",
    Ship: "ship",
    Deliver: "deliver",
    Reject: "reject",
    ConfirmCancellation: "confirm_cancellation",
    DeclineCancellation: "decline_cancellation",
  } as const;
  export type Action = (typeof Action)[keyof typeof Action];
}
