// This file was auto-generated by Fern from our API Definition.

import type * as AffinityApi from "../index.js";

export type ListCatalogItemsResponseDataItemCompositionIngredientsItemStrength =
  | AffinityApi.ListCatalogItemsResponseDataItemCompositionIngredientsItemStrength.Amount
  | AffinityApi.ListCatalogItemsResponseDataItemCompositionIngredientsItemStrength.Ratio
  | AffinityApi.ListCatalogItemsResponseDataItemCompositionIngredientsItemStrength.Unresolved;

export namespace ListCatalogItemsResponseDataItemCompositionIngredientsItemStrength {
  export interface Amount {
    kind: "amount";
    amount: ListCatalogItemsResponseDataItemCompositionIngredientsItemStrengthAmount.Amount;
  }

  export namespace ListCatalogItemsResponseDataItemCompositionIngredientsItemStrengthAmount {
    export interface Amount {
      value: string;
      unit: string;
    }
  }

  export interface Ratio {
    kind: "ratio";
    numerator: ListCatalogItemsResponseDataItemCompositionIngredientsItemStrengthRatio.Numerator;
    denominator: ListCatalogItemsResponseDataItemCompositionIngredientsItemStrengthRatio.Denominator;
  }

  export namespace ListCatalogItemsResponseDataItemCompositionIngredientsItemStrengthRatio {
    export interface Numerator {
      value: string;
      unit: string;
    }

    export interface Denominator {
      value: string;
      unit: string;
    }
  }

  export interface Unresolved {
    kind: "unresolved";
    reason: string;
  }
}
