// This file was auto-generated by Fern from our API Definition.

export interface ListShippingOptionsResponseItem {
  amountCents: number;
  carrier: string | null;
  currency: ListShippingOptionsResponseItem.Currency;
  estimatedDaysMax: number | null;
  estimatedDaysMin: number | null;
  id: string;
  label: string;
  serviceLevel: string;
  temperature: ListShippingOptionsResponseItem.Temperature;
}

export namespace ListShippingOptionsResponseItem {
  export const Currency = {
    Usd: "USD",
  } as const;
  export type Currency = (typeof Currency)[keyof typeof Currency];
  export const Temperature = {
    Ambient: "ambient",
    Refrigerated: "refrigerated",
  } as const;
  export type Temperature = (typeof Temperature)[keyof typeof Temperature];
}
