// This file was auto-generated by Fern from our API Definition.

import type * as AffinityApi from "../index.js";

export interface PlatformPublicApiSellingPricesUpdateSellingPriceResponse {
  amountCents: number | null;
  version: number;
  currency: PlatformPublicApiSellingPricesUpdateSellingPriceResponse.Currency;
  basis: AffinityApi.PlatformPublicApiSellingPricesUpdateSellingPriceResponseBasis;
  purchaseAmountCents: number;
  requiresReview: boolean;
}

export namespace PlatformPublicApiSellingPricesUpdateSellingPriceResponse {
  export const Currency = {
    Usd: "USD",
  } as const;
  export type Currency = (typeof Currency)[keyof typeof Currency];
}
