// This file was auto-generated by Fern from our API Definition.

export interface RegisterUserResponse {
  object: RegisterUserResponse.Object_;
  id: string;
  practiceId: string;
  memberId: string;
  prescriberId: string | null;
  externalId: string;
  livemode: boolean;
}

export namespace RegisterUserResponse {
  export const Object_ = {
    RegisteredUser: "registered_user",
  } as const;
  export type Object_ = (typeof Object_)[keyof typeof Object_];
}
