// This file was auto-generated by Fern from our API Definition.

export interface RotateWebhookEndpointSecretResponse {
  organizationId: string;
  practiceIds: string[];
  apiVersion: string;
  consecutiveFailures: number;
  createdAt: string;
  description: string;
  id: string;
  livemode: boolean;
  object: RotateWebhookEndpointSecretResponse.Object_;
  payloadStyle: RotateWebhookEndpointSecretResponse.PayloadStyle;
  status: RotateWebhookEndpointSecretResponse.Status;
  subscribedEvents: string[];
  updatedAt: string;
  url: string;
  signingSecret: string;
}

export namespace RotateWebhookEndpointSecretResponse {
  export const Object_ = {
    WebhookEndpoint: "webhook_endpoint",
  } as const;
  export type Object_ = (typeof Object_)[keyof typeof Object_];
  export const PayloadStyle = {
    Thin: "thin",
    Snapshot: "snapshot",
  } as const;
  export type PayloadStyle = (typeof PayloadStyle)[keyof typeof PayloadStyle];
  export const Status = {
    Active: "active",
    Suspended: "suspended",
    Disabled: "disabled",
  } as const;
  export type Status = (typeof Status)[keyof typeof Status];
}
