// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         platformId: "acct_01j2y8m6jcc9tt24af5pw9x1bc",
 *         scopes: ["webhooks:read"]
 *     }
 */
export interface SaveWebhookGrantRequest {
  platformId: string;
  "Idempotency-Key": string;
  scopes: SaveWebhookGrantRequest.Scopes.Item[];
}

export namespace SaveWebhookGrantRequest {
  export type Scopes = Scopes.Item[];

  export namespace Scopes {
    export const Item = {
      WebhooksRead: "webhooks:read",
      WebhooksWrite: "webhooks:write",
    } as const;
    export type Item = (typeof Item)[keyof typeof Item];
  }
}
