// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import {
  type NormalizedClientOptionsWithAuth,
  normalizeClientOptionsWithAuth,
} from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as AffinityApi from "../../../../../index.js";

export declare namespace EndpointsClient {
  export type Options = BaseClientOptions;

  export interface RequestOptions extends BaseRequestOptions {}
}

export class EndpointsClient {
  protected readonly _options: NormalizedClientOptionsWithAuth<EndpointsClient.Options>;

  constructor(options: EndpointsClient.Options) {
    this._options = normalizeClientOptionsWithAuth(options);
  }

  /**
   * Requires webhooks:read. Returns endpoints owned by the key organization, or the organization selected with X-Affinity-Organization-Id. Platform delegation requires a webhook grant in the key's mode.
   *
   * @param {AffinityApi.webhooks.ListEndpointsRequest} request
   * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AffinityApi.BadRequestError}
   * @throws {@link AffinityApi.UnauthorizedError}
   * @throws {@link AffinityApi.ForbiddenError}
   * @throws {@link AffinityApi.NotFoundError}
   * @throws {@link AffinityApi.ConflictError}
   * @throws {@link AffinityApi.UnprocessableEntityError}
   * @throws {@link AffinityApi.TooManyRequestsError}
   *
   * @example
   *     await client.webhooks.endpoints.list({
   *         endingBefore: "whe_01j2y8m6jcc9tt24af5pw9x1bc",
   *         startingAfter: "whe_01j2y8m6jcc9tt24af5pw9x1bc"
   *     })
   */
  public list(
    request: AffinityApi.webhooks.ListEndpointsRequest = {},
    requestOptions?: EndpointsClient.RequestOptions,
  ): core.HttpResponsePromise<AffinityApi.ListWebhookEndpointsResponse> {
    return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
  }

  private async __list(
    request: AffinityApi.webhooks.ListEndpointsRequest = {},
    requestOptions?: EndpointsClient.RequestOptions,
  ): Promise<core.WithRawResponse<AffinityApi.ListWebhookEndpointsResponse>> {
    const {
      endingBefore,
      limit,
      startingAfter,
      "X-Affinity-Organization-Id": affinityOrganizationId,
    } = request;
    const _queryParams: Record<string, unknown> = {
      endingBefore,
      limit,
      startingAfter,
    };
    const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      _authRequest.headers,
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        "X-Affinity-Organization-Id": affinityOrganizationId,
        "Affinity-Version": requestOptions?.affinityVersion ?? this._options?.affinityVersion,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.AffinityApiEnvironment.Production,
        "v1/webhook-endpoints",
      ),
      method: "GET",
      headers: _headers,
      queryString: core.url
        .queryBuilder()
        .addMany(_queryParams)
        .mergeAdditional(requestOptions?.queryParams)
        .build(),
      timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: _response.body as AffinityApi.ListWebhookEndpointsResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AffinityApi.BadRequestError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 401:
          throw new AffinityApi.UnauthorizedError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 403:
          throw new AffinityApi.ForbiddenError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 404:
          throw new AffinityApi.NotFoundError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 409:
          throw new AffinityApi.ConflictError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 422:
          throw new AffinityApi.UnprocessableEntityError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 429:
          throw new AffinityApi.TooManyRequestsError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        default:
          throw new errors.AffinityApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "GET",
      "/v1/webhook-endpoints",
    );
  }

  /**
   * Requires webhooks:write and Idempotency-Key. Defaults to the API key organization. A platform can select a practice or pharmacy owner with X-Affinity-Organization-Id and an explicit webhook grant. For platform-owned endpoints, practiceIds narrows delivery to selected connected practices. An empty filter receives all otherwise-authorized events.
   *
   * @param {AffinityApi.webhooks.CreateWebhookEndpointRequest} request
   * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AffinityApi.BadRequestError}
   * @throws {@link AffinityApi.UnauthorizedError}
   * @throws {@link AffinityApi.ForbiddenError}
   * @throws {@link AffinityApi.NotFoundError}
   * @throws {@link AffinityApi.ConflictError}
   * @throws {@link AffinityApi.UnprocessableEntityError}
   * @throws {@link AffinityApi.TooManyRequestsError}
   *
   * @example
   *     await client.webhooks.endpoints.create({
   *         "Idempotency-Key": "Idempotency-Key",
   *         url: "url"
   *     })
   */
  public create(
    request: AffinityApi.webhooks.CreateWebhookEndpointRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): core.HttpResponsePromise<AffinityApi.CreateWebhookEndpointResponse> {
    return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
  }

  private async __create(
    request: AffinityApi.webhooks.CreateWebhookEndpointRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): Promise<core.WithRawResponse<AffinityApi.CreateWebhookEndpointResponse>> {
    const {
      "X-Affinity-Organization-Id": affinityOrganizationId,
      "Idempotency-Key": idempotencyKey,
      ..._body
    } = request;
    const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      _authRequest.headers,
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        "X-Affinity-Organization-Id": affinityOrganizationId,
        "Idempotency-Key": idempotencyKey,
        "Affinity-Version": requestOptions?.affinityVersion ?? this._options?.affinityVersion,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.AffinityApiEnvironment.Production,
        "v1/webhook-endpoints",
      ),
      method: "POST",
      headers: _headers,
      contentType: "application/json",
      queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
      requestType: "json",
      body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
      timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: _response.body as AffinityApi.CreateWebhookEndpointResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AffinityApi.BadRequestError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 401:
          throw new AffinityApi.UnauthorizedError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 403:
          throw new AffinityApi.ForbiddenError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 404:
          throw new AffinityApi.NotFoundError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 409:
          throw new AffinityApi.ConflictError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 422:
          throw new AffinityApi.UnprocessableEntityError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 429:
          throw new AffinityApi.TooManyRequestsError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        default:
          throw new errors.AffinityApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "POST",
      "/v1/webhook-endpoints",
    );
  }

  /**
   * @param {AffinityApi.webhooks.DeleteEndpointsRequest} request
   * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AffinityApi.BadRequestError}
   * @throws {@link AffinityApi.UnauthorizedError}
   * @throws {@link AffinityApi.ForbiddenError}
   * @throws {@link AffinityApi.NotFoundError}
   * @throws {@link AffinityApi.ConflictError}
   * @throws {@link AffinityApi.UnprocessableEntityError}
   * @throws {@link AffinityApi.TooManyRequestsError}
   *
   * @example
   *     await client.webhooks.endpoints.delete({
   *         "Idempotency-Key": "Idempotency-Key",
   *         endpointId: "whe_01j2y8m6jcc9tt24af5pw9x1bc"
   *     })
   */
  public delete(
    request: AffinityApi.webhooks.DeleteEndpointsRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): core.HttpResponsePromise<AffinityApi.DeleteWebhookEndpointResponse> {
    return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
  }

  private async __delete(
    request: AffinityApi.webhooks.DeleteEndpointsRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): Promise<core.WithRawResponse<AffinityApi.DeleteWebhookEndpointResponse>> {
    const {
      endpointId,
      "X-Affinity-Organization-Id": affinityOrganizationId,
      "Idempotency-Key": idempotencyKey,
    } = request;
    const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      _authRequest.headers,
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        "X-Affinity-Organization-Id": affinityOrganizationId,
        "Idempotency-Key": idempotencyKey,
        "Affinity-Version": requestOptions?.affinityVersion ?? this._options?.affinityVersion,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.AffinityApiEnvironment.Production,
        `v1/webhook-endpoints/${core.url.encodePathParam(endpointId)}`,
      ),
      method: "DELETE",
      headers: _headers,
      queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
      timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: _response.body as AffinityApi.DeleteWebhookEndpointResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AffinityApi.BadRequestError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 401:
          throw new AffinityApi.UnauthorizedError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 403:
          throw new AffinityApi.ForbiddenError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 404:
          throw new AffinityApi.NotFoundError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 409:
          throw new AffinityApi.ConflictError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 422:
          throw new AffinityApi.UnprocessableEntityError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 429:
          throw new AffinityApi.TooManyRequestsError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        default:
          throw new errors.AffinityApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "DELETE",
      "/v1/webhook-endpoints/{endpointId}",
    );
  }

  /**
   * Requires webhooks:write and Idempotency-Key. Updates an endpoint in the selected organization and mode. Omitted practiceIds preserves the filter; an empty array removes the practice filter. Subscription changes apply to newly generated events.
   *
   * @param {AffinityApi.webhooks.UpdateWebhookEndpointRequest} request
   * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AffinityApi.BadRequestError}
   * @throws {@link AffinityApi.UnauthorizedError}
   * @throws {@link AffinityApi.ForbiddenError}
   * @throws {@link AffinityApi.NotFoundError}
   * @throws {@link AffinityApi.ConflictError}
   * @throws {@link AffinityApi.UnprocessableEntityError}
   * @throws {@link AffinityApi.TooManyRequestsError}
   *
   * @example
   *     await client.webhooks.endpoints.update({
   *         "Idempotency-Key": "Idempotency-Key",
   *         endpointId: "whe_01j2y8m6jcc9tt24af5pw9x1bc"
   *     })
   */
  public update(
    request: AffinityApi.webhooks.UpdateWebhookEndpointRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): core.HttpResponsePromise<AffinityApi.UpdateWebhookEndpointResponse> {
    return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
  }

  private async __update(
    request: AffinityApi.webhooks.UpdateWebhookEndpointRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): Promise<core.WithRawResponse<AffinityApi.UpdateWebhookEndpointResponse>> {
    const {
      endpointId,
      "X-Affinity-Organization-Id": affinityOrganizationId,
      "Idempotency-Key": idempotencyKey,
      ..._body
    } = request;
    const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      _authRequest.headers,
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        "X-Affinity-Organization-Id": affinityOrganizationId,
        "Idempotency-Key": idempotencyKey,
        "Affinity-Version": requestOptions?.affinityVersion ?? this._options?.affinityVersion,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.AffinityApiEnvironment.Production,
        `v1/webhook-endpoints/${core.url.encodePathParam(endpointId)}`,
      ),
      method: "PATCH",
      headers: _headers,
      contentType: "application/json",
      queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
      requestType: "json",
      body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
      timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: _response.body as AffinityApi.UpdateWebhookEndpointResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AffinityApi.BadRequestError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 401:
          throw new AffinityApi.UnauthorizedError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 403:
          throw new AffinityApi.ForbiddenError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 404:
          throw new AffinityApi.NotFoundError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 409:
          throw new AffinityApi.ConflictError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 422:
          throw new AffinityApi.UnprocessableEntityError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 429:
          throw new AffinityApi.TooManyRequestsError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        default:
          throw new errors.AffinityApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "PATCH",
      "/v1/webhook-endpoints/{endpointId}",
    );
  }

  /**
   * @param {AffinityApi.webhooks.RotateSecretEndpointsRequest} request
   * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AffinityApi.BadRequestError}
   * @throws {@link AffinityApi.UnauthorizedError}
   * @throws {@link AffinityApi.ForbiddenError}
   * @throws {@link AffinityApi.NotFoundError}
   * @throws {@link AffinityApi.ConflictError}
   * @throws {@link AffinityApi.UnprocessableEntityError}
   * @throws {@link AffinityApi.TooManyRequestsError}
   *
   * @example
   *     await client.webhooks.endpoints.rotateSecret({
   *         "Idempotency-Key": "Idempotency-Key",
   *         endpointId: "whe_01j2y8m6jcc9tt24af5pw9x1bc"
   *     })
   */
  public rotateSecret(
    request: AffinityApi.webhooks.RotateSecretEndpointsRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): core.HttpResponsePromise<AffinityApi.RotateWebhookEndpointSecretResponse> {
    return core.HttpResponsePromise.fromPromise(this.__rotateSecret(request, requestOptions));
  }

  private async __rotateSecret(
    request: AffinityApi.webhooks.RotateSecretEndpointsRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): Promise<core.WithRawResponse<AffinityApi.RotateWebhookEndpointSecretResponse>> {
    const {
      endpointId,
      "X-Affinity-Organization-Id": affinityOrganizationId,
      "Idempotency-Key": idempotencyKey,
    } = request;
    const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      _authRequest.headers,
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        "X-Affinity-Organization-Id": affinityOrganizationId,
        "Idempotency-Key": idempotencyKey,
        "Affinity-Version": requestOptions?.affinityVersion ?? this._options?.affinityVersion,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.AffinityApiEnvironment.Production,
        `v1/webhook-endpoints/${core.url.encodePathParam(endpointId)}/rotate-secret`,
      ),
      method: "POST",
      headers: _headers,
      queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
      timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: _response.body as AffinityApi.RotateWebhookEndpointSecretResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AffinityApi.BadRequestError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 401:
          throw new AffinityApi.UnauthorizedError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 403:
          throw new AffinityApi.ForbiddenError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 404:
          throw new AffinityApi.NotFoundError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 409:
          throw new AffinityApi.ConflictError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 422:
          throw new AffinityApi.UnprocessableEntityError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 429:
          throw new AffinityApi.TooManyRequestsError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        default:
          throw new errors.AffinityApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "POST",
      "/v1/webhook-endpoints/{endpointId}/rotate-secret",
    );
  }

  /**
   * @param {AffinityApi.webhooks.TestEndpointsRequest} request
   * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @throws {@link AffinityApi.BadRequestError}
   * @throws {@link AffinityApi.UnauthorizedError}
   * @throws {@link AffinityApi.ForbiddenError}
   * @throws {@link AffinityApi.NotFoundError}
   * @throws {@link AffinityApi.ConflictError}
   * @throws {@link AffinityApi.UnprocessableEntityError}
   * @throws {@link AffinityApi.TooManyRequestsError}
   *
   * @example
   *     await client.webhooks.endpoints.test({
   *         "Idempotency-Key": "Idempotency-Key",
   *         endpointId: "whe_01j2y8m6jcc9tt24af5pw9x1bc"
   *     })
   */
  public test(
    request: AffinityApi.webhooks.TestEndpointsRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): core.HttpResponsePromise<AffinityApi.TestWebhookEndpointResponse> {
    return core.HttpResponsePromise.fromPromise(this.__test(request, requestOptions));
  }

  private async __test(
    request: AffinityApi.webhooks.TestEndpointsRequest,
    requestOptions?: EndpointsClient.RequestOptions,
  ): Promise<core.WithRawResponse<AffinityApi.TestWebhookEndpointResponse>> {
    const {
      endpointId,
      "X-Affinity-Organization-Id": affinityOrganizationId,
      "Idempotency-Key": idempotencyKey,
    } = request;
    const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
    const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
      _authRequest.headers,
      this._options?.headers,
      mergeOnlyDefinedHeaders({
        "X-Affinity-Organization-Id": affinityOrganizationId,
        "Idempotency-Key": idempotencyKey,
        "Affinity-Version": requestOptions?.affinityVersion ?? this._options?.affinityVersion,
      }),
      requestOptions?.headers,
    );
    const _response = await core.fetcher({
      url: core.url.join(
        (await core.Supplier.get(this._options.baseUrl)) ??
          (await core.Supplier.get(this._options.environment)) ??
          environments.AffinityApiEnvironment.Production,
        `v1/webhook-endpoints/${core.url.encodePathParam(endpointId)}/test`,
      ),
      method: "POST",
      headers: _headers,
      queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
      timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
      maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
      abortSignal: requestOptions?.abortSignal,
      fetchFn: this._options?.fetch,
      logging: this._options.logging,
    });
    if (_response.ok) {
      return {
        data: _response.body as AffinityApi.TestWebhookEndpointResponse,
        rawResponse: _response.rawResponse,
      };
    }

    if (_response.error.reason === "status-code") {
      switch (_response.error.statusCode) {
        case 400:
          throw new AffinityApi.BadRequestError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 401:
          throw new AffinityApi.UnauthorizedError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 403:
          throw new AffinityApi.ForbiddenError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 404:
          throw new AffinityApi.NotFoundError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 409:
          throw new AffinityApi.ConflictError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 422:
          throw new AffinityApi.UnprocessableEntityError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        case 429:
          throw new AffinityApi.TooManyRequestsError(
            _response.error.body as AffinityApi.Problem,
            _response.rawResponse,
          );
        default:
          throw new errors.AffinityApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.body,
            rawResponse: _response.rawResponse,
          });
      }
    }

    return handleNonStatusCodeError(
      _response.error,
      _response.rawResponse,
      "POST",
      "/v1/webhook-endpoints/{endpointId}/test",
    );
  }
}
