// This file was auto-generated by Fern from our API Definition.

import type * as AffinityApi from "../../../../index.js";

/**
 * @example
 *     {
 *         practiceId: "prac_01j2y8m6jcc9tt24af5pw9x1bc",
 *         startingAfter: "mbr_01j2y8m6jcc9tt24af5pw9x1bc",
 *         endingBefore: "mbr_01j2y8m6jcc9tt24af5pw9x1bc"
 *     }
 */
export interface ListPracticeTeamMembersRequest {
  practiceId: string;
  limit?: number;
  startingAfter?: string | null;
  endingBefore?: string | null;
  search?: string | null;
  role?: AffinityApi.ListPracticeTeamMembersRequestRole | null;
  status?: AffinityApi.ListPracticeTeamMembersRequestStatus | null;
}
