/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type GetApiAccessResponse,
  GetApiAccessResponseFromJSON,
  GetApiAccessResponseToJSON,
} from "../models/GetApiAccessResponse";
import { type Problem, ProblemFromJSON, ProblemToJSON } from "../models/Problem";

export interface GetApiAccessRequest {
  affinityVersion?: string;
}

/**
 *
 */
export class APIKeysApi extends runtime.BaseAPI {
  /**
   * Creates request options for getApiAccess without sending the request
   */
  async getApiAccessRequestOpts(
    requestParameters: GetApiAccessRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/auth/access`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns the subject, mode, and scopes for the API key.
   * Read API key access
   */
  async getApiAccessRaw(
    requestParameters: GetApiAccessRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetApiAccessResponse>> {
    const requestOptions = await this.getApiAccessRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetApiAccessResponseFromJSON(jsonValue),
    );
  }

  /**
   * Returns the subject, mode, and scopes for the API key.
   * Read API key access
   */
  async getApiAccess(
    requestParameters: GetApiAccessRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetApiAccessResponse> {
    const response = await this.getApiAccessRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
