/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type ListCatalogItemsResponse,
  ListCatalogItemsResponseFromJSON,
  ListCatalogItemsResponseToJSON,
} from "../models/ListCatalogItemsResponse";
import {
  type ListShippingOptionsResponse,
  ListShippingOptionsResponseFromJSON,
  ListShippingOptionsResponseToJSON,
} from "../models/ListShippingOptionsResponse";
import { type Problem, ProblemFromJSON, ProblemToJSON } from "../models/Problem";

export interface ListCatalogItemsRequest {
  query?: string;
  limit?: number;
  startingAfter?: string;
  endingBefore?: string;
  route?: ListCatalogItemsRouteEnum;
  affinityVersion?: string;
}

export interface ListShippingOptionsRequest {
  catalogItemId: string;
  destinationState: string;
  destinationType?: ListShippingOptionsDestinationTypeEnum;
  affinityVersion?: string;
}

/**
 *
 */
export class CatalogApi extends runtime.BaseAPI {
  /**
   * Creates request options for listCatalogItems without sending the request
   */
  async listCatalogItemsRequestOpts(
    requestParameters: ListCatalogItemsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["query"] != null) {
      queryParameters["query"] = requestParameters["query"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["startingAfter"] != null) {
      queryParameters["startingAfter"] = requestParameters["startingAfter"];
    }

    if (requestParameters["endingBefore"] != null) {
      queryParameters["endingBefore"] = requestParameters["endingBefore"];
    }

    if (requestParameters["route"] != null) {
      queryParameters["route"] = requestParameters["route"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/catalog/items`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Lists the catalog items that are eligible for the authenticated account and mode.
   * List catalog items
   */
  async listCatalogItemsRaw(
    requestParameters: ListCatalogItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListCatalogItemsResponse>> {
    const requestOptions = await this.listCatalogItemsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListCatalogItemsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Lists the catalog items that are eligible for the authenticated account and mode.
   * List catalog items
   */
  async listCatalogItems(
    requestParameters: ListCatalogItemsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListCatalogItemsResponse> {
    const response = await this.listCatalogItemsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listShippingOptions without sending the request
   */
  async listShippingOptionsRequestOpts(
    requestParameters: ListShippingOptionsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["catalogItemId"] == null) {
      throw new runtime.RequiredError(
        "catalogItemId",
        'Required parameter "catalogItemId" was null or undefined when calling listShippingOptions().',
      );
    }

    if (requestParameters["destinationState"] == null) {
      throw new runtime.RequiredError(
        "destinationState",
        'Required parameter "destinationState" was null or undefined when calling listShippingOptions().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["destinationState"] != null) {
      queryParameters["destinationState"] = requestParameters["destinationState"];
    }

    if (requestParameters["destinationType"] != null) {
      queryParameters["destinationType"] = requestParameters["destinationType"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/catalog/items/{catalogItemId}/shipping-options`;
    urlPath = urlPath.replace(
      "{catalogItemId}",
      encodeURIComponent(String(requestParameters["catalogItemId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Lists reviewed shipping services eligible for a catalog item, destination, and API mode.
   * List shipping options
   */
  async listShippingOptionsRaw(
    requestParameters: ListShippingOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListShippingOptionsResponse>> {
    const requestOptions = await this.listShippingOptionsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListShippingOptionsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Lists reviewed shipping services eligible for a catalog item, destination, and API mode.
   * List shipping options
   */
  async listShippingOptions(
    requestParameters: ListShippingOptionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListShippingOptionsResponse> {
    const response = await this.listShippingOptionsRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const ListCatalogItemsRouteEnum = {
  All: "all",
  Injectable: "injectable",
  Nasal: "nasal",
  Oral: "oral",
  Sublingual: "sublingual",
  Topical: "topical",
  Unknown: "unknown",
} as const;
export type ListCatalogItemsRouteEnum =
  (typeof ListCatalogItemsRouteEnum)[keyof typeof ListCatalogItemsRouteEnum];
/**
 * @export
 */
export const ListShippingOptionsDestinationTypeEnum = {
  Patient: "patient",
  Practice: "practice",
} as const;
export type ListShippingOptionsDestinationTypeEnum =
  (typeof ListShippingOptionsDestinationTypeEnum)[keyof typeof ListShippingOptionsDestinationTypeEnum];
