/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type CancelOrderRequest,
  CancelOrderRequestFromJSON,
  CancelOrderRequestToJSON,
} from "../models/CancelOrderRequest";
import {
  type CreateOrder200Response,
  CreateOrder200ResponseFromJSON,
  CreateOrder200ResponseToJSON,
} from "../models/CreateOrder200Response";
import {
  type CreateOrderRequest,
  CreateOrderRequestFromJSON,
  CreateOrderRequestToJSON,
} from "../models/CreateOrderRequest";
import {
  type ListOrderEvents200Response,
  ListOrderEvents200ResponseFromJSON,
  ListOrderEvents200ResponseToJSON,
} from "../models/ListOrderEvents200Response";
import {
  type ListOrders200Response,
  ListOrders200ResponseFromJSON,
  ListOrders200ResponseToJSON,
} from "../models/ListOrders200Response";
import {
  type ListOrders400Response,
  ListOrders400ResponseFromJSON,
  ListOrders400ResponseToJSON,
} from "../models/ListOrders400Response";
import {
  type UpdateOrderRequest,
  UpdateOrderRequestFromJSON,
  UpdateOrderRequestToJSON,
} from "../models/UpdateOrderRequest";

export interface CancelOrderOperationRequest {
  orderId: string;
  idempotencyKey: string;
  cancelOrderRequest: CancelOrderRequest;
}

export interface CreateOrderOperationRequest {
  idempotencyKey: string;
  createOrderRequest: CreateOrderRequest;
}

export interface GetOrderRequest {
  orderId: string;
}

export interface ListOrderEventsRequest {
  orderId: string;
}

export interface ListOrdersRequest {
  externalOrderId?: string;
  patientExternalId?: string;
  limit?: number;
  status?: ListOrdersStatusEnum;
}

export interface SubmitOrderRequest {
  orderId: string;
  idempotencyKey: string;
}

export interface UpdateOrderOperationRequest {
  orderId: string;
  idempotencyKey: string;
  updateOrderRequest: UpdateOrderRequest;
}

/**
 *
 */
export class PlatformOrdersApi extends runtime.BaseAPI {
  /**
   * Creates request options for cancelOrder without sending the request
   */
  async cancelOrderRequestOpts(
    requestParameters: CancelOrderOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["orderId"] == null) {
      throw new runtime.RequiredError(
        "orderId",
        'Required parameter "orderId" was null or undefined when calling cancelOrder().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling cancelOrder().',
      );
    }

    if (requestParameters["cancelOrderRequest"] == null) {
      throw new runtime.RequiredError(
        "cancelOrderRequest",
        'Required parameter "cancelOrderRequest" was null or undefined when calling cancelOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders/{orderId}/cancel`;
    urlPath = urlPath.replace(
      "{orderId}",
      encodeURIComponent(String(requestParameters["orderId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CancelOrderRequestToJSON(requestParameters["cancelOrderRequest"]),
    };
  }

  /**
   * Cancels an order before shipment. Corrections use cancel-and-replace.
   * Cancel order
   */
  async cancelOrderRaw(
    requestParameters: CancelOrderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateOrder200Response>> {
    const requestOptions = await this.cancelOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateOrder200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Cancels an order before shipment. Corrections use cancel-and-replace.
   * Cancel order
   */
  async cancelOrder(
    requestParameters: CancelOrderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateOrder200Response> {
    const response = await this.cancelOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for createOrder without sending the request
   */
  async createOrderRequestOpts(
    requestParameters: CreateOrderOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling createOrder().',
      );
    }

    if (requestParameters["createOrderRequest"] == null) {
      throw new runtime.RequiredError(
        "createOrderRequest",
        'Required parameter "createOrderRequest" was null or undefined when calling createOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateOrderRequestToJSON(requestParameters["createOrderRequest"]),
    };
  }

  /**
   * Creates an editable synthetic draft in test mode or releases an existing signed immutable prescription version in live mode.
   * Create order
   */
  async createOrderRaw(
    requestParameters: CreateOrderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateOrder200Response>> {
    const requestOptions = await this.createOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateOrder200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Creates an editable synthetic draft in test mode or releases an existing signed immutable prescription version in live mode.
   * Create order
   */
  async createOrder(
    requestParameters: CreateOrderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateOrder200Response> {
    const response = await this.createOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getOrder without sending the request
   */
  async getOrderRequestOpts(requestParameters: GetOrderRequest): Promise<runtime.RequestOpts> {
    if (requestParameters["orderId"] == null) {
      throw new runtime.RequiredError(
        "orderId",
        'Required parameter "orderId" was null or undefined when calling getOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders/{orderId}`;
    urlPath = urlPath.replace(
      "{orderId}",
      encodeURIComponent(String(requestParameters["orderId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Read order
   */
  async getOrderRaw(
    requestParameters: GetOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateOrder200Response>> {
    const requestOptions = await this.getOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateOrder200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Read order
   */
  async getOrder(
    requestParameters: GetOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateOrder200Response> {
    const response = await this.getOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listOrderEvents without sending the request
   */
  async listOrderEventsRequestOpts(
    requestParameters: ListOrderEventsRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["orderId"] == null) {
      throw new runtime.RequiredError(
        "orderId",
        'Required parameter "orderId" was null or undefined when calling listOrderEvents().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders/{orderId}/events`;
    urlPath = urlPath.replace(
      "{orderId}",
      encodeURIComponent(String(requestParameters["orderId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * List order events
   */
  async listOrderEventsRaw(
    requestParameters: ListOrderEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListOrderEvents200Response>> {
    const requestOptions = await this.listOrderEventsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListOrderEvents200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List order events
   */
  async listOrderEvents(
    requestParameters: ListOrderEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListOrderEvents200Response> {
    const response = await this.listOrderEventsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listOrders without sending the request
   */
  async listOrdersRequestOpts(requestParameters: ListOrdersRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["externalOrderId"] != null) {
      queryParameters["externalOrderId"] = requestParameters["externalOrderId"];
    }

    if (requestParameters["patientExternalId"] != null) {
      queryParameters["patientExternalId"] = requestParameters["patientExternalId"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * List platform orders
   */
  async listOrdersRaw(
    requestParameters: ListOrdersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListOrders200Response>> {
    const requestOptions = await this.listOrdersRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListOrders200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * List platform orders
   */
  async listOrders(
    requestParameters: ListOrdersRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListOrders200Response> {
    const response = await this.listOrdersRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for submitOrder without sending the request
   */
  async submitOrderRequestOpts(
    requestParameters: SubmitOrderRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["orderId"] == null) {
      throw new runtime.RequiredError(
        "orderId",
        'Required parameter "orderId" was null or undefined when calling submitOrder().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling submitOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders/{orderId}/submit`;
    urlPath = urlPath.replace(
      "{orderId}",
      encodeURIComponent(String(requestParameters["orderId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Validates and submits an immutable order to the Affinity review queue.
   * Submit order
   */
  async submitOrderRaw(
    requestParameters: SubmitOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateOrder200Response>> {
    const requestOptions = await this.submitOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateOrder200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Validates and submits an immutable order to the Affinity review queue.
   * Submit order
   */
  async submitOrder(
    requestParameters: SubmitOrderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateOrder200Response> {
    const response = await this.submitOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateOrder without sending the request
   */
  async updateOrderRequestOpts(
    requestParameters: UpdateOrderOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["orderId"] == null) {
      throw new runtime.RequiredError(
        "orderId",
        'Required parameter "orderId" was null or undefined when calling updateOrder().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling updateOrder().',
      );
    }

    if (requestParameters["updateOrderRequest"] == null) {
      throw new runtime.RequiredError(
        "updateOrderRequest",
        'Required parameter "updateOrderRequest" was null or undefined when calling updateOrder().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/orders/{orderId}`;
    urlPath = urlPath.replace(
      "{orderId}",
      encodeURIComponent(String(requestParameters["orderId"])),
    );

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateOrderRequestToJSON(requestParameters["updateOrderRequest"]),
    };
  }

  /**
   * Updates an order while it remains a draft.
   * Update draft order
   */
  async updateOrderRaw(
    requestParameters: UpdateOrderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateOrder200Response>> {
    const requestOptions = await this.updateOrderRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateOrder200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Updates an order while it remains a draft.
   * Update draft order
   */
  async updateOrder(
    requestParameters: UpdateOrderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateOrder200Response> {
    const response = await this.updateOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const ListOrdersStatusEnum = {
  Blocked: "blocked",
  Cancelled: "cancelled",
  Delivered: "delivered",
  Draft: "draft",
  Processing: "processing",
  Shipped: "shipped",
  Submitted: "submitted",
} as const;
export type ListOrdersStatusEnum = (typeof ListOrdersStatusEnum)[keyof typeof ListOrdersStatusEnum];
