/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type GetPlatformOrganization200Response,
  GetPlatformOrganization200ResponseFromJSON,
  GetPlatformOrganization200ResponseToJSON,
} from "../models/GetPlatformOrganization200Response";
import {
  type ListOrders400Response,
  ListOrders400ResponseFromJSON,
  ListOrders400ResponseToJSON,
} from "../models/ListOrders400Response";

export interface GetPlatformOrganizationRequest {
  orgId?: string;
}

/**
 *
 */
export class PlatformsApi extends runtime.BaseAPI {
  /**
   * Creates request options for getPlatformOrganization without sending the request
   */
  async getPlatformOrganizationRequestOpts(
    requestParameters: GetPlatformOrganizationRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["orgId"] != null) {
      queryParameters["orgId"] = requestParameters["orgId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/platform/organization`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Reads the authenticated platform organization and current role.
   * Read platform organization
   */
  async getPlatformOrganizationRaw(
    requestParameters: GetPlatformOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetPlatformOrganization200Response>> {
    const requestOptions = await this.getPlatformOrganizationRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetPlatformOrganization200ResponseFromJSON(jsonValue),
    );
  }

  /**
   * Reads the authenticated platform organization and current role.
   * Read platform organization
   */
  async getPlatformOrganization(
    requestParameters: GetPlatformOrganizationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetPlatformOrganization200Response> {
    const response = await this.getPlatformOrganizationRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
