/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type CreateWebhookEndpointRequest,
  CreateWebhookEndpointRequestFromJSON,
  CreateWebhookEndpointRequestToJSON,
} from "../models/CreateWebhookEndpointRequest";
import {
  type CreateWebhookEndpointResponse,
  CreateWebhookEndpointResponseFromJSON,
  CreateWebhookEndpointResponseToJSON,
} from "../models/CreateWebhookEndpointResponse";
import {
  type DeleteWebhookEndpointResponse,
  DeleteWebhookEndpointResponseFromJSON,
  DeleteWebhookEndpointResponseToJSON,
} from "../models/DeleteWebhookEndpointResponse";
import {
  type GetWebhookEventResponse,
  GetWebhookEventResponseFromJSON,
  GetWebhookEventResponseToJSON,
} from "../models/GetWebhookEventResponse";
import {
  type ListWebhookEndpointsResponse,
  ListWebhookEndpointsResponseFromJSON,
  ListWebhookEndpointsResponseToJSON,
} from "../models/ListWebhookEndpointsResponse";
import {
  type ListWebhookEventsResponse,
  ListWebhookEventsResponseFromJSON,
  ListWebhookEventsResponseToJSON,
} from "../models/ListWebhookEventsResponse";
import {
  type ListWebhookGrantsResponse,
  ListWebhookGrantsResponseFromJSON,
  ListWebhookGrantsResponseToJSON,
} from "../models/ListWebhookGrantsResponse";
import { type Problem, ProblemFromJSON, ProblemToJSON } from "../models/Problem";
import {
  type ReplayWebhookEventResponse,
  ReplayWebhookEventResponseFromJSON,
  ReplayWebhookEventResponseToJSON,
} from "../models/ReplayWebhookEventResponse";
import {
  type RevokeWebhookGrantResponse,
  RevokeWebhookGrantResponseFromJSON,
  RevokeWebhookGrantResponseToJSON,
} from "../models/RevokeWebhookGrantResponse";
import {
  type RotateWebhookEndpointSecretResponse,
  RotateWebhookEndpointSecretResponseFromJSON,
  RotateWebhookEndpointSecretResponseToJSON,
} from "../models/RotateWebhookEndpointSecretResponse";
import {
  type SaveWebhookGrantRequest,
  SaveWebhookGrantRequestFromJSON,
  SaveWebhookGrantRequestToJSON,
} from "../models/SaveWebhookGrantRequest";
import {
  type SaveWebhookGrantResponse,
  SaveWebhookGrantResponseFromJSON,
  SaveWebhookGrantResponseToJSON,
} from "../models/SaveWebhookGrantResponse";
import {
  type TestWebhookEndpointResponse,
  TestWebhookEndpointResponseFromJSON,
  TestWebhookEndpointResponseToJSON,
} from "../models/TestWebhookEndpointResponse";
import {
  type UpdateWebhookEndpointRequest,
  UpdateWebhookEndpointRequestFromJSON,
  UpdateWebhookEndpointRequestToJSON,
} from "../models/UpdateWebhookEndpointRequest";
import {
  type UpdateWebhookEndpointResponse,
  UpdateWebhookEndpointResponseFromJSON,
  UpdateWebhookEndpointResponseToJSON,
} from "../models/UpdateWebhookEndpointResponse";

export interface CreateWebhookEndpointOperationRequest {
  idempotencyKey: string;
  createWebhookEndpointRequest: CreateWebhookEndpointRequest;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface DeleteWebhookEndpointRequest {
  endpointId: string;
  idempotencyKey: string;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface GetWebhookEventRequest {
  eventId: string;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface ListWebhookEndpointsRequest {
  endingBefore?: string | null;
  limit?: number;
  startingAfter?: string | null;
  affinityVersion?: string;
  xAffinityOrganizationId?: string | null;
}

export interface ListWebhookEventsRequest {
  endingBefore?: string | null;
  limit?: number;
  status?: ListWebhookEventsStatusEnum;
  startingAfter?: string | null;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface ListWebhookGrantsRequest {
  limit?: number;
  startingAfter?: string | null;
  endingBefore?: string | null;
  affinityVersion?: string;
}

export interface ReplayWebhookEventRequest {
  eventId: string;
  idempotencyKey: string;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface RevokeWebhookGrantRequest {
  platformId: string;
  idempotencyKey: string;
  affinityVersion?: string;
}

export interface RotateWebhookEndpointSecretRequest {
  endpointId: string;
  idempotencyKey: string;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface SaveWebhookGrantOperationRequest {
  platformId: string;
  idempotencyKey: string;
  saveWebhookGrantRequest: SaveWebhookGrantRequest;
  affinityVersion?: string;
}

export interface TestWebhookEndpointRequest {
  endpointId: string;
  idempotencyKey: string;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

export interface UpdateWebhookEndpointOperationRequest {
  endpointId: string;
  idempotencyKey: string;
  updateWebhookEndpointRequest: UpdateWebhookEndpointRequest;
  affinityVersion?: string;
  xAffinityOrganizationId?: string;
}

/**
 *
 */
export class WebhooksApi extends runtime.BaseAPI {
  /**
   * Creates request options for createWebhookEndpoint without sending the request
   */
  async createWebhookEndpointRequestOpts(
    requestParameters: CreateWebhookEndpointOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling createWebhookEndpoint().',
      );
    }

    if (requestParameters["createWebhookEndpointRequest"] == null) {
      throw new runtime.RequiredError(
        "createWebhookEndpointRequest",
        'Required parameter "createWebhookEndpointRequest" was null or undefined when calling createWebhookEndpoint().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-endpoints`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: CreateWebhookEndpointRequestToJSON(requestParameters["createWebhookEndpointRequest"]),
    };
  }

  /**
   * Requires webhooks:write and Idempotency-Key. Defaults to the API key organization. A platform can select a practice or pharmacy owner with X-Affinity-Organization-Id and an explicit webhook grant. For platform-owned endpoints, practiceIds narrows delivery to selected connected practices. An empty filter receives all otherwise-authorized events.
   * Create endpoint
   */
  async createWebhookEndpointRaw(
    requestParameters: CreateWebhookEndpointOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateWebhookEndpointResponse>> {
    const requestOptions = await this.createWebhookEndpointRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateWebhookEndpointResponseFromJSON(jsonValue),
    );
  }

  /**
   * Requires webhooks:write and Idempotency-Key. Defaults to the API key organization. A platform can select a practice or pharmacy owner with X-Affinity-Organization-Id and an explicit webhook grant. For platform-owned endpoints, practiceIds narrows delivery to selected connected practices. An empty filter receives all otherwise-authorized events.
   * Create endpoint
   */
  async createWebhookEndpoint(
    requestParameters: CreateWebhookEndpointOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateWebhookEndpointResponse> {
    const response = await this.createWebhookEndpointRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteWebhookEndpoint without sending the request
   */
  async deleteWebhookEndpointRequestOpts(
    requestParameters: DeleteWebhookEndpointRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["endpointId"] == null) {
      throw new runtime.RequiredError(
        "endpointId",
        'Required parameter "endpointId" was null or undefined when calling deleteWebhookEndpoint().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling deleteWebhookEndpoint().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-endpoints/{endpointId}`;
    urlPath = urlPath.replace(
      "{endpointId}",
      encodeURIComponent(String(requestParameters["endpointId"])),
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Disable endpoint
   */
  async deleteWebhookEndpointRaw(
    requestParameters: DeleteWebhookEndpointRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeleteWebhookEndpointResponse>> {
    const requestOptions = await this.deleteWebhookEndpointRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteWebhookEndpointResponseFromJSON(jsonValue),
    );
  }

  /**
   * Disable endpoint
   */
  async deleteWebhookEndpoint(
    requestParameters: DeleteWebhookEndpointRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeleteWebhookEndpointResponse> {
    const response = await this.deleteWebhookEndpointRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getWebhookEvent without sending the request
   */
  async getWebhookEventRequestOpts(
    requestParameters: GetWebhookEventRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["eventId"] == null) {
      throw new runtime.RequiredError(
        "eventId",
        'Required parameter "eventId" was null or undefined when calling getWebhookEvent().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-events/{eventId}`;
    urlPath = urlPath.replace(
      "{eventId}",
      encodeURIComponent(String(requestParameters["eventId"])),
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Read event attempts
   */
  async getWebhookEventRaw(
    requestParameters: GetWebhookEventRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetWebhookEventResponse>> {
    const requestOptions = await this.getWebhookEventRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetWebhookEventResponseFromJSON(jsonValue),
    );
  }

  /**
   * Read event attempts
   */
  async getWebhookEvent(
    requestParameters: GetWebhookEventRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetWebhookEventResponse> {
    const response = await this.getWebhookEventRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listWebhookEndpoints without sending the request
   */
  async listWebhookEndpointsRequestOpts(
    requestParameters: ListWebhookEndpointsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["endingBefore"] != null) {
      queryParameters["endingBefore"] = requestParameters["endingBefore"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["startingAfter"] != null) {
      queryParameters["startingAfter"] = requestParameters["startingAfter"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-endpoints`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Requires webhooks:read. Returns endpoints owned by the key organization, or the organization selected with X-Affinity-Organization-Id. Platform delegation requires a webhook grant in the key\'s mode.
   * List endpoints
   */
  async listWebhookEndpointsRaw(
    requestParameters: ListWebhookEndpointsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListWebhookEndpointsResponse>> {
    const requestOptions = await this.listWebhookEndpointsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListWebhookEndpointsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Requires webhooks:read. Returns endpoints owned by the key organization, or the organization selected with X-Affinity-Organization-Id. Platform delegation requires a webhook grant in the key\'s mode.
   * List endpoints
   */
  async listWebhookEndpoints(
    requestParameters: ListWebhookEndpointsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListWebhookEndpointsResponse> {
    const response = await this.listWebhookEndpointsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listWebhookEvents without sending the request
   */
  async listWebhookEventsRequestOpts(
    requestParameters: ListWebhookEventsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["endingBefore"] != null) {
      queryParameters["endingBefore"] = requestParameters["endingBefore"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    if (requestParameters["startingAfter"] != null) {
      queryParameters["startingAfter"] = requestParameters["startingAfter"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-events`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * List events
   */
  async listWebhookEventsRaw(
    requestParameters: ListWebhookEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListWebhookEventsResponse>> {
    const requestOptions = await this.listWebhookEventsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListWebhookEventsResponseFromJSON(jsonValue),
    );
  }

  /**
   * List events
   */
  async listWebhookEvents(
    requestParameters: ListWebhookEventsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListWebhookEventsResponse> {
    const response = await this.listWebhookEventsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listWebhookGrants without sending the request
   */
  async listWebhookGrantsRequestOpts(
    requestParameters: ListWebhookGrantsRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["startingAfter"] != null) {
      queryParameters["startingAfter"] = requestParameters["startingAfter"];
    }

    if (requestParameters["endingBefore"] != null) {
      queryParameters["endingBefore"] = requestParameters["endingBefore"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-grants`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Requires webhooks:read on the owning practice or pharmacy key. Lists platform webhook grants in the key\'s mode. Platforms cannot list or grant themselves delegated access.
   * List access grants
   */
  async listWebhookGrantsRaw(
    requestParameters: ListWebhookGrantsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ListWebhookGrantsResponse>> {
    const requestOptions = await this.listWebhookGrantsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListWebhookGrantsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Requires webhooks:read on the owning practice or pharmacy key. Lists platform webhook grants in the key\'s mode. Platforms cannot list or grant themselves delegated access.
   * List access grants
   */
  async listWebhookGrants(
    requestParameters: ListWebhookGrantsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ListWebhookGrantsResponse> {
    const response = await this.listWebhookGrantsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for replayWebhookEvent without sending the request
   */
  async replayWebhookEventRequestOpts(
    requestParameters: ReplayWebhookEventRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["eventId"] == null) {
      throw new runtime.RequiredError(
        "eventId",
        'Required parameter "eventId" was null or undefined when calling replayWebhookEvent().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling replayWebhookEvent().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-events/{eventId}/replay`;
    urlPath = urlPath.replace(
      "{eventId}",
      encodeURIComponent(String(requestParameters["eventId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Replay event
   */
  async replayWebhookEventRaw(
    requestParameters: ReplayWebhookEventRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReplayWebhookEventResponse>> {
    const requestOptions = await this.replayWebhookEventRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ReplayWebhookEventResponseFromJSON(jsonValue),
    );
  }

  /**
   * Replay event
   */
  async replayWebhookEvent(
    requestParameters: ReplayWebhookEventRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReplayWebhookEventResponse> {
    const response = await this.replayWebhookEventRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for revokeWebhookGrant without sending the request
   */
  async revokeWebhookGrantRequestOpts(
    requestParameters: RevokeWebhookGrantRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["platformId"] == null) {
      throw new runtime.RequiredError(
        "platformId",
        'Required parameter "platformId" was null or undefined when calling revokeWebhookGrant().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling revokeWebhookGrant().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-grants/{platformId}`;
    urlPath = urlPath.replace(
      "{platformId}",
      encodeURIComponent(String(requestParameters["platformId"])),
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Requires webhooks:write on the owning practice or pharmacy key and Idempotency-Key. Removes platform webhook access in this mode. Existing endpoints remain owned by the practice or pharmacy and continue operating.
   * Revoke webhook access
   */
  async revokeWebhookGrantRaw(
    requestParameters: RevokeWebhookGrantRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RevokeWebhookGrantResponse>> {
    const requestOptions = await this.revokeWebhookGrantRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RevokeWebhookGrantResponseFromJSON(jsonValue),
    );
  }

  /**
   * Requires webhooks:write on the owning practice or pharmacy key and Idempotency-Key. Removes platform webhook access in this mode. Existing endpoints remain owned by the practice or pharmacy and continue operating.
   * Revoke webhook access
   */
  async revokeWebhookGrant(
    requestParameters: RevokeWebhookGrantRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RevokeWebhookGrantResponse> {
    const response = await this.revokeWebhookGrantRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for rotateWebhookEndpointSecret without sending the request
   */
  async rotateWebhookEndpointSecretRequestOpts(
    requestParameters: RotateWebhookEndpointSecretRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["endpointId"] == null) {
      throw new runtime.RequiredError(
        "endpointId",
        'Required parameter "endpointId" was null or undefined when calling rotateWebhookEndpointSecret().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling rotateWebhookEndpointSecret().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-endpoints/{endpointId}/rotate-secret`;
    urlPath = urlPath.replace(
      "{endpointId}",
      encodeURIComponent(String(requestParameters["endpointId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Rotate signing secret
   */
  async rotateWebhookEndpointSecretRaw(
    requestParameters: RotateWebhookEndpointSecretRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RotateWebhookEndpointSecretResponse>> {
    const requestOptions = await this.rotateWebhookEndpointSecretRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RotateWebhookEndpointSecretResponseFromJSON(jsonValue),
    );
  }

  /**
   * Rotate signing secret
   */
  async rotateWebhookEndpointSecret(
    requestParameters: RotateWebhookEndpointSecretRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RotateWebhookEndpointSecretResponse> {
    const response = await this.rotateWebhookEndpointSecretRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for saveWebhookGrant without sending the request
   */
  async saveWebhookGrantRequestOpts(
    requestParameters: SaveWebhookGrantOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["platformId"] == null) {
      throw new runtime.RequiredError(
        "platformId",
        'Required parameter "platformId" was null or undefined when calling saveWebhookGrant().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling saveWebhookGrant().',
      );
    }

    if (requestParameters["saveWebhookGrantRequest"] == null) {
      throw new runtime.RequiredError(
        "saveWebhookGrantRequest",
        'Required parameter "saveWebhookGrantRequest" was null or undefined when calling saveWebhookGrant().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-grants/{platformId}`;
    urlPath = urlPath.replace(
      "{platformId}",
      encodeURIComponent(String(requestParameters["platformId"])),
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: SaveWebhookGrantRequestToJSON(requestParameters["saveWebhookGrantRequest"]),
    };
  }

  /**
   * Requires webhooks:write on the owning practice or pharmacy key and Idempotency-Key. Grants or replaces a platform\'s webhook permissions in this mode. A practice must already be connected to that platform. The grant does not give the platform access to other API resources.
   * Grant webhook access
   */
  async saveWebhookGrantRaw(
    requestParameters: SaveWebhookGrantOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SaveWebhookGrantResponse>> {
    const requestOptions = await this.saveWebhookGrantRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SaveWebhookGrantResponseFromJSON(jsonValue),
    );
  }

  /**
   * Requires webhooks:write on the owning practice or pharmacy key and Idempotency-Key. Grants or replaces a platform\'s webhook permissions in this mode. A practice must already be connected to that platform. The grant does not give the platform access to other API resources.
   * Grant webhook access
   */
  async saveWebhookGrant(
    requestParameters: SaveWebhookGrantOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SaveWebhookGrantResponse> {
    const response = await this.saveWebhookGrantRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for testWebhookEndpoint without sending the request
   */
  async testWebhookEndpointRequestOpts(
    requestParameters: TestWebhookEndpointRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["endpointId"] == null) {
      throw new runtime.RequiredError(
        "endpointId",
        'Required parameter "endpointId" was null or undefined when calling testWebhookEndpoint().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling testWebhookEndpoint().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-endpoints/{endpointId}/test`;
    urlPath = urlPath.replace(
      "{endpointId}",
      encodeURIComponent(String(requestParameters["endpointId"])),
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Send test event
   */
  async testWebhookEndpointRaw(
    requestParameters: TestWebhookEndpointRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TestWebhookEndpointResponse>> {
    const requestOptions = await this.testWebhookEndpointRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TestWebhookEndpointResponseFromJSON(jsonValue),
    );
  }

  /**
   * Send test event
   */
  async testWebhookEndpoint(
    requestParameters: TestWebhookEndpointRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TestWebhookEndpointResponse> {
    const response = await this.testWebhookEndpointRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateWebhookEndpoint without sending the request
   */
  async updateWebhookEndpointRequestOpts(
    requestParameters: UpdateWebhookEndpointOperationRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["endpointId"] == null) {
      throw new runtime.RequiredError(
        "endpointId",
        'Required parameter "endpointId" was null or undefined when calling updateWebhookEndpoint().',
      );
    }

    if (requestParameters["idempotencyKey"] == null) {
      throw new runtime.RequiredError(
        "idempotencyKey",
        'Required parameter "idempotencyKey" was null or undefined when calling updateWebhookEndpoint().',
      );
    }

    if (requestParameters["updateWebhookEndpointRequest"] == null) {
      throw new runtime.RequiredError(
        "updateWebhookEndpointRequest",
        'Required parameter "updateWebhookEndpointRequest" was null or undefined when calling updateWebhookEndpoint().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["affinityVersion"] != null) {
      headerParameters["Affinity-Version"] = String(requestParameters["affinityVersion"]);
    }

    if (requestParameters["xAffinityOrganizationId"] != null) {
      headerParameters["X-Affinity-Organization-Id"] = String(
        requestParameters["xAffinityOrganizationId"],
      );
    }

    if (requestParameters["idempotencyKey"] != null) {
      headerParameters["Idempotency-Key"] = String(requestParameters["idempotencyKey"]);
    }

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["x-affinity-api-key"] =
        await this.configuration.apiKey("x-affinity-api-key"); // affinityApiKey authentication
    }

    let urlPath = `/v1/webhook-endpoints/{endpointId}`;
    urlPath = urlPath.replace(
      "{endpointId}",
      encodeURIComponent(String(requestParameters["endpointId"])),
    );

    return {
      path: urlPath,
      method: "PATCH",
      headers: headerParameters,
      query: queryParameters,
      body: UpdateWebhookEndpointRequestToJSON(requestParameters["updateWebhookEndpointRequest"]),
    };
  }

  /**
   * Requires webhooks:write and Idempotency-Key. Updates an endpoint in the selected organization and mode. Omitted practiceIds preserves the filter; an empty array removes the practice filter. Subscription changes apply to newly generated events.
   * Update endpoint
   */
  async updateWebhookEndpointRaw(
    requestParameters: UpdateWebhookEndpointOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateWebhookEndpointResponse>> {
    const requestOptions = await this.updateWebhookEndpointRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateWebhookEndpointResponseFromJSON(jsonValue),
    );
  }

  /**
   * Requires webhooks:write and Idempotency-Key. Updates an endpoint in the selected organization and mode. Omitted practiceIds preserves the filter; an empty array removes the practice filter. Subscription changes apply to newly generated events.
   * Update endpoint
   */
  async updateWebhookEndpoint(
    requestParameters: UpdateWebhookEndpointOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateWebhookEndpointResponse> {
    const response = await this.updateWebhookEndpointRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const ListWebhookEventsStatusEnum = {
  All: "all",
  Delivered: "delivered",
  Failed: "failed",
  Pending: "pending",
} as const;
export type ListWebhookEventsStatusEnum =
  (typeof ListWebhookEventsStatusEnum)[keyof typeof ListWebhookEventsStatusEnum];
