// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endingBefore: "pharm_01j2y8m6jcc9tt24af5pw9x1bc",
 *         orgId: "acct_01j2y8m6jcc9tt24af5pw9x1bc",
 *         pharmacyId: "pharm_01j2y8m6jcc9tt24af5pw9x1bc",
 *         startingAfter: "pharm_01j2y8m6jcc9tt24af5pw9x1bc"
 *     }
 */
export interface ListPharmaciesRequest {
  endingBefore?: string | null;
  limit?: number;
  orgId?: string | null;
  pharmacyId?: string | null;
  query?: string | null;
  shipsToState?: string | null;
  startingAfter?: string | null;
}
