/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AffinityWebhookPayloadAnyOfData } from "./AffinityWebhookPayloadAnyOfData";
import {
  AffinityWebhookPayloadAnyOfDataFromJSON,
  AffinityWebhookPayloadAnyOfDataFromJSONTyped,
  AffinityWebhookPayloadAnyOfDataToJSON,
  AffinityWebhookPayloadAnyOfDataToJSONTyped,
} from "./AffinityWebhookPayloadAnyOfData";
import type { AffinityWebhookPayloadAnyOfOrganizationId } from "./AffinityWebhookPayloadAnyOfOrganizationId";
import {
  AffinityWebhookPayloadAnyOfOrganizationIdFromJSON,
  AffinityWebhookPayloadAnyOfOrganizationIdFromJSONTyped,
  AffinityWebhookPayloadAnyOfOrganizationIdToJSON,
  AffinityWebhookPayloadAnyOfOrganizationIdToJSONTyped,
} from "./AffinityWebhookPayloadAnyOfOrganizationId";

/**
 *
 * @export
 * @interface AffinityWebhookPayloadAnyOf
 */
export interface AffinityWebhookPayloadAnyOf {
  /**
   *
   * @type {AffinityWebhookPayloadAnyOfApiVersionEnum}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  apiVersion: AffinityWebhookPayloadAnyOfApiVersionEnum;
  /**
   *
   * @type {number}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  created: number;
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  livemode: boolean;
  /**
   *
   * @type {AffinityWebhookPayloadAnyOfObjectEnum}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  object: AffinityWebhookPayloadAnyOfObjectEnum;
  /**
   *
   * @type {AffinityWebhookPayloadAnyOfOrganizationId}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  organizationId: AffinityWebhookPayloadAnyOfOrganizationId;
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  requestId: string | null;
  /**
   *
   * @type {AffinityWebhookPayloadAnyOfData}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  data: AffinityWebhookPayloadAnyOfData;
  /**
   *
   * @type {AffinityWebhookPayloadAnyOfTypeEnum}
   * @memberof AffinityWebhookPayloadAnyOf
   */
  type: AffinityWebhookPayloadAnyOfTypeEnum;
}

/**
 * @export
 */
export const AffinityWebhookPayloadAnyOfApiVersionEnum = {
  _20260729: "2026-07-29",
} as const;
export type AffinityWebhookPayloadAnyOfApiVersionEnum =
  (typeof AffinityWebhookPayloadAnyOfApiVersionEnum)[keyof typeof AffinityWebhookPayloadAnyOfApiVersionEnum];

/**
 * @export
 */
export const AffinityWebhookPayloadAnyOfObjectEnum = {
  Event: "event",
} as const;
export type AffinityWebhookPayloadAnyOfObjectEnum =
  (typeof AffinityWebhookPayloadAnyOfObjectEnum)[keyof typeof AffinityWebhookPayloadAnyOfObjectEnum];

/**
 * @export
 */
export const AffinityWebhookPayloadAnyOfTypeEnum = {
  WebhookEndpointTest: "webhook_endpoint.test",
} as const;
export type AffinityWebhookPayloadAnyOfTypeEnum =
  (typeof AffinityWebhookPayloadAnyOfTypeEnum)[keyof typeof AffinityWebhookPayloadAnyOfTypeEnum];

/**
 * Check if a given object implements the AffinityWebhookPayloadAnyOf interface.
 */
export function instanceOfAffinityWebhookPayloadAnyOf(
  value: object,
): value is AffinityWebhookPayloadAnyOf {
  if (!("apiVersion" in value) || value["apiVersion"] === undefined) return false;
  if (!("created" in value) || value["created"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("livemode" in value) || value["livemode"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined) return false;
  if (!("requestId" in value) || value["requestId"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function AffinityWebhookPayloadAnyOfFromJSON(json: any): AffinityWebhookPayloadAnyOf {
  return AffinityWebhookPayloadAnyOfFromJSONTyped(json, false);
}

export function AffinityWebhookPayloadAnyOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AffinityWebhookPayloadAnyOf {
  if (json == null) {
    return json;
  }
  return {
    apiVersion: json["api_version"],
    created: json["created"],
    id: json["id"],
    livemode: json["livemode"],
    object: json["object"],
    organizationId: AffinityWebhookPayloadAnyOfOrganizationIdFromJSON(json["organization_id"]),
    requestId: json["request_id"],
    data: AffinityWebhookPayloadAnyOfDataFromJSON(json["data"]),
    type: json["type"],
  };
}

export function AffinityWebhookPayloadAnyOfToJSON(json: any): AffinityWebhookPayloadAnyOf {
  return AffinityWebhookPayloadAnyOfToJSONTyped(json, false);
}

export function AffinityWebhookPayloadAnyOfToJSONTyped(
  value?: AffinityWebhookPayloadAnyOf | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    api_version: value["apiVersion"],
    created: value["created"],
    id: value["id"],
    livemode: value["livemode"],
    object: value["object"],
    organization_id: AffinityWebhookPayloadAnyOfOrganizationIdToJSON(value["organizationId"]),
    request_id: value["requestId"],
    data: AffinityWebhookPayloadAnyOfDataToJSON(value["data"]),
    type: value["type"],
  };
}
