/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AffinityWebhookPayloadAnyOf1DataObject
 */
export interface AffinityWebhookPayloadAnyOf1DataObject {
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  carrier?: string | null;
  /**
   *
   * @type {Date}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  deliveredAt?: Date | null;
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  externalOrderId?: string | null;
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  id: string;
  /**
   *
   * @type {AffinityWebhookPayloadAnyOf1DataObjectObjectEnum}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  object: AffinityWebhookPayloadAnyOf1DataObjectObjectEnum;
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  practiceId?: string | null;
  /**
   *
   * @type {Date}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  shippedAt?: Date | null;
  /**
   *
   * @type {AffinityWebhookPayloadAnyOf1DataObjectStatusEnum}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  status?: AffinityWebhookPayloadAnyOf1DataObjectStatusEnum;
  /**
   *
   * @type {string}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  trackingNumber?: string | null;
  /**
   *
   * @type {Date}
   * @memberof AffinityWebhookPayloadAnyOf1DataObject
   */
  updatedAt?: Date;
}

/**
 * @export
 */
export const AffinityWebhookPayloadAnyOf1DataObjectObjectEnum = {
  Order: "order",
} as const;
export type AffinityWebhookPayloadAnyOf1DataObjectObjectEnum =
  (typeof AffinityWebhookPayloadAnyOf1DataObjectObjectEnum)[keyof typeof AffinityWebhookPayloadAnyOf1DataObjectObjectEnum];

/**
 * @export
 */
export const AffinityWebhookPayloadAnyOf1DataObjectStatusEnum = {
  Accepted: "accepted",
  Blocked: "blocked",
  Cancelled: "cancelled",
  Delivered: "delivered",
  Draft: "draft",
  Processing: "processing",
  Shipped: "shipped",
  Submitted: "submitted",
} as const;
export type AffinityWebhookPayloadAnyOf1DataObjectStatusEnum =
  (typeof AffinityWebhookPayloadAnyOf1DataObjectStatusEnum)[keyof typeof AffinityWebhookPayloadAnyOf1DataObjectStatusEnum];

/**
 * Check if a given object implements the AffinityWebhookPayloadAnyOf1DataObject interface.
 */
export function instanceOfAffinityWebhookPayloadAnyOf1DataObject(
  value: object,
): value is AffinityWebhookPayloadAnyOf1DataObject {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  return true;
}

export function AffinityWebhookPayloadAnyOf1DataObjectFromJSON(
  json: any,
): AffinityWebhookPayloadAnyOf1DataObject {
  return AffinityWebhookPayloadAnyOf1DataObjectFromJSONTyped(json, false);
}

export function AffinityWebhookPayloadAnyOf1DataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AffinityWebhookPayloadAnyOf1DataObject {
  if (json == null) {
    return json;
  }
  return {
    carrier: json["carrier"] == null ? undefined : json["carrier"],
    deliveredAt: json["delivered_at"] == null ? undefined : new Date(json["delivered_at"]),
    externalOrderId: json["external_order_id"] == null ? undefined : json["external_order_id"],
    id: json["id"],
    object: json["object"],
    practiceId: json["practice_id"] == null ? undefined : json["practice_id"],
    shippedAt: json["shipped_at"] == null ? undefined : new Date(json["shipped_at"]),
    status: json["status"] == null ? undefined : json["status"],
    trackingNumber: json["tracking_number"] == null ? undefined : json["tracking_number"],
    updatedAt: json["updated_at"] == null ? undefined : new Date(json["updated_at"]),
  };
}

export function AffinityWebhookPayloadAnyOf1DataObjectToJSON(
  json: any,
): AffinityWebhookPayloadAnyOf1DataObject {
  return AffinityWebhookPayloadAnyOf1DataObjectToJSONTyped(json, false);
}

export function AffinityWebhookPayloadAnyOf1DataObjectToJSONTyped(
  value?: AffinityWebhookPayloadAnyOf1DataObject | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    carrier: value["carrier"],
    delivered_at:
      value["deliveredAt"] == null ? value["deliveredAt"] : value["deliveredAt"].toISOString(),
    external_order_id: value["externalOrderId"],
    id: value["id"],
    object: value["object"],
    practice_id: value["practiceId"],
    shipped_at: value["shippedAt"] == null ? value["shippedAt"] : value["shippedAt"].toISOString(),
    status: value["status"],
    tracking_number: value["trackingNumber"],
    updated_at: value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
  };
}
