/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CancelOrderResponseCancellationOutcomesInner
 */
export interface CancelOrderResponseCancellationOutcomesInner {
  /**
   *
   * @type {string}
   * @memberof CancelOrderResponseCancellationOutcomesInner
   */
  cancellationId: string;
  /**
   *
   * @type {string}
   * @memberof CancelOrderResponseCancellationOutcomesInner
   */
  fulfillmentId: string;
  /**
   *
   * @type {CancelOrderResponseCancellationOutcomesInnerStatusEnum}
   * @memberof CancelOrderResponseCancellationOutcomesInner
   */
  status: CancelOrderResponseCancellationOutcomesInnerStatusEnum;
}

/**
 * @export
 */
export const CancelOrderResponseCancellationOutcomesInnerStatusEnum = {
  Confirmed: "confirmed",
  Failed: "failed",
  Rejected: "rejected",
  Requested: "requested",
  Sent: "sent",
  TooLate: "too_late",
} as const;
export type CancelOrderResponseCancellationOutcomesInnerStatusEnum =
  (typeof CancelOrderResponseCancellationOutcomesInnerStatusEnum)[keyof typeof CancelOrderResponseCancellationOutcomesInnerStatusEnum];

/**
 * Check if a given object implements the CancelOrderResponseCancellationOutcomesInner interface.
 */
export function instanceOfCancelOrderResponseCancellationOutcomesInner(
  value: object,
): value is CancelOrderResponseCancellationOutcomesInner {
  if (!("cancellationId" in value) || value["cancellationId"] === undefined) return false;
  if (!("fulfillmentId" in value) || value["fulfillmentId"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function CancelOrderResponseCancellationOutcomesInnerFromJSON(
  json: any,
): CancelOrderResponseCancellationOutcomesInner {
  return CancelOrderResponseCancellationOutcomesInnerFromJSONTyped(json, false);
}

export function CancelOrderResponseCancellationOutcomesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancelOrderResponseCancellationOutcomesInner {
  if (json == null) {
    return json;
  }
  return {
    cancellationId: json["cancellationId"],
    fulfillmentId: json["fulfillmentId"],
    status: json["status"],
  };
}

export function CancelOrderResponseCancellationOutcomesInnerToJSON(
  json: any,
): CancelOrderResponseCancellationOutcomesInner {
  return CancelOrderResponseCancellationOutcomesInnerToJSONTyped(json, false);
}

export function CancelOrderResponseCancellationOutcomesInnerToJSONTyped(
  value?: CancelOrderResponseCancellationOutcomesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    cancellationId: value["cancellationId"],
    fulfillmentId: value["fulfillmentId"],
    status: value["status"],
  };
}
