/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason
 */
export interface CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason {
  /**
   *
   * @type {string}
   * @memberof CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason
   */
  category?: string | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason
   */
  context: string | null;
}

/**
 * Check if a given object implements the CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason interface.
 */
export function instanceOfCancelOrderResponsePrescriptionsInnerClinicalCompoundingReason(
  value: object,
): value is CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason {
  if (!("context" in value) || value["context"] === undefined) return false;
  return true;
}

export function CancelOrderResponsePrescriptionsInnerClinicalCompoundingReasonFromJSON(
  json: any,
): CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason {
  return CancelOrderResponsePrescriptionsInnerClinicalCompoundingReasonFromJSONTyped(json, false);
}

export function CancelOrderResponsePrescriptionsInnerClinicalCompoundingReasonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason {
  if (json == null) {
    return json;
  }
  return {
    category: json["category"] == null ? undefined : json["category"],
    context: json["context"],
  };
}

export function CancelOrderResponsePrescriptionsInnerClinicalCompoundingReasonToJSON(
  json: any,
): CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason {
  return CancelOrderResponsePrescriptionsInnerClinicalCompoundingReasonToJSONTyped(json, false);
}

export function CancelOrderResponsePrescriptionsInnerClinicalCompoundingReasonToJSONTyped(
  value?: CancelOrderResponsePrescriptionsInnerClinicalCompoundingReason | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category: value["category"],
    context: value["context"],
  };
}
