/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CancelOrderResponseCancellationOutcomesInner } from "./CancelOrderResponseCancellationOutcomesInner";
import {
  CancelOrderResponseCancellationOutcomesInnerFromJSON,
  CancelOrderResponseCancellationOutcomesInnerFromJSONTyped,
  CancelOrderResponseCancellationOutcomesInnerToJSON,
  CancelOrderResponseCancellationOutcomesInnerToJSONTyped,
} from "./CancelOrderResponseCancellationOutcomesInner";

/**
 *
 * @export
 * @interface CancelOrderResponseCancellation
 */
export interface CancelOrderResponseCancellation {
  /**
   *
   * @type {CancelOrderResponseCancellationStatusEnum}
   * @memberof CancelOrderResponseCancellation
   */
  status: CancelOrderResponseCancellationStatusEnum;
  /**
   *
   * @type {Array<CancelOrderResponseCancellationOutcomesInner>}
   * @memberof CancelOrderResponseCancellation
   */
  outcomes: Array<CancelOrderResponseCancellationOutcomesInner>;
}

/**
 * @export
 */
export const CancelOrderResponseCancellationStatusEnum = {
  Confirmed: "confirmed",
  Pending: "pending",
  Partial: "partial",
  Failed: "failed",
} as const;
export type CancelOrderResponseCancellationStatusEnum =
  (typeof CancelOrderResponseCancellationStatusEnum)[keyof typeof CancelOrderResponseCancellationStatusEnum];

/**
 * Check if a given object implements the CancelOrderResponseCancellation interface.
 */
export function instanceOfCancelOrderResponseCancellation(
  value: object,
): value is CancelOrderResponseCancellation {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("outcomes" in value) || value["outcomes"] === undefined) return false;
  return true;
}

export function CancelOrderResponseCancellationFromJSON(
  json: any,
): CancelOrderResponseCancellation {
  return CancelOrderResponseCancellationFromJSONTyped(json, false);
}

export function CancelOrderResponseCancellationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancelOrderResponseCancellation {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    outcomes: (json["outcomes"] as Array<any>).map(
      CancelOrderResponseCancellationOutcomesInnerFromJSON,
    ),
  };
}

export function CancelOrderResponseCancellationToJSON(json: any): CancelOrderResponseCancellation {
  return CancelOrderResponseCancellationToJSONTyped(json, false);
}

export function CancelOrderResponseCancellationToJSONTyped(
  value?: CancelOrderResponseCancellation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    outcomes: (value["outcomes"] as Array<any>).map(
      CancelOrderResponseCancellationOutcomesInnerToJSON,
    ),
  };
}
