/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompletePracticePaymentSetupResponsePaymentMethodsInner
 */
export interface CompletePracticePaymentSetupResponsePaymentMethodsInner {
  /**
   *
   * @type {string}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  brand: string;
  /**
   *
   * @type {number}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  expMonth: number;
  /**
   *
   * @type {number}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  expYear: number;
  /**
   *
   * @type {string}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  isPrimary: boolean;
  /**
   *
   * @type {string}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  last4: string;
  /**
   *
   * @type {CompletePracticePaymentSetupResponsePaymentMethodsInnerTypeEnum}
   * @memberof CompletePracticePaymentSetupResponsePaymentMethodsInner
   */
  type: CompletePracticePaymentSetupResponsePaymentMethodsInnerTypeEnum;
}

/**
 * @export
 */
export const CompletePracticePaymentSetupResponsePaymentMethodsInnerTypeEnum = {
  Card: "card",
} as const;
export type CompletePracticePaymentSetupResponsePaymentMethodsInnerTypeEnum =
  (typeof CompletePracticePaymentSetupResponsePaymentMethodsInnerTypeEnum)[keyof typeof CompletePracticePaymentSetupResponsePaymentMethodsInnerTypeEnum];

/**
 * Check if a given object implements the CompletePracticePaymentSetupResponsePaymentMethodsInner interface.
 */
export function instanceOfCompletePracticePaymentSetupResponsePaymentMethodsInner(
  value: object,
): value is CompletePracticePaymentSetupResponsePaymentMethodsInner {
  if (!("brand" in value) || value["brand"] === undefined) return false;
  if (!("expMonth" in value) || value["expMonth"] === undefined) return false;
  if (!("expYear" in value) || value["expYear"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("isPrimary" in value) || value["isPrimary"] === undefined) return false;
  if (!("last4" in value) || value["last4"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function CompletePracticePaymentSetupResponsePaymentMethodsInnerFromJSON(
  json: any,
): CompletePracticePaymentSetupResponsePaymentMethodsInner {
  return CompletePracticePaymentSetupResponsePaymentMethodsInnerFromJSONTyped(json, false);
}

export function CompletePracticePaymentSetupResponsePaymentMethodsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompletePracticePaymentSetupResponsePaymentMethodsInner {
  if (json == null) {
    return json;
  }
  return {
    brand: json["brand"],
    expMonth: json["expMonth"],
    expYear: json["expYear"],
    id: json["id"],
    isPrimary: json["isPrimary"],
    last4: json["last4"],
    type: json["type"],
  };
}

export function CompletePracticePaymentSetupResponsePaymentMethodsInnerToJSON(
  json: any,
): CompletePracticePaymentSetupResponsePaymentMethodsInner {
  return CompletePracticePaymentSetupResponsePaymentMethodsInnerToJSONTyped(json, false);
}

export function CompletePracticePaymentSetupResponsePaymentMethodsInnerToJSONTyped(
  value?: CompletePracticePaymentSetupResponsePaymentMethodsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    brand: value["brand"],
    expMonth: value["expMonth"],
    expYear: value["expYear"],
    id: value["id"],
    isPrimary: value["isPrimary"],
    last4: value["last4"],
    type: value["type"],
  };
}
