/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompletePracticePaymentSetupRequest
 */
export interface CompletePracticePaymentSetupRequest {
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof CompletePracticePaymentSetupRequest
   */
  setupIntentId: string | null;
}

/**
 * Check if a given object implements the CompletePracticePaymentSetupRequest interface.
 */
export function instanceOfCompletePracticePaymentSetupRequest(
  value: object,
): value is CompletePracticePaymentSetupRequest {
  if (!("setupIntentId" in value) || value["setupIntentId"] === undefined) return false;
  return true;
}

export function CompletePracticePaymentSetupRequestFromJSON(
  json: any,
): CompletePracticePaymentSetupRequest {
  return CompletePracticePaymentSetupRequestFromJSONTyped(json, false);
}

export function CompletePracticePaymentSetupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompletePracticePaymentSetupRequest {
  if (json == null) {
    return json;
  }
  return {
    setupIntentId: json["setupIntentId"],
  };
}

export function CompletePracticePaymentSetupRequestToJSON(
  json: any,
): CompletePracticePaymentSetupRequest {
  return CompletePracticePaymentSetupRequestToJSONTyped(json, false);
}

export function CompletePracticePaymentSetupRequestToJSONTyped(
  value?: CompletePracticePaymentSetupRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    setupIntentId: value["setupIntentId"],
  };
}
