/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateOrderRequestPrescriptionsInnerDispensing
 */
export interface CreateOrderRequestPrescriptionsInnerDispensing {
  /**
   *
   * @type {boolean}
   * @memberof CreateOrderRequestPrescriptionsInnerDispensing
   */
  dispenseUponAcceptance?: boolean;
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInnerDispensing
   */
  pharmacyNotes?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInnerDispensing
   */
  requestedFillDate?: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateOrderRequestPrescriptionsInnerDispensing
   */
  substitutionPermitted?: boolean;
}

/**
 * Check if a given object implements the CreateOrderRequestPrescriptionsInnerDispensing interface.
 */
export function instanceOfCreateOrderRequestPrescriptionsInnerDispensing(
  value: object,
): value is CreateOrderRequestPrescriptionsInnerDispensing {
  return true;
}

export function CreateOrderRequestPrescriptionsInnerDispensingFromJSON(
  json: any,
): CreateOrderRequestPrescriptionsInnerDispensing {
  return CreateOrderRequestPrescriptionsInnerDispensingFromJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerDispensingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderRequestPrescriptionsInnerDispensing {
  if (json == null) {
    return json;
  }
  return {
    dispenseUponAcceptance:
      json["dispenseUponAcceptance"] == null ? undefined : json["dispenseUponAcceptance"],
    pharmacyNotes: json["pharmacyNotes"] == null ? undefined : json["pharmacyNotes"],
    requestedFillDate: json["requestedFillDate"] == null ? undefined : json["requestedFillDate"],
    substitutionPermitted:
      json["substitutionPermitted"] == null ? undefined : json["substitutionPermitted"],
  };
}

export function CreateOrderRequestPrescriptionsInnerDispensingToJSON(
  json: any,
): CreateOrderRequestPrescriptionsInnerDispensing {
  return CreateOrderRequestPrescriptionsInnerDispensingToJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerDispensingToJSONTyped(
  value?: CreateOrderRequestPrescriptionsInnerDispensing | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    dispenseUponAcceptance: value["dispenseUponAcceptance"],
    pharmacyNotes: value["pharmacyNotes"],
    requestedFillDate: value["requestedFillDate"],
    substitutionPermitted: value["substitutionPermitted"],
  };
}
