/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreatePatientRequestAddress
 */
export interface CreatePatientRequestAddress {
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestAddress
   */
  city: string;
  /**
   *
   * @type {CreatePatientRequestAddressCountryEnum}
   * @memberof CreatePatientRequestAddress
   */
  country?: CreatePatientRequestAddressCountryEnum;
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestAddress
   */
  line1: string;
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestAddress
   */
  line2?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestAddress
   */
  postalCode: string;
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestAddress
   */
  state: string;
}

/**
 * @export
 */
export const CreatePatientRequestAddressCountryEnum = {
  Us: "US",
} as const;
export type CreatePatientRequestAddressCountryEnum =
  (typeof CreatePatientRequestAddressCountryEnum)[keyof typeof CreatePatientRequestAddressCountryEnum];

/**
 * Check if a given object implements the CreatePatientRequestAddress interface.
 */
export function instanceOfCreatePatientRequestAddress(
  value: object,
): value is CreatePatientRequestAddress {
  if (!("city" in value) || value["city"] === undefined) return false;
  if (!("line1" in value) || value["line1"] === undefined) return false;
  if (!("postalCode" in value) || value["postalCode"] === undefined) return false;
  if (!("state" in value) || value["state"] === undefined) return false;
  return true;
}

export function CreatePatientRequestAddressFromJSON(json: any): CreatePatientRequestAddress {
  return CreatePatientRequestAddressFromJSONTyped(json, false);
}

export function CreatePatientRequestAddressFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatePatientRequestAddress {
  if (json == null) {
    return json;
  }
  return {
    city: json["city"],
    country: json["country"] == null ? undefined : json["country"],
    line1: json["line1"],
    line2: json["line2"] == null ? undefined : json["line2"],
    postalCode: json["postalCode"],
    state: json["state"],
  };
}

export function CreatePatientRequestAddressToJSON(json: any): CreatePatientRequestAddress {
  return CreatePatientRequestAddressToJSONTyped(json, false);
}

export function CreatePatientRequestAddressToJSONTyped(
  value?: CreatePatientRequestAddress | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    city: value["city"],
    country: value["country"],
    line1: value["line1"],
    line2: value["line2"],
    postalCode: value["postalCode"],
    state: value["state"],
  };
}
