/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrderRequestPatientClinicalProfileHeightInches } from "./CreateOrderRequestPatientClinicalProfileHeightInches";
import {
  CreateOrderRequestPatientClinicalProfileHeightInchesFromJSON,
  CreateOrderRequestPatientClinicalProfileHeightInchesFromJSONTyped,
  CreateOrderRequestPatientClinicalProfileHeightInchesToJSON,
  CreateOrderRequestPatientClinicalProfileHeightInchesToJSONTyped,
} from "./CreateOrderRequestPatientClinicalProfileHeightInches";

/**
 *
 * @export
 * @interface CreatePatientRequestMeasurementsInner
 */
export interface CreatePatientRequestMeasurementsInner {
  /**
   *
   * @type {CreateOrderRequestPatientClinicalProfileHeightInches}
   * @memberof CreatePatientRequestMeasurementsInner
   */
  heightCentimeters: CreateOrderRequestPatientClinicalProfileHeightInches | null;
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestMeasurementsInner
   */
  recordedAt: string;
  /**
   *
   * @type {string}
   * @memberof CreatePatientRequestMeasurementsInner
   */
  source: string;
  /**
   *
   * @type {CreateOrderRequestPatientClinicalProfileHeightInches}
   * @memberof CreatePatientRequestMeasurementsInner
   */
  weightKilograms: CreateOrderRequestPatientClinicalProfileHeightInches | null;
}

/**
 * Check if a given object implements the CreatePatientRequestMeasurementsInner interface.
 */
export function instanceOfCreatePatientRequestMeasurementsInner(
  value: object,
): value is CreatePatientRequestMeasurementsInner {
  if (!("heightCentimeters" in value) || value["heightCentimeters"] === undefined) return false;
  if (!("recordedAt" in value) || value["recordedAt"] === undefined) return false;
  if (!("source" in value) || value["source"] === undefined) return false;
  if (!("weightKilograms" in value) || value["weightKilograms"] === undefined) return false;
  return true;
}

export function CreatePatientRequestMeasurementsInnerFromJSON(
  json: any,
): CreatePatientRequestMeasurementsInner {
  return CreatePatientRequestMeasurementsInnerFromJSONTyped(json, false);
}

export function CreatePatientRequestMeasurementsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatePatientRequestMeasurementsInner {
  if (json == null) {
    return json;
  }
  return {
    heightCentimeters: CreateOrderRequestPatientClinicalProfileHeightInchesFromJSON(
      json["heightCentimeters"],
    ),
    recordedAt: json["recordedAt"],
    source: json["source"],
    weightKilograms: CreateOrderRequestPatientClinicalProfileHeightInchesFromJSON(
      json["weightKilograms"],
    ),
  };
}

export function CreatePatientRequestMeasurementsInnerToJSON(
  json: any,
): CreatePatientRequestMeasurementsInner {
  return CreatePatientRequestMeasurementsInnerToJSONTyped(json, false);
}

export function CreatePatientRequestMeasurementsInnerToJSONTyped(
  value?: CreatePatientRequestMeasurementsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    heightCentimeters: CreateOrderRequestPatientClinicalProfileHeightInchesToJSON(
      value["heightCentimeters"],
    ),
    recordedAt: value["recordedAt"],
    source: value["source"],
    weightKilograms: CreateOrderRequestPatientClinicalProfileHeightInchesToJSON(
      value["weightKilograms"],
    ),
  };
}
