/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrderRequestPrescriberProfile } from "./CreateOrderRequestPrescriberProfile";
import {
  CreateOrderRequestPrescriberProfileFromJSON,
  CreateOrderRequestPrescriberProfileFromJSONTyped,
  CreateOrderRequestPrescriberProfileToJSON,
  CreateOrderRequestPrescriberProfileToJSONTyped,
} from "./CreateOrderRequestPrescriberProfile";

/**
 *
 * @export
 * @interface CreateOrderRequestPrescriber
 */
export interface CreateOrderRequestPrescriber {
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriber
   */
  id?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriber
   */
  npi?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriber
   */
  externalId?: string | null;
  /**
   *
   * @type {CreateOrderRequestPrescriberProfile}
   * @memberof CreateOrderRequestPrescriber
   */
  profile?: CreateOrderRequestPrescriberProfile | null;
}

/**
 * Check if a given object implements the CreateOrderRequestPrescriber interface.
 */
export function instanceOfCreateOrderRequestPrescriber(
  value: object,
): value is CreateOrderRequestPrescriber {
  return true;
}

export function CreateOrderRequestPrescriberFromJSON(json: any): CreateOrderRequestPrescriber {
  return CreateOrderRequestPrescriberFromJSONTyped(json, false);
}

export function CreateOrderRequestPrescriberFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderRequestPrescriber {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    npi: json["npi"] == null ? undefined : json["npi"],
    externalId: json["externalId"] == null ? undefined : json["externalId"],
    profile:
      json["profile"] == null
        ? undefined
        : CreateOrderRequestPrescriberProfileFromJSON(json["profile"]),
  };
}

export function CreateOrderRequestPrescriberToJSON(json: any): CreateOrderRequestPrescriber {
  return CreateOrderRequestPrescriberToJSONTyped(json, false);
}

export function CreateOrderRequestPrescriberToJSONTyped(
  value?: CreateOrderRequestPrescriber | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    npi: value["npi"],
    externalId: value["externalId"],
    profile: CreateOrderRequestPrescriberProfileToJSON(value["profile"]),
  };
}
