/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  email?: string | null;
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof CreateUserRequest
   */
  externalId: string | null;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof CreateUserRequest
   */
  metadata?: { [key: string]: any };
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof CreateUserRequest
   */
  name?: string | null;
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): value is CreateUserRequest {
  if (!("externalId" in value) || value["externalId"] === undefined) return false;
  return true;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
  return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateUserRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"] == null ? undefined : json["email"],
    externalId: json["externalId"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function CreateUserRequestToJSON(json: any): CreateUserRequest {
  return CreateUserRequestToJSONTyped(json, false);
}

export function CreateUserRequestToJSONTyped(
  value?: CreateUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    externalId: value["externalId"],
    metadata: value["metadata"],
    name: value["name"],
  };
}
