/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListPatientsResponseDataInnerName } from "./ListPatientsResponseDataInnerName";
import {
  ListPatientsResponseDataInnerNameFromJSON,
  ListPatientsResponseDataInnerNameFromJSONTyped,
  ListPatientsResponseDataInnerNameToJSON,
  ListPatientsResponseDataInnerNameToJSONTyped,
} from "./ListPatientsResponseDataInnerName";
import type { ListPatientsResponseDataInnerAddress } from "./ListPatientsResponseDataInnerAddress";
import {
  ListPatientsResponseDataInnerAddressFromJSON,
  ListPatientsResponseDataInnerAddressFromJSONTyped,
  ListPatientsResponseDataInnerAddressToJSON,
  ListPatientsResponseDataInnerAddressToJSONTyped,
} from "./ListPatientsResponseDataInnerAddress";

/**
 *
 * @export
 * @interface CreatePatientResponse
 */
export interface CreatePatientResponse {
  /**
   *
   * @type {ListPatientsResponseDataInnerAddress}
   * @memberof CreatePatientResponse
   */
  address: ListPatientsResponseDataInnerAddress;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponse
   */
  allergies: string;
  /**
   *
   * @type {Date}
   * @memberof CreatePatientResponse
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CreatePatientResponse
   */
  dateOfBirth: Date;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponse
   */
  email: string | null;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponse
   */
  externalId: string;
  /**
   *
   * @type {CreatePatientResponseGenderEnum}
   * @memberof CreatePatientResponse
   */
  gender: CreatePatientResponseGenderEnum;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponse
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof CreatePatientResponse
   */
  livemode: boolean;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof CreatePatientResponse
   */
  metadata: { [key: string]: any };
  /**
   *
   * @type {ListPatientsResponseDataInnerName}
   * @memberof CreatePatientResponse
   */
  name: ListPatientsResponseDataInnerName;
  /**
   *
   * @type {CreatePatientResponseObjectEnum}
   * @memberof CreatePatientResponse
   */
  object: CreatePatientResponseObjectEnum;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponse
   */
  phone: string;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponse
   */
  practiceId: string;
  /**
   *
   * @type {CreatePatientResponseStatusEnum}
   * @memberof CreatePatientResponse
   */
  status: CreatePatientResponseStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof CreatePatientResponse
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const CreatePatientResponseGenderEnum = {
  F: "f",
  M: "m",
  O: "o",
  U: "u",
} as const;
export type CreatePatientResponseGenderEnum =
  (typeof CreatePatientResponseGenderEnum)[keyof typeof CreatePatientResponseGenderEnum];

/**
 * @export
 */
export const CreatePatientResponseObjectEnum = {
  Patient: "patient",
} as const;
export type CreatePatientResponseObjectEnum =
  (typeof CreatePatientResponseObjectEnum)[keyof typeof CreatePatientResponseObjectEnum];

/**
 * @export
 */
export const CreatePatientResponseStatusEnum = {
  Active: "active",
  Inactive: "inactive",
  NeedsReview: "needs_review",
} as const;
export type CreatePatientResponseStatusEnum =
  (typeof CreatePatientResponseStatusEnum)[keyof typeof CreatePatientResponseStatusEnum];

/**
 * Check if a given object implements the CreatePatientResponse interface.
 */
export function instanceOfCreatePatientResponse(value: object): value is CreatePatientResponse {
  if (!("address" in value) || value["address"] === undefined) return false;
  if (!("allergies" in value) || value["allergies"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("dateOfBirth" in value) || value["dateOfBirth"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("externalId" in value) || value["externalId"] === undefined) return false;
  if (!("gender" in value) || value["gender"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("livemode" in value) || value["livemode"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("phone" in value) || value["phone"] === undefined) return false;
  if (!("practiceId" in value) || value["practiceId"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function CreatePatientResponseFromJSON(json: any): CreatePatientResponse {
  return CreatePatientResponseFromJSONTyped(json, false);
}

export function CreatePatientResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatePatientResponse {
  if (json == null) {
    return json;
  }
  return {
    address: ListPatientsResponseDataInnerAddressFromJSON(json["address"]),
    allergies: json["allergies"],
    createdAt: new Date(json["createdAt"]),
    dateOfBirth: new Date(json["dateOfBirth"]),
    email: json["email"],
    externalId: json["externalId"],
    gender: json["gender"],
    id: json["id"],
    livemode: json["livemode"],
    metadata: json["metadata"],
    name: ListPatientsResponseDataInnerNameFromJSON(json["name"]),
    object: json["object"],
    phone: json["phone"],
    practiceId: json["practiceId"],
    status: json["status"],
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function CreatePatientResponseToJSON(json: any): CreatePatientResponse {
  return CreatePatientResponseToJSONTyped(json, false);
}

export function CreatePatientResponseToJSONTyped(
  value?: CreatePatientResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: ListPatientsResponseDataInnerAddressToJSON(value["address"]),
    allergies: value["allergies"],
    createdAt: value["createdAt"].toISOString(),
    dateOfBirth: value["dateOfBirth"].toISOString().substring(0, 10),
    email: value["email"],
    externalId: value["externalId"],
    gender: value["gender"],
    id: value["id"],
    livemode: value["livemode"],
    metadata: value["metadata"],
    name: ListPatientsResponseDataInnerNameToJSON(value["name"]),
    object: value["object"],
    phone: value["phone"],
    practiceId: value["practiceId"],
    status: value["status"],
    updatedAt: value["updatedAt"].toISOString(),
  };
}
