/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreatePrescriptionRequestDispensing
 */
export interface CreatePrescriptionRequestDispensing {
  /**
   *
   * @type {boolean}
   * @memberof CreatePrescriptionRequestDispensing
   */
  dispenseUponAcceptance?: boolean;
  /**
   *
   * @type {string}
   * @memberof CreatePrescriptionRequestDispensing
   */
  pharmacyNotes?: string;
  /**
   *
   * @type {Date}
   * @memberof CreatePrescriptionRequestDispensing
   */
  requestedFillDate?: Date;
  /**
   *
   * @type {boolean}
   * @memberof CreatePrescriptionRequestDispensing
   */
  substitutionPermitted?: boolean;
}

/**
 * Check if a given object implements the CreatePrescriptionRequestDispensing interface.
 */
export function instanceOfCreatePrescriptionRequestDispensing(
  value: object,
): value is CreatePrescriptionRequestDispensing {
  return true;
}

export function CreatePrescriptionRequestDispensingFromJSON(
  json: any,
): CreatePrescriptionRequestDispensing {
  return CreatePrescriptionRequestDispensingFromJSONTyped(json, false);
}

export function CreatePrescriptionRequestDispensingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatePrescriptionRequestDispensing {
  if (json == null) {
    return json;
  }
  return {
    dispenseUponAcceptance:
      json["dispenseUponAcceptance"] == null ? undefined : json["dispenseUponAcceptance"],
    pharmacyNotes: json["pharmacyNotes"] == null ? undefined : json["pharmacyNotes"],
    requestedFillDate:
      json["requestedFillDate"] == null ? undefined : new Date(json["requestedFillDate"]),
    substitutionPermitted:
      json["substitutionPermitted"] == null ? undefined : json["substitutionPermitted"],
  };
}

export function CreatePrescriptionRequestDispensingToJSON(
  json: any,
): CreatePrescriptionRequestDispensing {
  return CreatePrescriptionRequestDispensingToJSONTyped(json, false);
}

export function CreatePrescriptionRequestDispensingToJSONTyped(
  value?: CreatePrescriptionRequestDispensing | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    dispenseUponAcceptance: value["dispenseUponAcceptance"],
    pharmacyNotes: value["pharmacyNotes"],
    requestedFillDate:
      value["requestedFillDate"] == null
        ? value["requestedFillDate"]
        : value["requestedFillDate"].toISOString().substring(0, 10),
    substitutionPermitted: value["substitutionPermitted"],
  };
}
