/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrderRequestPrescriptionsInner } from "./CreateOrderRequestPrescriptionsInner";
import {
  CreateOrderRequestPrescriptionsInnerFromJSON,
  CreateOrderRequestPrescriptionsInnerFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerToJSON,
  CreateOrderRequestPrescriptionsInnerToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInner";
import type { ListOrdersResponseDataInnerMetadataValue } from "./ListOrdersResponseDataInnerMetadataValue";
import {
  ListOrdersResponseDataInnerMetadataValueFromJSON,
  ListOrdersResponseDataInnerMetadataValueFromJSONTyped,
  ListOrdersResponseDataInnerMetadataValueToJSON,
  ListOrdersResponseDataInnerMetadataValueToJSONTyped,
} from "./ListOrdersResponseDataInnerMetadataValue";
import type { CreateOrderRequestPatient } from "./CreateOrderRequestPatient";
import {
  CreateOrderRequestPatientFromJSON,
  CreateOrderRequestPatientFromJSONTyped,
  CreateOrderRequestPatientToJSON,
  CreateOrderRequestPatientToJSONTyped,
} from "./CreateOrderRequestPatient";

/**
 *
 * @export
 * @interface CreateOrderBatchRequestOrdersInner
 */
export interface CreateOrderBatchRequestOrdersInner {
  /**
   *
   * @type {string}
   * @memberof CreateOrderBatchRequestOrdersInner
   */
  externalOrderId?: string | null;
  /**
   *
   * @type {{ [key: string]: ListOrdersResponseDataInnerMetadataValue; }}
   * @memberof CreateOrderBatchRequestOrdersInner
   */
  metadata?: { [key: string]: ListOrdersResponseDataInnerMetadataValue } | null;
  /**
   *
   * @type {string}
   * @memberof CreateOrderBatchRequestOrdersInner
   */
  patientId?: string | null;
  /**
   *
   * @type {CreateOrderRequestPatient}
   * @memberof CreateOrderBatchRequestOrdersInner
   */
  patient?: CreateOrderRequestPatient | null;
  /**
   *
   * @type {string}
   * @memberof CreateOrderBatchRequestOrdersInner
   */
  shippingAddressId?: string | null;
  /**
   *
   * @type {Array<CreateOrderRequestPrescriptionsInner>}
   * @memberof CreateOrderBatchRequestOrdersInner
   */
  prescriptions: Array<CreateOrderRequestPrescriptionsInner>;
}

/**
 * Check if a given object implements the CreateOrderBatchRequestOrdersInner interface.
 */
export function instanceOfCreateOrderBatchRequestOrdersInner(
  value: object,
): value is CreateOrderBatchRequestOrdersInner {
  if (!("prescriptions" in value) || value["prescriptions"] === undefined) return false;
  return true;
}

export function CreateOrderBatchRequestOrdersInnerFromJSON(
  json: any,
): CreateOrderBatchRequestOrdersInner {
  return CreateOrderBatchRequestOrdersInnerFromJSONTyped(json, false);
}

export function CreateOrderBatchRequestOrdersInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderBatchRequestOrdersInner {
  if (json == null) {
    return json;
  }
  return {
    externalOrderId: json["externalOrderId"] == null ? undefined : json["externalOrderId"],
    metadata:
      json["metadata"] == null
        ? undefined
        : mapValues(json["metadata"], ListOrdersResponseDataInnerMetadataValueFromJSON),
    patientId: json["patientId"] == null ? undefined : json["patientId"],
    patient:
      json["patient"] == null ? undefined : CreateOrderRequestPatientFromJSON(json["patient"]),
    shippingAddressId: json["shippingAddressId"] == null ? undefined : json["shippingAddressId"],
    prescriptions: (json["prescriptions"] as Array<any>).map(
      CreateOrderRequestPrescriptionsInnerFromJSON,
    ),
  };
}

export function CreateOrderBatchRequestOrdersInnerToJSON(
  json: any,
): CreateOrderBatchRequestOrdersInner {
  return CreateOrderBatchRequestOrdersInnerToJSONTyped(json, false);
}

export function CreateOrderBatchRequestOrdersInnerToJSONTyped(
  value?: CreateOrderBatchRequestOrdersInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    externalOrderId: value["externalOrderId"],
    metadata:
      value["metadata"] == null
        ? undefined
        : mapValues(value["metadata"], ListOrdersResponseDataInnerMetadataValueToJSON),
    patientId: value["patientId"],
    patient: CreateOrderRequestPatientToJSON(value["patient"]),
    shippingAddressId: value["shippingAddressId"],
    prescriptions: (value["prescriptions"] as Array<any>).map(
      CreateOrderRequestPrescriptionsInnerToJSON,
    ),
  };
}
