/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateOrder200ResponseOrderRouting
 */
export interface CreateOrder200ResponseOrderRouting {
  /**
   *
   * @type {Array<string>}
   * @memberof CreateOrder200ResponseOrderRouting
   */
  blockedReasons: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateOrder200ResponseOrderRouting
   */
  candidateCompounderIds: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof CreateOrder200ResponseOrderRouting
   */
  coldShip: boolean;
  /**
   *
   * @type {string}
   * @memberof CreateOrder200ResponseOrderRouting
   */
  selectedCompounderId: string | null;
}

/**
 * Check if a given object implements the CreateOrder200ResponseOrderRouting interface.
 */
export function instanceOfCreateOrder200ResponseOrderRouting(
  value: object,
): value is CreateOrder200ResponseOrderRouting {
  if (!("blockedReasons" in value) || value["blockedReasons"] === undefined) return false;
  if (!("candidateCompounderIds" in value) || value["candidateCompounderIds"] === undefined)
    return false;
  if (!("coldShip" in value) || value["coldShip"] === undefined) return false;
  if (!("selectedCompounderId" in value) || value["selectedCompounderId"] === undefined)
    return false;
  return true;
}

export function CreateOrder200ResponseOrderRoutingFromJSON(
  json: any,
): CreateOrder200ResponseOrderRouting {
  return CreateOrder200ResponseOrderRoutingFromJSONTyped(json, false);
}

export function CreateOrder200ResponseOrderRoutingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrder200ResponseOrderRouting {
  if (json == null) {
    return json;
  }
  return {
    blockedReasons: json["blockedReasons"],
    candidateCompounderIds: json["candidateCompounderIds"],
    coldShip: json["coldShip"],
    selectedCompounderId: json["selectedCompounderId"],
  };
}

export function CreateOrder200ResponseOrderRoutingToJSON(
  json: any,
): CreateOrder200ResponseOrderRouting {
  return CreateOrder200ResponseOrderRoutingToJSONTyped(json, false);
}

export function CreateOrder200ResponseOrderRoutingToJSONTyped(
  value?: CreateOrder200ResponseOrderRouting | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    blockedReasons: value["blockedReasons"],
    candidateCompounderIds: value["candidateCompounderIds"],
    coldShip: value["coldShip"],
    selectedCompounderId: value["selectedCompounderId"],
  };
}
