/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrderRequestPrescriptionsInnerStructuredSig } from "./CreateOrderRequestPrescriptionsInnerStructuredSig";
import {
  CreateOrderRequestPrescriptionsInnerStructuredSigFromJSON,
  CreateOrderRequestPrescriptionsInnerStructuredSigFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerStructuredSigToJSON,
  CreateOrderRequestPrescriptionsInnerStructuredSigToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInnerStructuredSig";
import type { CreateOrderRequestPrescriptionsInnerClinical } from "./CreateOrderRequestPrescriptionsInnerClinical";
import {
  CreateOrderRequestPrescriptionsInnerClinicalFromJSON,
  CreateOrderRequestPrescriptionsInnerClinicalFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerClinicalToJSON,
  CreateOrderRequestPrescriptionsInnerClinicalToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInnerClinical";
import type { CreateOrderRequestPrescriptionsInnerDispensing } from "./CreateOrderRequestPrescriptionsInnerDispensing";
import {
  CreateOrderRequestPrescriptionsInnerDispensingFromJSON,
  CreateOrderRequestPrescriptionsInnerDispensingFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerDispensingToJSON,
  CreateOrderRequestPrescriptionsInnerDispensingToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInnerDispensing";

/**
 *
 * @export
 * @interface CreateOrderRequestPrescriptionsInner
 */
export interface CreateOrderRequestPrescriptionsInner {
  /**
   *
   * @type {CreateOrderRequestPrescriptionsInnerClinical}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  clinical?: CreateOrderRequestPrescriptionsInnerClinical;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  compounderId?: string;
  /**
   *
   * @type {number}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  daysSupply: number;
  /**
   *
   * @type {CreateOrderRequestPrescriptionsInnerDispensing}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  dispensing: CreateOrderRequestPrescriptionsInnerDispensing;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  directions: string;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  medicationId: string;
  /**
   *
   * @type {number}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  quantity: number;
  /**
   * The provider's professional credentials, such as MD or DO.
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  quantityUnit: string | null;
  /**
   *
   * @type {number}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  refills: number;
  /**
   *
   * @type {CreateOrderRequestPrescriptionsInnerStructuredSig}
   * @memberof CreateOrderRequestPrescriptionsInner
   */
  structuredSig: CreateOrderRequestPrescriptionsInnerStructuredSig;
}

/**
 * Check if a given object implements the CreateOrderRequestPrescriptionsInner interface.
 */
export function instanceOfCreateOrderRequestPrescriptionsInner(
  value: object,
): value is CreateOrderRequestPrescriptionsInner {
  if (!("daysSupply" in value) || value["daysSupply"] === undefined) return false;
  if (!("dispensing" in value) || value["dispensing"] === undefined) return false;
  if (!("directions" in value) || value["directions"] === undefined) return false;
  if (!("medicationId" in value) || value["medicationId"] === undefined) return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  if (!("quantityUnit" in value) || value["quantityUnit"] === undefined) return false;
  if (!("refills" in value) || value["refills"] === undefined) return false;
  if (!("structuredSig" in value) || value["structuredSig"] === undefined) return false;
  return true;
}

export function CreateOrderRequestPrescriptionsInnerFromJSON(
  json: any,
): CreateOrderRequestPrescriptionsInner {
  return CreateOrderRequestPrescriptionsInnerFromJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderRequestPrescriptionsInner {
  if (json == null) {
    return json;
  }
  return {
    clinical:
      json["clinical"] == null
        ? undefined
        : CreateOrderRequestPrescriptionsInnerClinicalFromJSON(json["clinical"]),
    compounderId: json["compounderId"] == null ? undefined : json["compounderId"],
    daysSupply: json["daysSupply"],
    dispensing: CreateOrderRequestPrescriptionsInnerDispensingFromJSON(json["dispensing"]),
    directions: json["directions"],
    medicationId: json["medicationId"],
    quantity: json["quantity"],
    quantityUnit: json["quantityUnit"],
    refills: json["refills"],
    structuredSig: CreateOrderRequestPrescriptionsInnerStructuredSigFromJSON(json["structuredSig"]),
  };
}

export function CreateOrderRequestPrescriptionsInnerToJSON(
  json: any,
): CreateOrderRequestPrescriptionsInner {
  return CreateOrderRequestPrescriptionsInnerToJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerToJSONTyped(
  value?: CreateOrderRequestPrescriptionsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clinical: CreateOrderRequestPrescriptionsInnerClinicalToJSON(value["clinical"]),
    compounderId: value["compounderId"],
    daysSupply: value["daysSupply"],
    dispensing: CreateOrderRequestPrescriptionsInnerDispensingToJSON(value["dispensing"]),
    directions: value["directions"],
    medicationId: value["medicationId"],
    quantity: value["quantity"],
    quantityUnit: value["quantityUnit"],
    refills: value["refills"],
    structuredSig: CreateOrderRequestPrescriptionsInnerStructuredSigToJSON(value["structuredSig"]),
  };
}
