/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue
 */
export interface CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue {}

/**
 * Check if a given object implements the CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue interface.
 */
export function instanceOfCreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue(
  value: object,
): value is CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue {
  return true;
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueFromJSON(
  json: any,
): CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue {
  return CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueFromJSONTyped(
    json,
    false,
  );
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue {
  return json;
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueToJSON(
  json: any,
): CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue {
  return CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueToJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueToJSONTyped(
  value?: CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
