/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax } from "./ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax";
import {
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSON,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSONTyped,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSON,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSONTyped,
} from "./ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax";

/**
 *
 * @export
 * @interface CreatePatientResponseClinicalProfile
 */
export interface CreatePatientResponseClinicalProfile {
  /**
   *
   * @type {Array<string>}
   * @memberof CreatePatientResponseClinicalProfile
   */
  currentMedications: Array<string>;
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax}
   * @memberof CreatePatientResponseClinicalProfile
   */
  heightInches: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax | null;
  /**
   *
   * @type {string}
   * @memberof CreatePatientResponseClinicalProfile
   */
  reviewedAt: string | null;
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax}
   * @memberof CreatePatientResponseClinicalProfile
   */
  weightPounds: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax | null;
}

/**
 * Check if a given object implements the CreatePatientResponseClinicalProfile interface.
 */
export function instanceOfCreatePatientResponseClinicalProfile(
  value: object,
): value is CreatePatientResponseClinicalProfile {
  if (!("currentMedications" in value) || value["currentMedications"] === undefined) return false;
  if (!("heightInches" in value) || value["heightInches"] === undefined) return false;
  if (!("reviewedAt" in value) || value["reviewedAt"] === undefined) return false;
  if (!("weightPounds" in value) || value["weightPounds"] === undefined) return false;
  return true;
}

export function CreatePatientResponseClinicalProfileFromJSON(
  json: any,
): CreatePatientResponseClinicalProfile {
  return CreatePatientResponseClinicalProfileFromJSONTyped(json, false);
}

export function CreatePatientResponseClinicalProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatePatientResponseClinicalProfile {
  if (json == null) {
    return json;
  }
  return {
    currentMedications: json["currentMedications"],
    heightInches:
      ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSON(
        json["heightInches"],
      ),
    reviewedAt: json["reviewedAt"],
    weightPounds:
      ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSON(
        json["weightPounds"],
      ),
  };
}

export function CreatePatientResponseClinicalProfileToJSON(
  json: any,
): CreatePatientResponseClinicalProfile {
  return CreatePatientResponseClinicalProfileToJSONTyped(json, false);
}

export function CreatePatientResponseClinicalProfileToJSONTyped(
  value?: CreatePatientResponseClinicalProfile | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentMedications: value["currentMedications"],
    heightInches:
      ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSON(
        value["heightInches"],
      ),
    reviewedAt: value["reviewedAt"],
    weightPounds:
      ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSON(
        value["weightPounds"],
      ),
  };
}
