/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateOrderRequestPatientExternalIdentitiesInner
 */
export interface CreateOrderRequestPatientExternalIdentitiesInner {
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPatientExternalIdentitiesInner
   */
  source: string;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPatientExternalIdentitiesInner
   */
  value: string;
}

/**
 * Check if a given object implements the CreateOrderRequestPatientExternalIdentitiesInner interface.
 */
export function instanceOfCreateOrderRequestPatientExternalIdentitiesInner(
  value: object,
): value is CreateOrderRequestPatientExternalIdentitiesInner {
  if (!("source" in value) || value["source"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function CreateOrderRequestPatientExternalIdentitiesInnerFromJSON(
  json: any,
): CreateOrderRequestPatientExternalIdentitiesInner {
  return CreateOrderRequestPatientExternalIdentitiesInnerFromJSONTyped(json, false);
}

export function CreateOrderRequestPatientExternalIdentitiesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderRequestPatientExternalIdentitiesInner {
  if (json == null) {
    return json;
  }
  return {
    source: json["source"],
    value: json["value"],
  };
}

export function CreateOrderRequestPatientExternalIdentitiesInnerToJSON(
  json: any,
): CreateOrderRequestPatientExternalIdentitiesInner {
  return CreateOrderRequestPatientExternalIdentitiesInnerToJSONTyped(json, false);
}

export function CreateOrderRequestPatientExternalIdentitiesInnerToJSONTyped(
  value?: CreateOrderRequestPatientExternalIdentitiesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    source: value["source"],
    value: value["value"],
  };
}
