/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateComponentSessionRequestComponents } from "./CreateComponentSessionRequestComponents";
import {
  CreateComponentSessionRequestComponentsFromJSON,
  CreateComponentSessionRequestComponentsFromJSONTyped,
  CreateComponentSessionRequestComponentsToJSON,
  CreateComponentSessionRequestComponentsToJSONTyped,
} from "./CreateComponentSessionRequestComponents";
import type { CreateComponentSessionRequestContext } from "./CreateComponentSessionRequestContext";
import {
  CreateComponentSessionRequestContextFromJSON,
  CreateComponentSessionRequestContextFromJSONTyped,
  CreateComponentSessionRequestContextToJSON,
  CreateComponentSessionRequestContextToJSONTyped,
} from "./CreateComponentSessionRequestContext";
import type { CreateComponentSessionRequestConsent } from "./CreateComponentSessionRequestConsent";
import {
  CreateComponentSessionRequestConsentFromJSON,
  CreateComponentSessionRequestConsentFromJSONTyped,
  CreateComponentSessionRequestConsentToJSON,
  CreateComponentSessionRequestConsentToJSONTyped,
} from "./CreateComponentSessionRequestConsent";

/**
 *
 * @export
 * @interface CreateComponentSessionRequest
 */
export interface CreateComponentSessionRequest {
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof CreateComponentSessionRequest
   */
  allowedOrigin: string | null;
  /**
   *
   * @type {CreateComponentSessionRequestComponents}
   * @memberof CreateComponentSessionRequest
   */
  components: CreateComponentSessionRequestComponents;
  /**
   *
   * @type {CreateComponentSessionRequestConsent}
   * @memberof CreateComponentSessionRequest
   */
  consent: CreateComponentSessionRequestConsent;
  /**
   *
   * @type {CreateComponentSessionRequestContext}
   * @memberof CreateComponentSessionRequest
   */
  context: CreateComponentSessionRequestContext;
  /**
   *
   * @type {string}
   * @memberof CreateComponentSessionRequest
   */
  practiceId: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateComponentSessionRequest
   */
  userId: string;
}

/**
 * Check if a given object implements the CreateComponentSessionRequest interface.
 */
export function instanceOfCreateComponentSessionRequest(
  value: object,
): value is CreateComponentSessionRequest {
  if (!("allowedOrigin" in value) || value["allowedOrigin"] === undefined) return false;
  if (!("components" in value) || value["components"] === undefined) return false;
  if (!("consent" in value) || value["consent"] === undefined) return false;
  if (!("context" in value) || value["context"] === undefined) return false;
  if (!("practiceId" in value) || value["practiceId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  return true;
}

export function CreateComponentSessionRequestFromJSON(json: any): CreateComponentSessionRequest {
  return CreateComponentSessionRequestFromJSONTyped(json, false);
}

export function CreateComponentSessionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateComponentSessionRequest {
  if (json == null) {
    return json;
  }
  return {
    allowedOrigin: json["allowedOrigin"],
    components: CreateComponentSessionRequestComponentsFromJSON(json["components"]),
    consent: CreateComponentSessionRequestConsentFromJSON(json["consent"]),
    context: CreateComponentSessionRequestContextFromJSON(json["context"]),
    practiceId: json["practiceId"],
    userId: json["userId"],
  };
}

export function CreateComponentSessionRequestToJSON(json: any): CreateComponentSessionRequest {
  return CreateComponentSessionRequestToJSONTyped(json, false);
}

export function CreateComponentSessionRequestToJSONTyped(
  value?: CreateComponentSessionRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    allowedOrigin: value["allowedOrigin"],
    components: CreateComponentSessionRequestComponentsToJSON(value["components"]),
    consent: CreateComponentSessionRequestConsentToJSON(value["consent"]),
    context: CreateComponentSessionRequestContextToJSON(value["context"]),
    practiceId: value["practiceId"],
    userId: value["userId"],
  };
}
