/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue } from "./CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue";
import {
  CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueFromJSON,
  CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueToJSON,
  CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue";

/**
 *
 * @export
 * @interface CreateOrderRequestPrescriptionsInnerClinicalObservationsInner
 */
export interface CreateOrderRequestPrescriptionsInnerClinicalObservationsInner {
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInnerClinicalObservationsInner
   */
  display: string;
  /**
   *
   * @type {string}
   * @memberof CreateOrderRequestPrescriptionsInnerClinicalObservationsInner
   */
  unit: string;
  /**
   *
   * @type {CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue}
   * @memberof CreateOrderRequestPrescriptionsInnerClinicalObservationsInner
   */
  value: CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValue;
}

/**
 * Check if a given object implements the CreateOrderRequestPrescriptionsInnerClinicalObservationsInner interface.
 */
export function instanceOfCreateOrderRequestPrescriptionsInnerClinicalObservationsInner(
  value: object,
): value is CreateOrderRequestPrescriptionsInnerClinicalObservationsInner {
  if (!("display" in value) || value["display"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerFromJSON(
  json: any,
): CreateOrderRequestPrescriptionsInnerClinicalObservationsInner {
  return CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerFromJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOrderRequestPrescriptionsInnerClinicalObservationsInner {
  if (json == null) {
    return json;
  }
  return {
    display: json["display"],
    unit: json["unit"],
    value: CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueFromJSON(
      json["value"],
    ),
  };
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerToJSON(
  json: any,
): CreateOrderRequestPrescriptionsInnerClinicalObservationsInner {
  return CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerToJSONTyped(json, false);
}

export function CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerToJSONTyped(
  value?: CreateOrderRequestPrescriptionsInnerClinicalObservationsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    display: value["display"],
    unit: value["unit"],
    value: CreateOrderRequestPrescriptionsInnerClinicalObservationsInnerValueToJSON(value["value"]),
  };
}
