/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetPracticePaymentProfileResponsePaymentMethodsInner
 */
export interface GetPracticePaymentProfileResponsePaymentMethodsInner {
  /**
   *
   * @type {string}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  brand: string;
  /**
   *
   * @type {number}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  expMonth: number | null;
  /**
   *
   * @type {number}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  expYear: number | null;
  /**
   *
   * @type {string}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  isPrimary: boolean;
  /**
   *
   * @type {string}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  last4: string;
  /**
   *
   * @type {GetPracticePaymentProfileResponsePaymentMethodsInnerTypeEnum}
   * @memberof GetPracticePaymentProfileResponsePaymentMethodsInner
   */
  type: GetPracticePaymentProfileResponsePaymentMethodsInnerTypeEnum;
}

/**
 * @export
 */
export const GetPracticePaymentProfileResponsePaymentMethodsInnerTypeEnum = {
  Card: "card",
} as const;
export type GetPracticePaymentProfileResponsePaymentMethodsInnerTypeEnum =
  (typeof GetPracticePaymentProfileResponsePaymentMethodsInnerTypeEnum)[keyof typeof GetPracticePaymentProfileResponsePaymentMethodsInnerTypeEnum];

/**
 * Check if a given object implements the GetPracticePaymentProfileResponsePaymentMethodsInner interface.
 */
export function instanceOfGetPracticePaymentProfileResponsePaymentMethodsInner(
  value: object,
): value is GetPracticePaymentProfileResponsePaymentMethodsInner {
  if (!("brand" in value) || value["brand"] === undefined) return false;
  if (!("expMonth" in value) || value["expMonth"] === undefined) return false;
  if (!("expYear" in value) || value["expYear"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("isPrimary" in value) || value["isPrimary"] === undefined) return false;
  if (!("last4" in value) || value["last4"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function GetPracticePaymentProfileResponsePaymentMethodsInnerFromJSON(
  json: any,
): GetPracticePaymentProfileResponsePaymentMethodsInner {
  return GetPracticePaymentProfileResponsePaymentMethodsInnerFromJSONTyped(json, false);
}

export function GetPracticePaymentProfileResponsePaymentMethodsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPracticePaymentProfileResponsePaymentMethodsInner {
  if (json == null) {
    return json;
  }
  return {
    brand: json["brand"],
    expMonth: json["expMonth"],
    expYear: json["expYear"],
    id: json["id"],
    isPrimary: json["isPrimary"],
    last4: json["last4"],
    type: json["type"],
  };
}

export function GetPracticePaymentProfileResponsePaymentMethodsInnerToJSON(
  json: any,
): GetPracticePaymentProfileResponsePaymentMethodsInner {
  return GetPracticePaymentProfileResponsePaymentMethodsInnerToJSONTyped(json, false);
}

export function GetPracticePaymentProfileResponsePaymentMethodsInnerToJSONTyped(
  value?: GetPracticePaymentProfileResponsePaymentMethodsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    brand: value["brand"],
    expMonth: value["expMonth"],
    expYear: value["expYear"],
    id: value["id"],
    isPrimary: value["isPrimary"],
    last4: value["last4"],
    type: value["type"],
  };
}
