/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProvider } from "./GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProvider";
import {
  GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProviderFromJSON,
  GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProviderFromJSONTyped,
  GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProviderToJSON,
  GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProviderToJSONTyped,
} from "./GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProvider";

/**
 *
 * @export
 * @interface GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection
 */
export interface GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection {
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection
   */
  status: string | null;
  /**
   *
   * @type {GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProvider}
   * @memberof GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection
   */
  provider: GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProvider;
}

/**
 * Check if a given object implements the GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection interface.
 */
export function instanceOfGetPracticeTeamInvitationResponsePersonAccountPrescriberConnection(
  value: object,
): value is GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("provider" in value) || value["provider"] === undefined) return false;
  return true;
}

export function GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionFromJSON(
  json: any,
): GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection {
  return GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionFromJSONTyped(
    json,
    false,
  );
}

export function GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    provider: GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProviderFromJSON(
      json["provider"],
    ),
  };
}

export function GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionToJSON(
  json: any,
): GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection {
  return GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionToJSONTyped(json, false);
}

export function GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionToJSONTyped(
  value?: GetPracticeTeamInvitationResponsePersonAccountPrescriberConnection | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    provider: GetPracticeTeamInvitationResponsePersonAccountPrescriberConnectionProviderToJSON(
      value["provider"],
    ),
  };
}
