/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GetPracticeTeamInvitationResponsePersonInvitationRolesInner } from "./GetPracticeTeamInvitationResponsePersonInvitationRolesInner";
import {
  GetPracticeTeamInvitationResponsePersonInvitationRolesInnerFromJSON,
  GetPracticeTeamInvitationResponsePersonInvitationRolesInnerFromJSONTyped,
  GetPracticeTeamInvitationResponsePersonInvitationRolesInnerToJSON,
  GetPracticeTeamInvitationResponsePersonInvitationRolesInnerToJSONTyped,
} from "./GetPracticeTeamInvitationResponsePersonInvitationRolesInner";

/**
 *
 * @export
 * @interface GetPracticeTeamInvitationResponsePersonInvitation
 */
export interface GetPracticeTeamInvitationResponsePersonInvitation {
  /**
   *
   * @type {string}
   * @memberof GetPracticeTeamInvitationResponsePersonInvitation
   */
  id: string;
  /**
   *
   * @type {GetPracticeTeamInvitationResponsePersonInvitationStatusEnum}
   * @memberof GetPracticeTeamInvitationResponsePersonInvitation
   */
  status: GetPracticeTeamInvitationResponsePersonInvitationStatusEnum | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof GetPracticeTeamInvitationResponsePersonInvitation
   */
  expiresAt: string | null;
  /**
   *
   * @type {Array<GetPracticeTeamInvitationResponsePersonInvitationRolesInner>}
   * @memberof GetPracticeTeamInvitationResponsePersonInvitation
   */
  roles: Array<GetPracticeTeamInvitationResponsePersonInvitationRolesInner>;
}

/**
 * @export
 */
export const GetPracticeTeamInvitationResponsePersonInvitationStatusEnum = {
  Accepted: "accepted",
  Declined: "declined",
  Pending: "pending",
  Expired: "expired",
  Revoked: "revoked",
} as const;
export type GetPracticeTeamInvitationResponsePersonInvitationStatusEnum =
  (typeof GetPracticeTeamInvitationResponsePersonInvitationStatusEnum)[keyof typeof GetPracticeTeamInvitationResponsePersonInvitationStatusEnum];

/**
 * Check if a given object implements the GetPracticeTeamInvitationResponsePersonInvitation interface.
 */
export function instanceOfGetPracticeTeamInvitationResponsePersonInvitation(
  value: object,
): value is GetPracticeTeamInvitationResponsePersonInvitation {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("expiresAt" in value) || value["expiresAt"] === undefined) return false;
  if (!("roles" in value) || value["roles"] === undefined) return false;
  return true;
}

export function GetPracticeTeamInvitationResponsePersonInvitationFromJSON(
  json: any,
): GetPracticeTeamInvitationResponsePersonInvitation {
  return GetPracticeTeamInvitationResponsePersonInvitationFromJSONTyped(json, false);
}

export function GetPracticeTeamInvitationResponsePersonInvitationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPracticeTeamInvitationResponsePersonInvitation {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    status: json["status"],
    expiresAt: json["expiresAt"],
    roles: (json["roles"] as Array<any>).map(
      GetPracticeTeamInvitationResponsePersonInvitationRolesInnerFromJSON,
    ),
  };
}

export function GetPracticeTeamInvitationResponsePersonInvitationToJSON(
  json: any,
): GetPracticeTeamInvitationResponsePersonInvitation {
  return GetPracticeTeamInvitationResponsePersonInvitationToJSONTyped(json, false);
}

export function GetPracticeTeamInvitationResponsePersonInvitationToJSONTyped(
  value?: GetPracticeTeamInvitationResponsePersonInvitation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    status: value["status"],
    expiresAt: value["expiresAt"],
    roles: (value["roles"] as Array<any>).map(
      GetPracticeTeamInvitationResponsePersonInvitationRolesInnerToJSON,
    ),
  };
}
