/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListPracticeTeamMembersResponseDataInnerAccount } from "./ListPracticeTeamMembersResponseDataInnerAccount";
import {
  ListPracticeTeamMembersResponseDataInnerAccountFromJSON,
  ListPracticeTeamMembersResponseDataInnerAccountFromJSONTyped,
  ListPracticeTeamMembersResponseDataInnerAccountToJSON,
  ListPracticeTeamMembersResponseDataInnerAccountToJSONTyped,
} from "./ListPracticeTeamMembersResponseDataInnerAccount";

/**
 *
 * @export
 * @interface GetPracticeTeamMemberResponse
 */
export interface GetPracticeTeamMemberResponse {
  /**
   *
   * @type {string}
   * @memberof GetPracticeTeamMemberResponse
   */
  id: string;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof GetPracticeTeamMemberResponse
   */
  name: string | null;
  /**
   *
   * @type {string}
   * @memberof GetPracticeTeamMemberResponse
   */
  email: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof GetPracticeTeamMemberResponse
   */
  locationIds: Array<string>;
  /**
   *
   * @type {ListPracticeTeamMembersResponseDataInnerAccount}
   * @memberof GetPracticeTeamMemberResponse
   */
  account: ListPracticeTeamMembersResponseDataInnerAccount;
  /**
   *
   * @type {Array<string>}
   * @memberof GetPracticeTeamMemberResponse
   */
  nextActions: Array<string>;
}

/**
 * Check if a given object implements the GetPracticeTeamMemberResponse interface.
 */
export function instanceOfGetPracticeTeamMemberResponse(
  value: object,
): value is GetPracticeTeamMemberResponse {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("locationIds" in value) || value["locationIds"] === undefined) return false;
  if (!("account" in value) || value["account"] === undefined) return false;
  if (!("nextActions" in value) || value["nextActions"] === undefined) return false;
  return true;
}

export function GetPracticeTeamMemberResponseFromJSON(json: any): GetPracticeTeamMemberResponse {
  return GetPracticeTeamMemberResponseFromJSONTyped(json, false);
}

export function GetPracticeTeamMemberResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPracticeTeamMemberResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    email: json["email"],
    locationIds: json["locationIds"],
    account: ListPracticeTeamMembersResponseDataInnerAccountFromJSON(json["account"]),
    nextActions: json["nextActions"],
  };
}

export function GetPracticeTeamMemberResponseToJSON(json: any): GetPracticeTeamMemberResponse {
  return GetPracticeTeamMemberResponseToJSONTyped(json, false);
}

export function GetPracticeTeamMemberResponseToJSONTyped(
  value?: GetPracticeTeamMemberResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    email: value["email"],
    locationIds: value["locationIds"],
    account: ListPracticeTeamMembersResponseDataInnerAccountToJSON(value["account"]),
    nextActions: value["nextActions"],
  };
}
