/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListPracticesResponseDataInnerPrescribersInner } from "./ListPracticesResponseDataInnerPrescribersInner";
import {
  ListPracticesResponseDataInnerPrescribersInnerFromJSON,
  ListPracticesResponseDataInnerPrescribersInnerFromJSONTyped,
  ListPracticesResponseDataInnerPrescribersInnerToJSON,
  ListPracticesResponseDataInnerPrescribersInnerToJSONTyped,
} from "./ListPracticesResponseDataInnerPrescribersInner";
import type { ListPracticesResponseDataInnerAddress } from "./ListPracticesResponseDataInnerAddress";
import {
  ListPracticesResponseDataInnerAddressFromJSON,
  ListPracticesResponseDataInnerAddressFromJSONTyped,
  ListPracticesResponseDataInnerAddressToJSON,
  ListPracticesResponseDataInnerAddressToJSONTyped,
} from "./ListPracticesResponseDataInnerAddress";
import type { ListPracticesResponseDataInnerContacts } from "./ListPracticesResponseDataInnerContacts";
import {
  ListPracticesResponseDataInnerContactsFromJSON,
  ListPracticesResponseDataInnerContactsFromJSONTyped,
  ListPracticesResponseDataInnerContactsToJSON,
  ListPracticesResponseDataInnerContactsToJSONTyped,
} from "./ListPracticesResponseDataInnerContacts";

/**
 *
 * @export
 * @interface GetPracticeResponse
 */
export interface GetPracticeResponse {
  /**
   *
   * @type {ListPracticesResponseDataInnerAddress}
   * @memberof GetPracticeResponse
   */
  address: ListPracticesResponseDataInnerAddress | null;
  /**
   *
   * @type {ListPracticesResponseDataInnerContacts}
   * @memberof GetPracticeResponse
   */
  contacts: ListPracticesResponseDataInnerContacts;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  externalId: string | null;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  legalName: string | null;
  /**
   *
   * @type {boolean}
   * @memberof GetPracticeResponse
   */
  livemode: boolean;
  /**
   *
   * @type {object}
   * @memberof GetPracticeResponse
   */
  metadata: object;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  name: string;
  /**
   *
   * @type {GetPracticeResponseObjectEnum}
   * @memberof GetPracticeResponse
   */
  object: GetPracticeResponseObjectEnum;
  /**
   *
   * @type {Array<ListPracticesResponseDataInnerPrescribersInner>}
   * @memberof GetPracticeResponse
   */
  prescribers: Array<ListPracticesResponseDataInnerPrescribersInner>;
  /**
   * Whether this practice currently has Live access. False for Test practices.
   * @type {boolean}
   * @memberof GetPracticeResponse
   */
  liveEnabled: boolean;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  supportEmail: string | null;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  supportPhone: string | null;
  /**
   *
   * @type {string}
   * @memberof GetPracticeResponse
   */
  timezone: string | null;
}

/**
 * @export
 */
export const GetPracticeResponseObjectEnum = {
  Practice: "practice",
} as const;
export type GetPracticeResponseObjectEnum =
  (typeof GetPracticeResponseObjectEnum)[keyof typeof GetPracticeResponseObjectEnum];

/**
 * Check if a given object implements the GetPracticeResponse interface.
 */
export function instanceOfGetPracticeResponse(value: object): value is GetPracticeResponse {
  if (!("address" in value) || value["address"] === undefined) return false;
  if (!("contacts" in value) || value["contacts"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("externalId" in value) || value["externalId"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("legalName" in value) || value["legalName"] === undefined) return false;
  if (!("livemode" in value) || value["livemode"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("prescribers" in value) || value["prescribers"] === undefined) return false;
  if (!("liveEnabled" in value) || value["liveEnabled"] === undefined) return false;
  if (!("supportEmail" in value) || value["supportEmail"] === undefined) return false;
  if (!("supportPhone" in value) || value["supportPhone"] === undefined) return false;
  if (!("timezone" in value) || value["timezone"] === undefined) return false;
  return true;
}

export function GetPracticeResponseFromJSON(json: any): GetPracticeResponse {
  return GetPracticeResponseFromJSONTyped(json, false);
}

export function GetPracticeResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPracticeResponse {
  if (json == null) {
    return json;
  }
  return {
    address: ListPracticesResponseDataInnerAddressFromJSON(json["address"]),
    contacts: ListPracticesResponseDataInnerContactsFromJSON(json["contacts"]),
    createdAt: json["createdAt"],
    externalId: json["externalId"],
    id: json["id"],
    legalName: json["legalName"],
    livemode: json["livemode"],
    metadata: json["metadata"],
    name: json["name"],
    object: json["object"],
    prescribers: (json["prescribers"] as Array<any>).map(
      ListPracticesResponseDataInnerPrescribersInnerFromJSON,
    ),
    liveEnabled: json["liveEnabled"],
    supportEmail: json["supportEmail"],
    supportPhone: json["supportPhone"],
    timezone: json["timezone"],
  };
}

export function GetPracticeResponseToJSON(json: any): GetPracticeResponse {
  return GetPracticeResponseToJSONTyped(json, false);
}

export function GetPracticeResponseToJSONTyped(
  value?: GetPracticeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: ListPracticesResponseDataInnerAddressToJSON(value["address"]),
    contacts: ListPracticesResponseDataInnerContactsToJSON(value["contacts"]),
    createdAt: value["createdAt"],
    externalId: value["externalId"],
    id: value["id"],
    legalName: value["legalName"],
    livemode: value["livemode"],
    metadata: value["metadata"],
    name: value["name"],
    object: value["object"],
    prescribers: (value["prescribers"] as Array<any>).map(
      ListPracticesResponseDataInnerPrescribersInnerToJSON,
    ),
    liveEnabled: value["liveEnabled"],
    supportEmail: value["supportEmail"],
    supportPhone: value["supportPhone"],
    timezone: value["timezone"],
  };
}
