/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-19
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetWebhookEventResponseAttemptsInner
 */
export interface GetWebhookEventResponseAttemptsInner {
  /**
   *
   * @type {string}
   * @memberof GetWebhookEventResponseAttemptsInner
   */
  attemptedAt: string;
  /**
   *
   * @type {string}
   * @memberof GetWebhookEventResponseAttemptsInner
   */
  errorMessage: string | null;
  /**
   *
   * @type {string}
   * @memberof GetWebhookEventResponseAttemptsInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetWebhookEventResponseAttemptsInner
   */
  responseBody: string | null;
  /**
   *
   * @type {number}
   * @memberof GetWebhookEventResponseAttemptsInner
   */
  responseStatus: number | null;
  /**
   *
   * @type {boolean}
   * @memberof GetWebhookEventResponseAttemptsInner
   */
  success: boolean;
}

/**
 * Check if a given object implements the GetWebhookEventResponseAttemptsInner interface.
 */
export function instanceOfGetWebhookEventResponseAttemptsInner(
  value: object,
): value is GetWebhookEventResponseAttemptsInner {
  if (!("attemptedAt" in value) || value["attemptedAt"] === undefined) return false;
  if (!("errorMessage" in value) || value["errorMessage"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("responseBody" in value) || value["responseBody"] === undefined) return false;
  if (!("responseStatus" in value) || value["responseStatus"] === undefined) return false;
  if (!("success" in value) || value["success"] === undefined) return false;
  return true;
}

export function GetWebhookEventResponseAttemptsInnerFromJSON(
  json: any,
): GetWebhookEventResponseAttemptsInner {
  return GetWebhookEventResponseAttemptsInnerFromJSONTyped(json, false);
}

export function GetWebhookEventResponseAttemptsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWebhookEventResponseAttemptsInner {
  if (json == null) {
    return json;
  }
  return {
    attemptedAt: json["attemptedAt"],
    errorMessage: json["errorMessage"],
    id: json["id"],
    responseBody: json["responseBody"],
    responseStatus: json["responseStatus"],
    success: json["success"],
  };
}

export function GetWebhookEventResponseAttemptsInnerToJSON(
  json: any,
): GetWebhookEventResponseAttemptsInner {
  return GetWebhookEventResponseAttemptsInnerToJSONTyped(json, false);
}

export function GetWebhookEventResponseAttemptsInnerToJSONTyped(
  value?: GetWebhookEventResponseAttemptsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    attemptedAt: value["attemptedAt"],
    errorMessage: value["errorMessage"],
    id: value["id"],
    responseBody: value["responseBody"],
    responseStatus: value["responseStatus"],
    success: value["success"],
  };
}
