/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetWebhookEvent200ResponseAttemptsInner
 */
export interface GetWebhookEvent200ResponseAttemptsInner {
  /**
   *
   * @type {string}
   * @memberof GetWebhookEvent200ResponseAttemptsInner
   */
  attemptedAt: string;
  /**
   *
   * @type {string}
   * @memberof GetWebhookEvent200ResponseAttemptsInner
   */
  errorMessage: string | null;
  /**
   *
   * @type {string}
   * @memberof GetWebhookEvent200ResponseAttemptsInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetWebhookEvent200ResponseAttemptsInner
   */
  responseBody: string | null;
  /**
   *
   * @type {number}
   * @memberof GetWebhookEvent200ResponseAttemptsInner
   */
  responseStatus: number | null;
  /**
   *
   * @type {boolean}
   * @memberof GetWebhookEvent200ResponseAttemptsInner
   */
  success: boolean;
}

/**
 * Check if a given object implements the GetWebhookEvent200ResponseAttemptsInner interface.
 */
export function instanceOfGetWebhookEvent200ResponseAttemptsInner(
  value: object,
): value is GetWebhookEvent200ResponseAttemptsInner {
  if (!("attemptedAt" in value) || value["attemptedAt"] === undefined) return false;
  if (!("errorMessage" in value) || value["errorMessage"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("responseBody" in value) || value["responseBody"] === undefined) return false;
  if (!("responseStatus" in value) || value["responseStatus"] === undefined) return false;
  if (!("success" in value) || value["success"] === undefined) return false;
  return true;
}

export function GetWebhookEvent200ResponseAttemptsInnerFromJSON(
  json: any,
): GetWebhookEvent200ResponseAttemptsInner {
  return GetWebhookEvent200ResponseAttemptsInnerFromJSONTyped(json, false);
}

export function GetWebhookEvent200ResponseAttemptsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWebhookEvent200ResponseAttemptsInner {
  if (json == null) {
    return json;
  }
  return {
    attemptedAt: json["attemptedAt"],
    errorMessage: json["errorMessage"],
    id: json["id"],
    responseBody: json["responseBody"],
    responseStatus: json["responseStatus"],
    success: json["success"],
  };
}

export function GetWebhookEvent200ResponseAttemptsInnerToJSON(
  json: any,
): GetWebhookEvent200ResponseAttemptsInner {
  return GetWebhookEvent200ResponseAttemptsInnerToJSONTyped(json, false);
}

export function GetWebhookEvent200ResponseAttemptsInnerToJSONTyped(
  value?: GetWebhookEvent200ResponseAttemptsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    attemptedAt: value["attemptedAt"],
    errorMessage: value["errorMessage"],
    id: value["id"],
    responseBody: value["responseBody"],
    responseStatus: value["responseStatus"],
    success: value["success"],
  };
}
