/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner
 */
export interface InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner {
  /**
   *
   * @type {string}
   * @memberof InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner
   */
  state: string;
  /**
   *
   * @type {string}
   * @memberof InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner
   */
  licenseNumber: string;
  /**
   *
   * @type {string}
   * @memberof InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner
   */
  expiresAt: string | null;
}

/**
 * Check if a given object implements the InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner interface.
 */
export function instanceOfInvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner(
  value: object,
): value is InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("state" in value) || value["state"] === undefined) return false;
  if (!("licenseNumber" in value) || value["licenseNumber"] === undefined) return false;
  if (!("expiresAt" in value) || value["expiresAt"] === undefined) return false;
  return true;
}

export function InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInnerFromJSON(
  json: any,
): InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner {
  return InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInnerFromJSONTyped(
    json,
    false,
  );
}

export function InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    state: json["state"],
    licenseNumber: json["licenseNumber"],
    expiresAt: json["expiresAt"],
  };
}

export function InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInnerToJSON(
  json: any,
): InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner {
  return InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInnerToJSONTyped(
    json,
    false,
  );
}

export function InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInnerToJSONTyped(
  value?: InvitePracticeTeamPersonResponsePersonAccountPrescriberConnectionProviderLicensesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    state: value["state"],
    licenseNumber: value["licenseNumber"],
    expiresAt: value["expiresAt"],
  };
}
