/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListOrdersResponseDataInnerPrescriptionsInnerDispensing
 */
export interface ListOrdersResponseDataInnerPrescriptionsInnerDispensing {
  /**
   *
   * @type {boolean}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  dispenseUponAcceptance: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  substitutionPermitted: boolean;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  pharmacyNotes?: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  requestedFillDate?: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  shippingOptionId?: string | null;
  /**
   *
   * @type {number}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  shippingAmountCents?: number | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerPrescriptionsInnerDispensingShippingDestinationTypeEnum}
   * @memberof ListOrdersResponseDataInnerPrescriptionsInnerDispensing
   */
  shippingDestinationType?: ListOrdersResponseDataInnerPrescriptionsInnerDispensingShippingDestinationTypeEnum | null;
}

/**
 * @export
 */
export const ListOrdersResponseDataInnerPrescriptionsInnerDispensingShippingDestinationTypeEnum = {
  Patient: "patient",
  Practice: "practice",
} as const;
export type ListOrdersResponseDataInnerPrescriptionsInnerDispensingShippingDestinationTypeEnum =
  (typeof ListOrdersResponseDataInnerPrescriptionsInnerDispensingShippingDestinationTypeEnum)[keyof typeof ListOrdersResponseDataInnerPrescriptionsInnerDispensingShippingDestinationTypeEnum];

/**
 * Check if a given object implements the ListOrdersResponseDataInnerPrescriptionsInnerDispensing interface.
 */
export function instanceOfListOrdersResponseDataInnerPrescriptionsInnerDispensing(
  value: object,
): value is ListOrdersResponseDataInnerPrescriptionsInnerDispensing {
  if (!("dispenseUponAcceptance" in value) || value["dispenseUponAcceptance"] === undefined)
    return false;
  if (!("substitutionPermitted" in value) || value["substitutionPermitted"] === undefined)
    return false;
  return true;
}

export function ListOrdersResponseDataInnerPrescriptionsInnerDispensingFromJSON(
  json: any,
): ListOrdersResponseDataInnerPrescriptionsInnerDispensing {
  return ListOrdersResponseDataInnerPrescriptionsInnerDispensingFromJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerPrescriptionsInnerDispensingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOrdersResponseDataInnerPrescriptionsInnerDispensing {
  if (json == null) {
    return json;
  }
  return {
    dispenseUponAcceptance: json["dispenseUponAcceptance"],
    substitutionPermitted: json["substitutionPermitted"],
    pharmacyNotes: json["pharmacyNotes"] == null ? undefined : json["pharmacyNotes"],
    requestedFillDate: json["requestedFillDate"] == null ? undefined : json["requestedFillDate"],
    shippingOptionId: json["shippingOptionId"] == null ? undefined : json["shippingOptionId"],
    shippingAmountCents:
      json["shippingAmountCents"] == null ? undefined : json["shippingAmountCents"],
    shippingDestinationType:
      json["shippingDestinationType"] == null ? undefined : json["shippingDestinationType"],
  };
}

export function ListOrdersResponseDataInnerPrescriptionsInnerDispensingToJSON(
  json: any,
): ListOrdersResponseDataInnerPrescriptionsInnerDispensing {
  return ListOrdersResponseDataInnerPrescriptionsInnerDispensingToJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerPrescriptionsInnerDispensingToJSONTyped(
  value?: ListOrdersResponseDataInnerPrescriptionsInnerDispensing | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    dispenseUponAcceptance: value["dispenseUponAcceptance"],
    substitutionPermitted: value["substitutionPermitted"],
    pharmacyNotes: value["pharmacyNotes"],
    requestedFillDate: value["requestedFillDate"],
    shippingOptionId: value["shippingOptionId"],
    shippingAmountCents: value["shippingAmountCents"],
    shippingDestinationType: value["shippingDestinationType"],
  };
}
