/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2
 */
export interface ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 {
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2KindEnum}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2
   */
  kind: ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2KindEnum;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2
   */
  unit: string;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2
   */
  minimum: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2
   */
  maximum: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2
   */
  increment: string | null;
}

/**
 * @export
 */
export const ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2KindEnum = {
  Range: "range",
} as const;
export type ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2KindEnum =
  (typeof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2KindEnum)[keyof typeof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2KindEnum];

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerQuantityConstraintOneOf2(
  value: object,
): value is ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 {
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("minimum" in value) || value["minimum"] === undefined) return false;
  if (!("maximum" in value) || value["maximum"] === undefined) return false;
  if (!("increment" in value) || value["increment"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2FromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 {
  return ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2FromJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 {
  if (json == null) {
    return json;
  }
  return {
    kind: json["kind"],
    unit: json["unit"],
    minimum: json["minimum"],
    maximum: json["maximum"],
    increment: json["increment"],
  };
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2ToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 {
  return ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2ToJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2ToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerQuantityConstraintOneOf2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    kind: value["kind"],
    unit: value["unit"],
    minimum: value["minimum"],
    maximum: value["maximum"],
    increment: value["increment"],
  };
}
