/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListShippingOptionsResponseDataInner
 */
export interface ListShippingOptionsResponseDataInner {
  /**
   *
   * @type {number}
   * @memberof ListShippingOptionsResponseDataInner
   */
  amountCents: number;
  /**
   *
   * @type {string}
   * @memberof ListShippingOptionsResponseDataInner
   */
  carrier: string | null;
  /**
   *
   * @type {ListShippingOptionsResponseDataInnerCurrencyEnum}
   * @memberof ListShippingOptionsResponseDataInner
   */
  currency: ListShippingOptionsResponseDataInnerCurrencyEnum;
  /**
   *
   * @type {number}
   * @memberof ListShippingOptionsResponseDataInner
   */
  estimatedDaysMax: number | null;
  /**
   *
   * @type {number}
   * @memberof ListShippingOptionsResponseDataInner
   */
  estimatedDaysMin: number | null;
  /**
   *
   * @type {string}
   * @memberof ListShippingOptionsResponseDataInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ListShippingOptionsResponseDataInner
   */
  label: string;
  /**
   *
   * @type {number}
   * @memberof ListShippingOptionsResponseDataInner
   */
  markupCents: number;
  /**
   *
   * @type {string}
   * @memberof ListShippingOptionsResponseDataInner
   */
  serviceLevel: string;
  /**
   *
   * @type {ListShippingOptionsResponseDataInnerTemperatureEnum}
   * @memberof ListShippingOptionsResponseDataInner
   */
  temperature: ListShippingOptionsResponseDataInnerTemperatureEnum;
  /**
   *
   * @type {number}
   * @memberof ListShippingOptionsResponseDataInner
   */
  totalCents: number;
}

/**
 * @export
 */
export const ListShippingOptionsResponseDataInnerCurrencyEnum = {
  Usd: "USD",
} as const;
export type ListShippingOptionsResponseDataInnerCurrencyEnum =
  (typeof ListShippingOptionsResponseDataInnerCurrencyEnum)[keyof typeof ListShippingOptionsResponseDataInnerCurrencyEnum];

/**
 * @export
 */
export const ListShippingOptionsResponseDataInnerTemperatureEnum = {
  Ambient: "ambient",
  Refrigerated: "refrigerated",
} as const;
export type ListShippingOptionsResponseDataInnerTemperatureEnum =
  (typeof ListShippingOptionsResponseDataInnerTemperatureEnum)[keyof typeof ListShippingOptionsResponseDataInnerTemperatureEnum];

/**
 * Check if a given object implements the ListShippingOptionsResponseDataInner interface.
 */
export function instanceOfListShippingOptionsResponseDataInner(
  value: object,
): value is ListShippingOptionsResponseDataInner {
  if (!("amountCents" in value) || value["amountCents"] === undefined) return false;
  if (!("carrier" in value) || value["carrier"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("estimatedDaysMax" in value) || value["estimatedDaysMax"] === undefined) return false;
  if (!("estimatedDaysMin" in value) || value["estimatedDaysMin"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  if (!("markupCents" in value) || value["markupCents"] === undefined) return false;
  if (!("serviceLevel" in value) || value["serviceLevel"] === undefined) return false;
  if (!("temperature" in value) || value["temperature"] === undefined) return false;
  if (!("totalCents" in value) || value["totalCents"] === undefined) return false;
  return true;
}

export function ListShippingOptionsResponseDataInnerFromJSON(
  json: any,
): ListShippingOptionsResponseDataInner {
  return ListShippingOptionsResponseDataInnerFromJSONTyped(json, false);
}

export function ListShippingOptionsResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListShippingOptionsResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    amountCents: json["amountCents"],
    carrier: json["carrier"],
    currency: json["currency"],
    estimatedDaysMax: json["estimatedDaysMax"],
    estimatedDaysMin: json["estimatedDaysMin"],
    id: json["id"],
    label: json["label"],
    markupCents: json["markupCents"],
    serviceLevel: json["serviceLevel"],
    temperature: json["temperature"],
    totalCents: json["totalCents"],
  };
}

export function ListShippingOptionsResponseDataInnerToJSON(
  json: any,
): ListShippingOptionsResponseDataInner {
  return ListShippingOptionsResponseDataInnerToJSONTyped(json, false);
}

export function ListShippingOptionsResponseDataInnerToJSONTyped(
  value?: ListShippingOptionsResponseDataInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amountCents: value["amountCents"],
    carrier: value["carrier"],
    currency: value["currency"],
    estimatedDaysMax: value["estimatedDaysMax"],
    estimatedDaysMin: value["estimatedDaysMin"],
    id: value["id"],
    label: value["label"],
    markupCents: value["markupCents"],
    serviceLevel: value["serviceLevel"],
    temperature: value["temperature"],
    totalCents: value["totalCents"],
  };
}
