/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2
 */
export interface ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 {
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2KindEnum}
   * @memberof ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2
   */
  kind: ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2KindEnum;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2
   */
  reason: string;
}

/**
 * @export
 */
export const ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2KindEnum = {
  Unresolved: "unresolved",
} as const;
export type ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2KindEnum =
  (typeof ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2KindEnum)[keyof typeof ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2KindEnum];

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2(
  value: object,
): value is ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 {
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2FromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 {
  return ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2FromJSONTyped(
    json,
    false,
  );
}

export function ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 {
  if (json == null) {
    return json;
  }
  return {
    kind: json["kind"],
    reason: json["reason"],
  };
}

export function ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2ToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 {
  return ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2ToJSONTyped(
    json,
    false,
  );
}

export function ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2ToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerCompositionIngredientsInnerStrengthOneOf2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    kind: value["kind"],
    reason: value["reason"],
  };
}
