/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListOrdersResponseDataInnerReviewResolvedBy
 */
export interface ListOrdersResponseDataInnerReviewResolvedBy {
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerReviewResolvedBy
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerReviewResolvedBy
   */
  type: string;
}

/**
 * Check if a given object implements the ListOrdersResponseDataInnerReviewResolvedBy interface.
 */
export function instanceOfListOrdersResponseDataInnerReviewResolvedBy(
  value: object,
): value is ListOrdersResponseDataInnerReviewResolvedBy {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function ListOrdersResponseDataInnerReviewResolvedByFromJSON(
  json: any,
): ListOrdersResponseDataInnerReviewResolvedBy {
  return ListOrdersResponseDataInnerReviewResolvedByFromJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerReviewResolvedByFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOrdersResponseDataInnerReviewResolvedBy {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    type: json["type"],
  };
}

export function ListOrdersResponseDataInnerReviewResolvedByToJSON(
  json: any,
): ListOrdersResponseDataInnerReviewResolvedBy {
  return ListOrdersResponseDataInnerReviewResolvedByToJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerReviewResolvedByToJSONTyped(
  value?: ListOrdersResponseDataInnerReviewResolvedBy | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    type: value["type"],
  };
}
