/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerPricingBasisOneOf2
 */
export interface ListCatalogItemsResponseDataInnerPricingBasisOneOf2 {
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPricingBasisOneOf2KindEnum}
   * @memberof ListCatalogItemsResponseDataInnerPricingBasisOneOf2
   */
  kind: ListCatalogItemsResponseDataInnerPricingBasisOneOf2KindEnum;
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPricingBasisOneOf2QuantityEnum}
   * @memberof ListCatalogItemsResponseDataInnerPricingBasisOneOf2
   */
  quantity: ListCatalogItemsResponseDataInnerPricingBasisOneOf2QuantityEnum;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerPricingBasisOneOf2
   */
  unit: string;
}

/**
 * @export
 */
export const ListCatalogItemsResponseDataInnerPricingBasisOneOf2KindEnum = {
  Unit: "unit",
} as const;
export type ListCatalogItemsResponseDataInnerPricingBasisOneOf2KindEnum =
  (typeof ListCatalogItemsResponseDataInnerPricingBasisOneOf2KindEnum)[keyof typeof ListCatalogItemsResponseDataInnerPricingBasisOneOf2KindEnum];

/**
 * @export
 */
export const ListCatalogItemsResponseDataInnerPricingBasisOneOf2QuantityEnum = {
  _1: "1",
} as const;
export type ListCatalogItemsResponseDataInnerPricingBasisOneOf2QuantityEnum =
  (typeof ListCatalogItemsResponseDataInnerPricingBasisOneOf2QuantityEnum)[keyof typeof ListCatalogItemsResponseDataInnerPricingBasisOneOf2QuantityEnum];

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerPricingBasisOneOf2 interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerPricingBasisOneOf2(
  value: object,
): value is ListCatalogItemsResponseDataInnerPricingBasisOneOf2 {
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerPricingBasisOneOf2FromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerPricingBasisOneOf2 {
  return ListCatalogItemsResponseDataInnerPricingBasisOneOf2FromJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerPricingBasisOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerPricingBasisOneOf2 {
  if (json == null) {
    return json;
  }
  return {
    kind: json["kind"],
    quantity: json["quantity"],
    unit: json["unit"],
  };
}

export function ListCatalogItemsResponseDataInnerPricingBasisOneOf2ToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerPricingBasisOneOf2 {
  return ListCatalogItemsResponseDataInnerPricingBasisOneOf2ToJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerPricingBasisOneOf2ToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerPricingBasisOneOf2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    kind: value["kind"],
    quantity: value["quantity"],
    unit: value["unit"],
  };
}
