/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProvider } from "./ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProvider";
import {
  ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProviderFromJSON,
  ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProviderFromJSONTyped,
  ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProviderToJSON,
  ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProviderToJSONTyped,
} from "./ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProvider";

/**
 *
 * @export
 * @interface ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection
 */
export interface ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection {
  /**
   *
   * @type {string}
   * @memberof ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection
   */
  status: string;
  /**
   *
   * @type {ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProvider}
   * @memberof ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection
   */
  provider: ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProvider;
}

/**
 * Check if a given object implements the ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection interface.
 */
export function instanceOfListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection(
  value: object,
): value is ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("provider" in value) || value["provider"] === undefined) return false;
  return true;
}

export function ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionFromJSON(
  json: any,
): ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection {
  return ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionFromJSONTyped(
    json,
    false,
  );
}

export function ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    provider:
      ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProviderFromJSON(
        json["provider"],
      ),
  };
}

export function ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionToJSON(
  json: any,
): ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection {
  return ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionToJSONTyped(
    json,
    false,
  );
}

export function ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionToJSONTyped(
  value?: ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnection | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    provider:
      ListPracticeTeamInvitationsResponseDataInnerPersonAccountPrescriberConnectionProviderToJSON(
        value["provider"],
      ),
  };
}
