/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2
 */
export interface ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 {
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2KindEnum}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2
   */
  kind: ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2KindEnum;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2
   */
  unit: string;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2
   */
  minimum: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2
   */
  maximum: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2
   */
  increment: string | null;
}

/**
 * @export
 */
export const ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2KindEnum = {
  Range: "range",
} as const;
export type ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2KindEnum =
  (typeof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2KindEnum)[keyof typeof ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2KindEnum];

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2(
  value: object,
): value is ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 {
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("minimum" in value) || value["minimum"] === undefined) return false;
  if (!("maximum" in value) || value["maximum"] === undefined) return false;
  if (!("increment" in value) || value["increment"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2FromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 {
  return ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2FromJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 {
  if (json == null) {
    return json;
  }
  return {
    kind: json["kind"],
    unit: json["unit"],
    minimum: json["minimum"],
    maximum: json["maximum"],
    increment: json["increment"],
  };
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2ToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 {
  return ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2ToJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2ToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerQuantityConstraintAnyOf2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    kind: value["kind"],
    unit: value["unit"],
    minimum: value["minimum"],
    maximum: value["maximum"],
    increment: value["increment"],
  };
}
