/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedBy } from "./ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedBy";
import {
  ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedByFromJSON,
  ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedByFromJSONTyped,
  ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedByToJSON,
  ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedByToJSONTyped,
} from "./ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedBy";

/**
 *
 * @export
 * @interface ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
 */
export interface ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner {
  /**
   *
   * @type {number}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  attempts: number;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  confirmedAt: string | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  createdAt: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  errorCode: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  errorMessage: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  providerStatus: string | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  reason: string | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  requestedAt: string | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedBy}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  requestedBy: ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedBy;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  resolvedAt: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  sentAt: string | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerSourceEnum}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  source: ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerSourceEnum;
  /**
   *
   * @type {ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerStatusEnum}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  status: ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerStatusEnum;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner
   */
  updatedAt: string | null;
}

/**
 * @export
 */
export const ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerSourceEnum = {
  Provider: "provider",
  Platform: "platform",
  PublicApi: "public_api",
  Pharmacy: "pharmacy",
  System: "system",
} as const;
export type ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerSourceEnum =
  (typeof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerSourceEnum)[keyof typeof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerSourceEnum];

/**
 * @export
 */
export const ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerStatusEnum = {
  Requested: "requested",
  Sent: "sent",
  Confirmed: "confirmed",
  Rejected: "rejected",
  Failed: "failed",
  TooLate: "too_late",
} as const;
export type ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerStatusEnum =
  (typeof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerStatusEnum)[keyof typeof ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerStatusEnum];

/**
 * Check if a given object implements the ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner interface.
 */
export function instanceOfListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner(
  value: object,
): value is ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner {
  if (!("attempts" in value) || value["attempts"] === undefined) return false;
  if (!("confirmedAt" in value) || value["confirmedAt"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("errorCode" in value) || value["errorCode"] === undefined) return false;
  if (!("errorMessage" in value) || value["errorMessage"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("providerStatus" in value) || value["providerStatus"] === undefined) return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  if (!("requestedAt" in value) || value["requestedAt"] === undefined) return false;
  if (!("requestedBy" in value) || value["requestedBy"] === undefined) return false;
  if (!("resolvedAt" in value) || value["resolvedAt"] === undefined) return false;
  if (!("sentAt" in value) || value["sentAt"] === undefined) return false;
  if (!("source" in value) || value["source"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerFromJSON(
  json: any,
): ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner {
  return ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerFromJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner {
  if (json == null) {
    return json;
  }
  return {
    attempts: json["attempts"],
    confirmedAt: json["confirmedAt"],
    createdAt: json["createdAt"],
    errorCode: json["errorCode"],
    errorMessage: json["errorMessage"],
    id: json["id"],
    providerStatus: json["providerStatus"],
    reason: json["reason"],
    requestedAt: json["requestedAt"],
    requestedBy: ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedByFromJSON(
      json["requestedBy"],
    ),
    resolvedAt: json["resolvedAt"],
    sentAt: json["sentAt"],
    source: json["source"],
    status: json["status"],
    updatedAt: json["updatedAt"],
  };
}

export function ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerToJSON(
  json: any,
): ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner {
  return ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerToJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerToJSONTyped(
  value?: ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    attempts: value["attempts"],
    confirmedAt: value["confirmedAt"],
    createdAt: value["createdAt"],
    errorCode: value["errorCode"],
    errorMessage: value["errorMessage"],
    id: value["id"],
    providerStatus: value["providerStatus"],
    reason: value["reason"],
    requestedAt: value["requestedAt"],
    requestedBy: ListOrdersResponseDataInnerFulfillmentsInnerCancellationsInnerRequestedByToJSON(
      value["requestedBy"],
    ),
    resolvedAt: value["resolvedAt"],
    sentAt: value["sentAt"],
    source: value["source"],
    status: value["status"],
    updatedAt: value["updatedAt"],
  };
}
