/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListPractices200ResponseDataInnerAddress
 */
export interface ListPractices200ResponseDataInnerAddress {
  /**
   *
   * @type {string}
   * @memberof ListPractices200ResponseDataInnerAddress
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof ListPractices200ResponseDataInnerAddress
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof ListPractices200ResponseDataInnerAddress
   */
  line1: string | null;
  /**
   *
   * @type {string}
   * @memberof ListPractices200ResponseDataInnerAddress
   */
  line2?: string | null;
  /**
   *
   * @type {string}
   * @memberof ListPractices200ResponseDataInnerAddress
   */
  postalCode: string;
  /**
   *
   * @type {string}
   * @memberof ListPractices200ResponseDataInnerAddress
   */
  state: string;
}

/**
 * Check if a given object implements the ListPractices200ResponseDataInnerAddress interface.
 */
export function instanceOfListPractices200ResponseDataInnerAddress(
  value: object,
): value is ListPractices200ResponseDataInnerAddress {
  if (!("city" in value) || value["city"] === undefined) return false;
  if (!("line1" in value) || value["line1"] === undefined) return false;
  if (!("postalCode" in value) || value["postalCode"] === undefined) return false;
  if (!("state" in value) || value["state"] === undefined) return false;
  return true;
}

export function ListPractices200ResponseDataInnerAddressFromJSON(
  json: any,
): ListPractices200ResponseDataInnerAddress {
  return ListPractices200ResponseDataInnerAddressFromJSONTyped(json, false);
}

export function ListPractices200ResponseDataInnerAddressFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListPractices200ResponseDataInnerAddress {
  if (json == null) {
    return json;
  }
  return {
    city: json["city"],
    country: json["country"] == null ? undefined : json["country"],
    line1: json["line1"],
    line2: json["line2"] == null ? undefined : json["line2"],
    postalCode: json["postalCode"],
    state: json["state"],
  };
}

export function ListPractices200ResponseDataInnerAddressToJSON(
  json: any,
): ListPractices200ResponseDataInnerAddress {
  return ListPractices200ResponseDataInnerAddressToJSONTyped(json, false);
}

export function ListPractices200ResponseDataInnerAddressToJSONTyped(
  value?: ListPractices200ResponseDataInnerAddress | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    city: value["city"],
    country: value["country"],
    line1: value["line1"],
    line2: value["line2"],
    postalCode: value["postalCode"],
    state: value["state"],
  };
}
