/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantity } from "./ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantity";
import {
  ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantityFromJSON,
  ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantityFromJSONTyped,
  ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantityToJSON,
  ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantityToJSONTyped,
} from "./ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantity";

/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerQuantityConstraintOneOf
 */
export interface ListCatalogItemsResponseDataInnerQuantityConstraintOneOf {
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerQuantityConstraintOneOfKindEnum}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf
   */
  kind: ListCatalogItemsResponseDataInnerQuantityConstraintOneOfKindEnum;
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantity}
   * @memberof ListCatalogItemsResponseDataInnerQuantityConstraintOneOf
   */
  quantity: ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantity;
}

/**
 * @export
 */
export const ListCatalogItemsResponseDataInnerQuantityConstraintOneOfKindEnum = {
  Fixed: "fixed",
} as const;
export type ListCatalogItemsResponseDataInnerQuantityConstraintOneOfKindEnum =
  (typeof ListCatalogItemsResponseDataInnerQuantityConstraintOneOfKindEnum)[keyof typeof ListCatalogItemsResponseDataInnerQuantityConstraintOneOfKindEnum];

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerQuantityConstraintOneOf interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerQuantityConstraintOneOf(
  value: object,
): value is ListCatalogItemsResponseDataInnerQuantityConstraintOneOf {
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOfFromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerQuantityConstraintOneOf {
  return ListCatalogItemsResponseDataInnerQuantityConstraintOneOfFromJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerQuantityConstraintOneOf {
  if (json == null) {
    return json;
  }
  return {
    kind: json["kind"],
    quantity: ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantityFromJSON(
      json["quantity"],
    ),
  };
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOfToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerQuantityConstraintOneOf {
  return ListCatalogItemsResponseDataInnerQuantityConstraintOneOfToJSONTyped(json, false);
}

export function ListCatalogItemsResponseDataInnerQuantityConstraintOneOfToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerQuantityConstraintOneOf | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    kind: value["kind"],
    quantity: ListCatalogItemsResponseDataInnerQuantityConstraintOneOfQuantityToJSON(
      value["quantity"],
    ),
  };
}
