/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValue } from "./ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValue";
import {
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValueFromJSON,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValueFromJSONTyped,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValueToJSON,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValueToJSONTyped,
} from "./ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValue";
import type { ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax } from "./ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax";
import {
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSON,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSONTyped,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSON,
  ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSONTyped,
} from "./ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax";

/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement
 */
export interface ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement {
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement
   */
  max?: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax | null;
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement
   */
  min?: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMax | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement
   */
  unit: string | null;
  /**
   *
   * @type {ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValue}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement
   */
  value: ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValue;
}

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement(
  value: object,
): value is ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement {
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementFromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement {
  return ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementFromJSONTyped(
    json,
    false,
  );
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement {
  if (json == null) {
    return json;
  }
  return {
    max:
      json["max"] == null
        ? undefined
        : ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSON(
            json["max"],
          ),
    min:
      json["min"] == null
        ? undefined
        : ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxFromJSON(
            json["min"],
          ),
    unit: json["unit"],
    value:
      ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValueFromJSON(
        json["value"],
      ),
  };
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement {
  return ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementToJSONTyped(
    json,
    false,
  );
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrement | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    max: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSON(
      value["max"],
    ),
    min: ListCatalogItemsResponseDataInnerPrescriptionRequirementsQuantityIncrementMaxToJSON(
      value["min"],
    ),
    unit: value["unit"],
    value:
      ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerValueToJSON(
        value["value"],
      ),
  };
}
