/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListPractices200ResponseDataInner } from "./ListPractices200ResponseDataInner";
import {
  ListPractices200ResponseDataInnerFromJSON,
  ListPractices200ResponseDataInnerFromJSONTyped,
  ListPractices200ResponseDataInnerToJSON,
  ListPractices200ResponseDataInnerToJSONTyped,
} from "./ListPractices200ResponseDataInner";

/**
 *
 * @export
 * @interface ListPractices200Response
 */
export interface ListPractices200Response {
  /**
   *
   * @type {Array<ListPractices200ResponseDataInner>}
   * @memberof ListPractices200Response
   */
  data: Array<ListPractices200ResponseDataInner>;
  /**
   *
   * @type {boolean}
   * @memberof ListPractices200Response
   */
  hasMore: boolean;
  /**
   *
   * @type {ListPractices200ResponseObjectEnum}
   * @memberof ListPractices200Response
   */
  object: ListPractices200ResponseObjectEnum;
}

/**
 * @export
 */
export const ListPractices200ResponseObjectEnum = {
  List: "list",
} as const;
export type ListPractices200ResponseObjectEnum =
  (typeof ListPractices200ResponseObjectEnum)[keyof typeof ListPractices200ResponseObjectEnum];

/**
 * Check if a given object implements the ListPractices200Response interface.
 */
export function instanceOfListPractices200Response(
  value: object,
): value is ListPractices200Response {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("hasMore" in value) || value["hasMore"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  return true;
}

export function ListPractices200ResponseFromJSON(json: any): ListPractices200Response {
  return ListPractices200ResponseFromJSONTyped(json, false);
}

export function ListPractices200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListPractices200Response {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(ListPractices200ResponseDataInnerFromJSON),
    hasMore: json["hasMore"],
    object: json["object"],
  };
}

export function ListPractices200ResponseToJSON(json: any): ListPractices200Response {
  return ListPractices200ResponseToJSONTyped(json, false);
}

export function ListPractices200ResponseToJSONTyped(
  value?: ListPractices200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(ListPractices200ResponseDataInnerToJSON),
    hasMore: value["hasMore"],
    object: value["object"],
  };
}
