/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListOrdersResponseDataInner } from "./ListOrdersResponseDataInner";
import {
  ListOrdersResponseDataInnerFromJSON,
  ListOrdersResponseDataInnerFromJSONTyped,
  ListOrdersResponseDataInnerToJSON,
  ListOrdersResponseDataInnerToJSONTyped,
} from "./ListOrdersResponseDataInner";

/**
 *
 * @export
 * @interface ListOrdersResponse
 */
export interface ListOrdersResponse {
  /**
   *
   * @type {Array<ListOrdersResponseDataInner>}
   * @memberof ListOrdersResponse
   */
  data: Array<ListOrdersResponseDataInner>;
  /**
   *
   * @type {boolean}
   * @memberof ListOrdersResponse
   */
  hasMore: boolean;
  /**
   *
   * @type {ListOrdersResponseObjectEnum}
   * @memberof ListOrdersResponse
   */
  object: ListOrdersResponseObjectEnum;
  /**
   *
   * @type {ListOrdersResponseUrlEnum}
   * @memberof ListOrdersResponse
   */
  url: ListOrdersResponseUrlEnum;
}

/**
 * @export
 */
export const ListOrdersResponseObjectEnum = {
  List: "list",
} as const;
export type ListOrdersResponseObjectEnum =
  (typeof ListOrdersResponseObjectEnum)[keyof typeof ListOrdersResponseObjectEnum];

/**
 * @export
 */
export const ListOrdersResponseUrlEnum = {
  V1Orders: "/v1/orders",
} as const;
export type ListOrdersResponseUrlEnum =
  (typeof ListOrdersResponseUrlEnum)[keyof typeof ListOrdersResponseUrlEnum];

/**
 * Check if a given object implements the ListOrdersResponse interface.
 */
export function instanceOfListOrdersResponse(value: object): value is ListOrdersResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("hasMore" in value) || value["hasMore"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("url" in value) || value["url"] === undefined) return false;
  return true;
}

export function ListOrdersResponseFromJSON(json: any): ListOrdersResponse {
  return ListOrdersResponseFromJSONTyped(json, false);
}

export function ListOrdersResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOrdersResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(ListOrdersResponseDataInnerFromJSON),
    hasMore: json["hasMore"],
    object: json["object"],
    url: json["url"],
  };
}

export function ListOrdersResponseToJSON(json: any): ListOrdersResponse {
  return ListOrdersResponseToJSONTyped(json, false);
}

export function ListOrdersResponseToJSONTyped(
  value?: ListOrdersResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(ListOrdersResponseDataInnerToJSON),
    hasMore: value["hasMore"],
    object: value["object"],
    url: value["url"],
  };
}
