/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListPharmaciesResponseDataInnerProfileRating } from "./ListPharmaciesResponseDataInnerProfileRating";
import {
  ListPharmaciesResponseDataInnerProfileRatingFromJSON,
  ListPharmaciesResponseDataInnerProfileRatingFromJSONTyped,
  ListPharmaciesResponseDataInnerProfileRatingToJSON,
  ListPharmaciesResponseDataInnerProfileRatingToJSONTyped,
} from "./ListPharmaciesResponseDataInnerProfileRating";

/**
 *
 * @export
 * @interface ListPharmaciesResponseDataInnerProfile
 */
export interface ListPharmaciesResponseDataInnerProfile {
  /**
   *
   * @type {string}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  effectiveAt: string;
  /**
   *
   * @type {number}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  monthlyPrescriptionVolume: number | null;
  /**
   *
   * @type {ListPharmaciesResponseDataInnerProfileRating}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  rating: ListPharmaciesResponseDataInnerProfileRating | null;
  /**
   *
   * @type {string}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  ratingBasis: string | null;
  /**
   *
   * @type {number}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  ratingReviewCount: number | null;
  /**
   *
   * @type {number}
   * @memberof ListPharmaciesResponseDataInnerProfile
   */
  recommendedRank: number | null;
}

/**
 * Check if a given object implements the ListPharmaciesResponseDataInnerProfile interface.
 */
export function instanceOfListPharmaciesResponseDataInnerProfile(
  value: object,
): value is ListPharmaciesResponseDataInnerProfile {
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("effectiveAt" in value) || value["effectiveAt"] === undefined) return false;
  if (!("monthlyPrescriptionVolume" in value) || value["monthlyPrescriptionVolume"] === undefined)
    return false;
  if (!("rating" in value) || value["rating"] === undefined) return false;
  if (!("ratingBasis" in value) || value["ratingBasis"] === undefined) return false;
  if (!("ratingReviewCount" in value) || value["ratingReviewCount"] === undefined) return false;
  if (!("recommendedRank" in value) || value["recommendedRank"] === undefined) return false;
  return true;
}

export function ListPharmaciesResponseDataInnerProfileFromJSON(
  json: any,
): ListPharmaciesResponseDataInnerProfile {
  return ListPharmaciesResponseDataInnerProfileFromJSONTyped(json, false);
}

export function ListPharmaciesResponseDataInnerProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListPharmaciesResponseDataInnerProfile {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"],
    effectiveAt: json["effectiveAt"],
    monthlyPrescriptionVolume: json["monthlyPrescriptionVolume"],
    rating: ListPharmaciesResponseDataInnerProfileRatingFromJSON(json["rating"]),
    ratingBasis: json["ratingBasis"],
    ratingReviewCount: json["ratingReviewCount"],
    recommendedRank: json["recommendedRank"],
  };
}

export function ListPharmaciesResponseDataInnerProfileToJSON(
  json: any,
): ListPharmaciesResponseDataInnerProfile {
  return ListPharmaciesResponseDataInnerProfileToJSONTyped(json, false);
}

export function ListPharmaciesResponseDataInnerProfileToJSONTyped(
  value?: ListPharmaciesResponseDataInnerProfile | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    description: value["description"],
    effectiveAt: value["effectiveAt"],
    monthlyPrescriptionVolume: value["monthlyPrescriptionVolume"],
    rating: ListPharmaciesResponseDataInnerProfileRatingToJSON(value["rating"]),
    ratingBasis: value["ratingBasis"],
    ratingReviewCount: value["ratingReviewCount"],
    recommendedRank: value["recommendedRank"],
  };
}
