/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-28
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListOrdersResponseDataInnerShipping } from "./ListOrdersResponseDataInnerShipping";
import {
  ListOrdersResponseDataInnerShippingFromJSON,
  ListOrdersResponseDataInnerShippingFromJSONTyped,
  ListOrdersResponseDataInnerShippingToJSON,
  ListOrdersResponseDataInnerShippingToJSONTyped,
} from "./ListOrdersResponseDataInnerShipping";
import type { ListOrdersResponseDataInnerRouting } from "./ListOrdersResponseDataInnerRouting";
import {
  ListOrdersResponseDataInnerRoutingFromJSON,
  ListOrdersResponseDataInnerRoutingFromJSONTyped,
  ListOrdersResponseDataInnerRoutingToJSON,
  ListOrdersResponseDataInnerRoutingToJSONTyped,
} from "./ListOrdersResponseDataInnerRouting";

/**
 *
 * @export
 * @interface ListOrdersResponseDataInner
 */
export interface ListOrdersResponseDataInner {
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  cancellationReason: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  carrier: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  catalogItemId: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  practiceId: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  compounderId: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  currency: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  directions: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  dosageForm: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  externalOrderId: string;
  /**
   *
   * @type {boolean}
   * @memberof ListOrdersResponseDataInner
   */
  externalSubmissionAttempted: boolean;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  externalSubmissionBlockedReason: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof ListOrdersResponseDataInner
   */
  livemode: boolean;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  medicationName: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  patientExternalId: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  patientName: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  patientState: string;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  prescriberName: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  prescriberNpi: string | null;
  /**
   *
   * @type {number}
   * @memberof ListOrdersResponseDataInner
   */
  quantity: number;
  /**
   *
   * @type {number}
   * @memberof ListOrdersResponseDataInner
   */
  quoteCents: number | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerObjectEnum}
   * @memberof ListOrdersResponseDataInner
   */
  object: ListOrdersResponseDataInnerObjectEnum;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  replacesOrderId: string | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerRouting}
   * @memberof ListOrdersResponseDataInner
   */
  routing: ListOrdersResponseDataInnerRouting | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerStatusEnum}
   * @memberof ListOrdersResponseDataInner
   */
  status: ListOrdersResponseDataInnerStatusEnum;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  strength: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  trackingNumber: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  shippedAt: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  deliveredAt: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  estimatedDeliveryAt: string | null;
  /**
   *
   * @type {ListOrdersResponseDataInnerShipping}
   * @memberof ListOrdersResponseDataInner
   */
  shipping: ListOrdersResponseDataInnerShipping;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  trackingUrl: string | null;
  /**
   *
   * @type {string}
   * @memberof ListOrdersResponseDataInner
   */
  updatedAt: string;
}

/**
 * @export
 */
export const ListOrdersResponseDataInnerObjectEnum = {
  Order: "order",
} as const;
export type ListOrdersResponseDataInnerObjectEnum =
  (typeof ListOrdersResponseDataInnerObjectEnum)[keyof typeof ListOrdersResponseDataInnerObjectEnum];

/**
 * @export
 */
export const ListOrdersResponseDataInnerStatusEnum = {
  Blocked: "blocked",
  Cancelled: "cancelled",
  Delivered: "delivered",
  Draft: "draft",
  Processing: "processing",
  Shipped: "shipped",
  Submitted: "submitted",
} as const;
export type ListOrdersResponseDataInnerStatusEnum =
  (typeof ListOrdersResponseDataInnerStatusEnum)[keyof typeof ListOrdersResponseDataInnerStatusEnum];

/**
 * Check if a given object implements the ListOrdersResponseDataInner interface.
 */
export function instanceOfListOrdersResponseDataInner(
  value: object,
): value is ListOrdersResponseDataInner {
  if (!("cancellationReason" in value) || value["cancellationReason"] === undefined) return false;
  if (!("carrier" in value) || value["carrier"] === undefined) return false;
  if (!("catalogItemId" in value) || value["catalogItemId"] === undefined) return false;
  if (!("practiceId" in value) || value["practiceId"] === undefined) return false;
  if (!("compounderId" in value) || value["compounderId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("directions" in value) || value["directions"] === undefined) return false;
  if (!("dosageForm" in value) || value["dosageForm"] === undefined) return false;
  if (!("externalOrderId" in value) || value["externalOrderId"] === undefined) return false;
  if (
    !("externalSubmissionAttempted" in value) ||
    value["externalSubmissionAttempted"] === undefined
  )
    return false;
  if (
    !("externalSubmissionBlockedReason" in value) ||
    value["externalSubmissionBlockedReason"] === undefined
  )
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("livemode" in value) || value["livemode"] === undefined) return false;
  if (!("medicationName" in value) || value["medicationName"] === undefined) return false;
  if (!("patientExternalId" in value) || value["patientExternalId"] === undefined) return false;
  if (!("patientName" in value) || value["patientName"] === undefined) return false;
  if (!("patientState" in value) || value["patientState"] === undefined) return false;
  if (!("prescriberName" in value) || value["prescriberName"] === undefined) return false;
  if (!("prescriberNpi" in value) || value["prescriberNpi"] === undefined) return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  if (!("quoteCents" in value) || value["quoteCents"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("replacesOrderId" in value) || value["replacesOrderId"] === undefined) return false;
  if (!("routing" in value) || value["routing"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("strength" in value) || value["strength"] === undefined) return false;
  if (!("trackingNumber" in value) || value["trackingNumber"] === undefined) return false;
  if (!("shippedAt" in value) || value["shippedAt"] === undefined) return false;
  if (!("deliveredAt" in value) || value["deliveredAt"] === undefined) return false;
  if (!("estimatedDeliveryAt" in value) || value["estimatedDeliveryAt"] === undefined) return false;
  if (!("shipping" in value) || value["shipping"] === undefined) return false;
  if (!("trackingUrl" in value) || value["trackingUrl"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function ListOrdersResponseDataInnerFromJSON(json: any): ListOrdersResponseDataInner {
  return ListOrdersResponseDataInnerFromJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListOrdersResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    cancellationReason: json["cancellationReason"],
    carrier: json["carrier"],
    catalogItemId: json["catalogItemId"],
    practiceId: json["practiceId"],
    compounderId: json["compounderId"],
    createdAt: json["createdAt"],
    currency: json["currency"],
    directions: json["directions"],
    dosageForm: json["dosageForm"],
    externalOrderId: json["externalOrderId"],
    externalSubmissionAttempted: json["externalSubmissionAttempted"],
    externalSubmissionBlockedReason: json["externalSubmissionBlockedReason"],
    id: json["id"],
    livemode: json["livemode"],
    medicationName: json["medicationName"],
    patientExternalId: json["patientExternalId"],
    patientName: json["patientName"],
    patientState: json["patientState"],
    prescriberName: json["prescriberName"],
    prescriberNpi: json["prescriberNpi"],
    quantity: json["quantity"],
    quoteCents: json["quoteCents"],
    object: json["object"],
    replacesOrderId: json["replacesOrderId"],
    routing: ListOrdersResponseDataInnerRoutingFromJSON(json["routing"]),
    status: json["status"],
    strength: json["strength"],
    trackingNumber: json["trackingNumber"],
    shippedAt: json["shippedAt"],
    deliveredAt: json["deliveredAt"],
    estimatedDeliveryAt: json["estimatedDeliveryAt"],
    shipping: ListOrdersResponseDataInnerShippingFromJSON(json["shipping"]),
    trackingUrl: json["trackingUrl"],
    updatedAt: json["updatedAt"],
  };
}

export function ListOrdersResponseDataInnerToJSON(json: any): ListOrdersResponseDataInner {
  return ListOrdersResponseDataInnerToJSONTyped(json, false);
}

export function ListOrdersResponseDataInnerToJSONTyped(
  value?: ListOrdersResponseDataInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    cancellationReason: value["cancellationReason"],
    carrier: value["carrier"],
    catalogItemId: value["catalogItemId"],
    practiceId: value["practiceId"],
    compounderId: value["compounderId"],
    createdAt: value["createdAt"],
    currency: value["currency"],
    directions: value["directions"],
    dosageForm: value["dosageForm"],
    externalOrderId: value["externalOrderId"],
    externalSubmissionAttempted: value["externalSubmissionAttempted"],
    externalSubmissionBlockedReason: value["externalSubmissionBlockedReason"],
    id: value["id"],
    livemode: value["livemode"],
    medicationName: value["medicationName"],
    patientExternalId: value["patientExternalId"],
    patientName: value["patientName"],
    patientState: value["patientState"],
    prescriberName: value["prescriberName"],
    prescriberNpi: value["prescriberNpi"],
    quantity: value["quantity"],
    quoteCents: value["quoteCents"],
    object: value["object"],
    replacesOrderId: value["replacesOrderId"],
    routing: ListOrdersResponseDataInnerRoutingToJSON(value["routing"]),
    status: value["status"],
    strength: value["strength"],
    trackingNumber: value["trackingNumber"],
    shippedAt: value["shippedAt"],
    deliveredAt: value["deliveredAt"],
    estimatedDeliveryAt: value["estimatedDeliveryAt"],
    shipping: ListOrdersResponseDataInnerShippingToJSON(value["shipping"]),
    trackingUrl: value["trackingUrl"],
    updatedAt: value["updatedAt"],
  };
}
