/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-08-10
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner
 */
export interface ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner {
  /**
   *
   * @type {number}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner
   */
  daysSupply?: number | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner
   */
  unit: string;
  /**
   *
   * @type {number}
   * @memberof ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner
   */
  value: number | null;
}

/**
 * Check if a given object implements the ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner interface.
 */
export function instanceOfListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner(
  value: object,
): value is ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner {
  if (!("label" in value) || value["label"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerFromJSON(
  json: any,
): ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner {
  return ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerFromJSONTyped(
    json,
    false,
  );
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner {
  if (json == null) {
    return json;
  }
  return {
    daysSupply: json["daysSupply"] == null ? undefined : json["daysSupply"],
    label: json["label"],
    unit: json["unit"],
    value: json["value"],
  };
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerToJSON(
  json: any,
): ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner {
  return ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerToJSONTyped(
    json,
    false,
  );
}

export function ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInnerToJSONTyped(
  value?: ListCatalogItemsResponseDataInnerPrescriptionRequirementsAllowedQuantitiesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    daysSupply: value["daysSupply"],
    label: value["label"],
    unit: value["unit"],
    value: value["value"],
  };
}
