/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListWebhookGrantsResponseDataInner
 */
export interface ListWebhookGrantsResponseDataInner {
  /**
   * Platform account ID; use as the pagination cursor within this owner's grants.
   * @type {string}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  id: string;
  /**
   *
   * @type {ListWebhookGrantsResponseDataInnerObjectEnum}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  object: ListWebhookGrantsResponseDataInnerObjectEnum;
  /**
   *
   * @type {string}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  organizationId: string;
  /**
   *
   * @type {string}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  platformId: string;
  /**
   *
   * @type {boolean}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  livemode: boolean;
  /**
   *
   * @type {Array<ListWebhookGrantsResponseDataInnerScopesEnum>}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  scopes: Array<ListWebhookGrantsResponseDataInnerScopesEnum>;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  createdAt: string | null;
  /**
   * Match this integration's external identity in the API key's mode.
   * @type {string}
   * @memberof ListWebhookGrantsResponseDataInner
   */
  updatedAt: string | null;
}

/**
 * @export
 */
export const ListWebhookGrantsResponseDataInnerObjectEnum = {
  WebhookGrant: "webhook_grant",
} as const;
export type ListWebhookGrantsResponseDataInnerObjectEnum =
  (typeof ListWebhookGrantsResponseDataInnerObjectEnum)[keyof typeof ListWebhookGrantsResponseDataInnerObjectEnum];

/**
 * @export
 */
export const ListWebhookGrantsResponseDataInnerScopesEnum = {
  WebhooksRead: "webhooks:read",
  WebhooksWrite: "webhooks:write",
} as const;
export type ListWebhookGrantsResponseDataInnerScopesEnum =
  (typeof ListWebhookGrantsResponseDataInnerScopesEnum)[keyof typeof ListWebhookGrantsResponseDataInnerScopesEnum];

/**
 * Check if a given object implements the ListWebhookGrantsResponseDataInner interface.
 */
export function instanceOfListWebhookGrantsResponseDataInner(
  value: object,
): value is ListWebhookGrantsResponseDataInner {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined) return false;
  if (!("platformId" in value) || value["platformId"] === undefined) return false;
  if (!("livemode" in value) || value["livemode"] === undefined) return false;
  if (!("scopes" in value) || value["scopes"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function ListWebhookGrantsResponseDataInnerFromJSON(
  json: any,
): ListWebhookGrantsResponseDataInner {
  return ListWebhookGrantsResponseDataInnerFromJSONTyped(json, false);
}

export function ListWebhookGrantsResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListWebhookGrantsResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    object: json["object"],
    organizationId: json["organizationId"],
    platformId: json["platformId"],
    livemode: json["livemode"],
    scopes: json["scopes"],
    createdAt: json["createdAt"],
    updatedAt: json["updatedAt"],
  };
}

export function ListWebhookGrantsResponseDataInnerToJSON(
  json: any,
): ListWebhookGrantsResponseDataInner {
  return ListWebhookGrantsResponseDataInnerToJSONTyped(json, false);
}

export function ListWebhookGrantsResponseDataInnerToJSONTyped(
  value?: ListWebhookGrantsResponseDataInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    object: value["object"],
    organizationId: value["organizationId"],
    platformId: value["platformId"],
    livemode: value["livemode"],
    scopes: value["scopes"],
    createdAt: value["createdAt"],
    updatedAt: value["updatedAt"],
  };
}
