/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-09
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ListCatalogItems200ResponseItemsInner
 */
export interface ListCatalogItems200ResponseItemsInner {
  /**
   *
   * @type {Array<string>}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  allowedStates: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  catalogKind: string | null;
  /**
   *
   * @type {boolean}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  coldShip: boolean;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  compounderId: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  compounderName: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  description: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  dosageForm: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  facilityType: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  id: string | null;
  /**
   *
   * @type {boolean}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  isOrderable: boolean;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  name: string | null;
  /**
   *
   * @type {boolean}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  patientSpecificRequired: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  restrictedStates: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  route: string | null;
  /**
   *
   * @type {string}
   * @memberof ListCatalogItems200ResponseItemsInner
   */
  strength: string | null;
}

/**
 * Check if a given object implements the ListCatalogItems200ResponseItemsInner interface.
 */
export function instanceOfListCatalogItems200ResponseItemsInner(
  value: object,
): value is ListCatalogItems200ResponseItemsInner {
  if (!("allowedStates" in value) || value["allowedStates"] === undefined) return false;
  if (!("catalogKind" in value) || value["catalogKind"] === undefined) return false;
  if (!("coldShip" in value) || value["coldShip"] === undefined) return false;
  if (!("compounderId" in value) || value["compounderId"] === undefined) return false;
  if (!("compounderName" in value) || value["compounderName"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("dosageForm" in value) || value["dosageForm"] === undefined) return false;
  if (!("facilityType" in value) || value["facilityType"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("isOrderable" in value) || value["isOrderable"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("patientSpecificRequired" in value) || value["patientSpecificRequired"] === undefined)
    return false;
  if (!("restrictedStates" in value) || value["restrictedStates"] === undefined) return false;
  if (!("route" in value) || value["route"] === undefined) return false;
  if (!("strength" in value) || value["strength"] === undefined) return false;
  return true;
}

export function ListCatalogItems200ResponseItemsInnerFromJSON(
  json: any,
): ListCatalogItems200ResponseItemsInner {
  return ListCatalogItems200ResponseItemsInnerFromJSONTyped(json, false);
}

export function ListCatalogItems200ResponseItemsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCatalogItems200ResponseItemsInner {
  if (json == null) {
    return json;
  }
  return {
    allowedStates: json["allowedStates"],
    catalogKind: json["catalogKind"],
    coldShip: json["coldShip"],
    compounderId: json["compounderId"],
    compounderName: json["compounderName"],
    description: json["description"],
    dosageForm: json["dosageForm"],
    facilityType: json["facilityType"],
    id: json["id"],
    isOrderable: json["isOrderable"],
    name: json["name"],
    patientSpecificRequired: json["patientSpecificRequired"],
    restrictedStates: json["restrictedStates"],
    route: json["route"],
    strength: json["strength"],
  };
}

export function ListCatalogItems200ResponseItemsInnerToJSON(
  json: any,
): ListCatalogItems200ResponseItemsInner {
  return ListCatalogItems200ResponseItemsInnerToJSONTyped(json, false);
}

export function ListCatalogItems200ResponseItemsInnerToJSONTyped(
  value?: ListCatalogItems200ResponseItemsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    allowedStates: value["allowedStates"],
    catalogKind: value["catalogKind"],
    coldShip: value["coldShip"],
    compounderId: value["compounderId"],
    compounderName: value["compounderName"],
    description: value["description"],
    dosageForm: value["dosageForm"],
    facilityType: value["facilityType"],
    id: value["id"],
    isOrderable: value["isOrderable"],
    name: value["name"],
    patientSpecificRequired: value["patientSpecificRequired"],
    restrictedStates: value["restrictedStates"],
    route: value["route"],
    strength: value["strength"],
  };
}
