/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlatformPublicApiSellingPricesUpdateSellingPriceRequest
 */
export interface PlatformPublicApiSellingPricesUpdateSellingPriceRequest {
  /**
   *
   * @type {string}
   * @memberof PlatformPublicApiSellingPricesUpdateSellingPriceRequest
   */
  practiceId?: string | null;
  /**
   *
   * @type {number}
   * @memberof PlatformPublicApiSellingPricesUpdateSellingPriceRequest
   */
  amountCents: number | null;
  /**
   *
   * @type {number}
   * @memberof PlatformPublicApiSellingPricesUpdateSellingPriceRequest
   */
  baseVersion: number;
}

/**
 * Check if a given object implements the PlatformPublicApiSellingPricesUpdateSellingPriceRequest interface.
 */
export function instanceOfPlatformPublicApiSellingPricesUpdateSellingPriceRequest(
  value: object,
): value is PlatformPublicApiSellingPricesUpdateSellingPriceRequest {
  if (!("amountCents" in value) || value["amountCents"] === undefined) return false;
  if (!("baseVersion" in value) || value["baseVersion"] === undefined) return false;
  return true;
}

export function PlatformPublicApiSellingPricesUpdateSellingPriceRequestFromJSON(
  json: any,
): PlatformPublicApiSellingPricesUpdateSellingPriceRequest {
  return PlatformPublicApiSellingPricesUpdateSellingPriceRequestFromJSONTyped(json, false);
}

export function PlatformPublicApiSellingPricesUpdateSellingPriceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlatformPublicApiSellingPricesUpdateSellingPriceRequest {
  if (json == null) {
    return json;
  }
  return {
    practiceId: json["practiceId"] == null ? undefined : json["practiceId"],
    amountCents: json["amountCents"],
    baseVersion: json["baseVersion"],
  };
}

export function PlatformPublicApiSellingPricesUpdateSellingPriceRequestToJSON(
  json: any,
): PlatformPublicApiSellingPricesUpdateSellingPriceRequest {
  return PlatformPublicApiSellingPricesUpdateSellingPriceRequestToJSONTyped(json, false);
}

export function PlatformPublicApiSellingPricesUpdateSellingPriceRequestToJSONTyped(
  value?: PlatformPublicApiSellingPricesUpdateSellingPriceRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    practiceId: value["practiceId"],
    amountCents: value["amountCents"],
    baseVersion: value["baseVersion"],
  };
}
