/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
 */
export interface PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields {
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  dose: string;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  doseUnit: string;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  frequency: string;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  route: string;
  /**
   *
   * @type {boolean}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  prn?: boolean | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  duration?: string | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  indication?: string | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  maxDailyUse?: string | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields
   */
  titrationSchedule?: string | null;
}

/**
 * Check if a given object implements the PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields interface.
 */
export function instanceOfPreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields(
  value: object,
): value is PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields {
  if (!("dose" in value) || value["dose"] === undefined) return false;
  if (!("doseUnit" in value) || value["doseUnit"] === undefined) return false;
  if (!("frequency" in value) || value["frequency"] === undefined) return false;
  if (!("route" in value) || value["route"] === undefined) return false;
  return true;
}

export function PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFieldsFromJSON(
  json: any,
): PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields {
  return PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFieldsFromJSONTyped(json, false);
}

export function PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFieldsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields {
  if (json == null) {
    return json;
  }
  return {
    dose: json["dose"],
    doseUnit: json["doseUnit"],
    frequency: json["frequency"],
    route: json["route"],
    prn: json["prn"] == null ? undefined : json["prn"],
    duration: json["duration"] == null ? undefined : json["duration"],
    indication: json["indication"] == null ? undefined : json["indication"],
    maxDailyUse: json["maxDailyUse"] == null ? undefined : json["maxDailyUse"],
    titrationSchedule: json["titrationSchedule"] == null ? undefined : json["titrationSchedule"],
  };
}

export function PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFieldsToJSON(
  json: any,
): PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields {
  return PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFieldsToJSONTyped(json, false);
}

export function PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFieldsToJSONTyped(
  value?: PreviewOrderRequestPrescriptionsInnerOverridesSigOneOfFields | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    dose: value["dose"],
    doseUnit: value["doseUnit"],
    frequency: value["frequency"],
    route: value["route"],
    prn: value["prn"],
    duration: value["duration"],
    indication: value["indication"],
    maxDailyUse: value["maxDailyUse"],
    titrationSchedule: value["titrationSchedule"],
  };
}
