/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PreviewOrderRequestPrescriptionsInnerOverrides } from "./PreviewOrderRequestPrescriptionsInnerOverrides";
import {
  PreviewOrderRequestPrescriptionsInnerOverridesFromJSON,
  PreviewOrderRequestPrescriptionsInnerOverridesFromJSONTyped,
  PreviewOrderRequestPrescriptionsInnerOverridesToJSON,
  PreviewOrderRequestPrescriptionsInnerOverridesToJSONTyped,
} from "./PreviewOrderRequestPrescriptionsInnerOverrides";

/**
 *
 * @export
 * @interface PreviewOrderRequestPrescriptionsInner
 */
export interface PreviewOrderRequestPrescriptionsInner {
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInner
   */
  medicationId: string;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInner
   */
  externalPrescriptionId?: string | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInner
   */
  preset?: string | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderRequestPrescriptionsInner
   */
  expectedRevision?: string | null;
  /**
   *
   * @type {PreviewOrderRequestPrescriptionsInnerOverrides}
   * @memberof PreviewOrderRequestPrescriptionsInner
   */
  overrides?: PreviewOrderRequestPrescriptionsInnerOverrides | null;
}

/**
 * Check if a given object implements the PreviewOrderRequestPrescriptionsInner interface.
 */
export function instanceOfPreviewOrderRequestPrescriptionsInner(
  value: object,
): value is PreviewOrderRequestPrescriptionsInner {
  if (!("medicationId" in value) || value["medicationId"] === undefined) return false;
  return true;
}

export function PreviewOrderRequestPrescriptionsInnerFromJSON(
  json: any,
): PreviewOrderRequestPrescriptionsInner {
  return PreviewOrderRequestPrescriptionsInnerFromJSONTyped(json, false);
}

export function PreviewOrderRequestPrescriptionsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreviewOrderRequestPrescriptionsInner {
  if (json == null) {
    return json;
  }
  return {
    medicationId: json["medicationId"],
    externalPrescriptionId:
      json["externalPrescriptionId"] == null ? undefined : json["externalPrescriptionId"],
    preset: json["preset"] == null ? undefined : json["preset"],
    expectedRevision: json["expectedRevision"] == null ? undefined : json["expectedRevision"],
    overrides:
      json["overrides"] == null
        ? undefined
        : PreviewOrderRequestPrescriptionsInnerOverridesFromJSON(json["overrides"]),
  };
}

export function PreviewOrderRequestPrescriptionsInnerToJSON(
  json: any,
): PreviewOrderRequestPrescriptionsInner {
  return PreviewOrderRequestPrescriptionsInnerToJSONTyped(json, false);
}

export function PreviewOrderRequestPrescriptionsInnerToJSONTyped(
  value?: PreviewOrderRequestPrescriptionsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    medicationId: value["medicationId"],
    externalPrescriptionId: value["externalPrescriptionId"],
    preset: value["preset"],
    expectedRevision: value["expectedRevision"],
    overrides: PreviewOrderRequestPrescriptionsInnerOverridesToJSON(value["overrides"]),
  };
}
