/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrderRequestPrescriptionsInnerStructuredSig } from "./CreateOrderRequestPrescriptionsInnerStructuredSig";
import {
  CreateOrderRequestPrescriptionsInnerStructuredSigFromJSON,
  CreateOrderRequestPrescriptionsInnerStructuredSigFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerStructuredSigToJSON,
  CreateOrderRequestPrescriptionsInnerStructuredSigToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInnerStructuredSig";
import type { CreateOrderRequestPrescriptionsInnerDispensing } from "./CreateOrderRequestPrescriptionsInnerDispensing";
import {
  CreateOrderRequestPrescriptionsInnerDispensingFromJSON,
  CreateOrderRequestPrescriptionsInnerDispensingFromJSONTyped,
  CreateOrderRequestPrescriptionsInnerDispensingToJSON,
  CreateOrderRequestPrescriptionsInnerDispensingToJSONTyped,
} from "./CreateOrderRequestPrescriptionsInnerDispensing";
import type { PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinical } from "./PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinical";
import {
  PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinicalFromJSON,
  PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinicalFromJSONTyped,
  PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinicalToJSON,
  PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinicalToJSONTyped,
} from "./PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinical";

/**
 *
 * @export
 * @interface PreviewOrderResponseOneOfOrderInputPrescriptionsInner
 */
export interface PreviewOrderResponseOneOfOrderInputPrescriptionsInner {
  /**
   *
   * @type {string}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  externalPrescriptionId?: string | null;
  /**
   *
   * @type {PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinical}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  clinical?: PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinical | null;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  pharmacyId?: string | null;
  /**
   *
   * @type {number}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  daysSupply: number;
  /**
   *
   * @type {CreateOrderRequestPrescriptionsInnerDispensing}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  dispensing: CreateOrderRequestPrescriptionsInnerDispensing;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  directions: string;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  medicationId: string;
  /**
   *
   * @type {number}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  quantity: number;
  /**
   *
   * @type {string}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  quantityUnit: string;
  /**
   *
   * @type {number}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  refills: number;
  /**
   *
   * @type {CreateOrderRequestPrescriptionsInnerStructuredSig}
   * @memberof PreviewOrderResponseOneOfOrderInputPrescriptionsInner
   */
  structuredSig?: CreateOrderRequestPrescriptionsInnerStructuredSig | null;
}

/**
 * Check if a given object implements the PreviewOrderResponseOneOfOrderInputPrescriptionsInner interface.
 */
export function instanceOfPreviewOrderResponseOneOfOrderInputPrescriptionsInner(
  value: object,
): value is PreviewOrderResponseOneOfOrderInputPrescriptionsInner {
  if (!("daysSupply" in value) || value["daysSupply"] === undefined) return false;
  if (!("dispensing" in value) || value["dispensing"] === undefined) return false;
  if (!("directions" in value) || value["directions"] === undefined) return false;
  if (!("medicationId" in value) || value["medicationId"] === undefined) return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  if (!("quantityUnit" in value) || value["quantityUnit"] === undefined) return false;
  if (!("refills" in value) || value["refills"] === undefined) return false;
  return true;
}

export function PreviewOrderResponseOneOfOrderInputPrescriptionsInnerFromJSON(
  json: any,
): PreviewOrderResponseOneOfOrderInputPrescriptionsInner {
  return PreviewOrderResponseOneOfOrderInputPrescriptionsInnerFromJSONTyped(json, false);
}

export function PreviewOrderResponseOneOfOrderInputPrescriptionsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreviewOrderResponseOneOfOrderInputPrescriptionsInner {
  if (json == null) {
    return json;
  }
  return {
    externalPrescriptionId:
      json["externalPrescriptionId"] == null ? undefined : json["externalPrescriptionId"],
    clinical:
      json["clinical"] == null
        ? undefined
        : PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinicalFromJSON(json["clinical"]),
    pharmacyId: json["pharmacyId"] == null ? undefined : json["pharmacyId"],
    daysSupply: json["daysSupply"],
    dispensing: CreateOrderRequestPrescriptionsInnerDispensingFromJSON(json["dispensing"]),
    directions: json["directions"],
    medicationId: json["medicationId"],
    quantity: json["quantity"],
    quantityUnit: json["quantityUnit"],
    refills: json["refills"],
    structuredSig:
      json["structuredSig"] == null
        ? undefined
        : CreateOrderRequestPrescriptionsInnerStructuredSigFromJSON(json["structuredSig"]),
  };
}

export function PreviewOrderResponseOneOfOrderInputPrescriptionsInnerToJSON(
  json: any,
): PreviewOrderResponseOneOfOrderInputPrescriptionsInner {
  return PreviewOrderResponseOneOfOrderInputPrescriptionsInnerToJSONTyped(json, false);
}

export function PreviewOrderResponseOneOfOrderInputPrescriptionsInnerToJSONTyped(
  value?: PreviewOrderResponseOneOfOrderInputPrescriptionsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    externalPrescriptionId: value["externalPrescriptionId"],
    clinical: PreviewOrderResponseOneOfOrderInputPrescriptionsInnerClinicalToJSON(
      value["clinical"],
    ),
    pharmacyId: value["pharmacyId"],
    daysSupply: value["daysSupply"],
    dispensing: CreateOrderRequestPrescriptionsInnerDispensingToJSON(value["dispensing"]),
    directions: value["directions"],
    medicationId: value["medicationId"],
    quantity: value["quantity"],
    quantityUnit: value["quantityUnit"],
    refills: value["refills"],
    structuredSig: CreateOrderRequestPrescriptionsInnerStructuredSigToJSON(value["structuredSig"]),
  };
}
