/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RegisterUserRequestLicensesInner } from "./RegisterUserRequestLicensesInner";
import {
  RegisterUserRequestLicensesInnerFromJSON,
  RegisterUserRequestLicensesInnerFromJSONTyped,
  RegisterUserRequestLicensesInnerToJSON,
  RegisterUserRequestLicensesInnerToJSONTyped,
} from "./RegisterUserRequestLicensesInner";
import type { RegisterUserRequestProfileDetails } from "./RegisterUserRequestProfileDetails";
import {
  RegisterUserRequestProfileDetailsFromJSON,
  RegisterUserRequestProfileDetailsFromJSONTyped,
  RegisterUserRequestProfileDetailsToJSON,
  RegisterUserRequestProfileDetailsToJSONTyped,
} from "./RegisterUserRequestProfileDetails";
import type { RegisterUserRequestAddress } from "./RegisterUserRequestAddress";
import {
  RegisterUserRequestAddressFromJSON,
  RegisterUserRequestAddressFromJSONTyped,
  RegisterUserRequestAddressToJSON,
  RegisterUserRequestAddressToJSONTyped,
} from "./RegisterUserRequestAddress";

/**
 *
 * @export
 * @interface RegisterUserRequest
 */
export interface RegisterUserRequest {
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  externalId: string;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  name: string;
  /**
   *
   * @type {RegisterUserRequestRoleEnum}
   * @memberof RegisterUserRequest
   */
  role: RegisterUserRequestRoleEnum;
  /**
   *
   * @type {Array<RegisterUserRequestRolesEnum>}
   * @memberof RegisterUserRequest
   */
  roles?: Array<RegisterUserRequestRolesEnum> | null;
  /**
   *
   * @type {RegisterUserRequestProfileDetails}
   * @memberof RegisterUserRequest
   */
  profileDetails?: RegisterUserRequestProfileDetails | null;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  npi?: string | null;
  /**
   *
   * @type {Array<RegisterUserRequestLicensesInner>}
   * @memberof RegisterUserRequest
   */
  licenses?: Array<RegisterUserRequestLicensesInner> | null;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  legalName?: string | null;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  displayName?: string | null;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  credentials?: string | null;
  /**
   *
   * @type {RegisterUserRequestAddress}
   * @memberof RegisterUserRequest
   */
  address?: RegisterUserRequestAddress | null;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequest
   */
  phone?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof RegisterUserRequest
   */
  locationIds?: Array<string> | null;
  /**
   *
   * @type {boolean}
   * @memberof RegisterUserRequest
   */
  identityAttestation: boolean;
}

/**
 * @export
 */
export const RegisterUserRequestRoleEnum = {
  Administrator: "administrator",
  Prescriber: "prescriber",
  ClinicalStaff: "clinical_staff",
  Billing: "billing",
  Developer: "developer",
} as const;
export type RegisterUserRequestRoleEnum =
  (typeof RegisterUserRequestRoleEnum)[keyof typeof RegisterUserRequestRoleEnum];

/**
 * @export
 */
export const RegisterUserRequestRolesEnum = {
  Owner: "owner",
  Administrator: "administrator",
  Prescriber: "prescriber",
  ClinicalStaff: "clinical_staff",
  Billing: "billing",
  Developer: "developer",
} as const;
export type RegisterUserRequestRolesEnum =
  (typeof RegisterUserRequestRolesEnum)[keyof typeof RegisterUserRequestRolesEnum];

/**
 * Check if a given object implements the RegisterUserRequest interface.
 */
export function instanceOfRegisterUserRequest(value: object): value is RegisterUserRequest {
  if (!("externalId" in value) || value["externalId"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("role" in value) || value["role"] === undefined) return false;
  if (!("identityAttestation" in value) || value["identityAttestation"] === undefined) return false;
  return true;
}

export function RegisterUserRequestFromJSON(json: any): RegisterUserRequest {
  return RegisterUserRequestFromJSONTyped(json, false);
}

export function RegisterUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterUserRequest {
  if (json == null) {
    return json;
  }
  return {
    externalId: json["externalId"],
    email: json["email"],
    name: json["name"],
    role: json["role"],
    roles: json["roles"] == null ? undefined : json["roles"],
    profileDetails:
      json["profileDetails"] == null
        ? undefined
        : RegisterUserRequestProfileDetailsFromJSON(json["profileDetails"]),
    npi: json["npi"] == null ? undefined : json["npi"],
    licenses:
      json["licenses"] == null
        ? undefined
        : (json["licenses"] as Array<any>).map(RegisterUserRequestLicensesInnerFromJSON),
    legalName: json["legalName"] == null ? undefined : json["legalName"],
    displayName: json["displayName"] == null ? undefined : json["displayName"],
    credentials: json["credentials"] == null ? undefined : json["credentials"],
    address:
      json["address"] == null ? undefined : RegisterUserRequestAddressFromJSON(json["address"]),
    phone: json["phone"] == null ? undefined : json["phone"],
    locationIds: json["locationIds"] == null ? undefined : json["locationIds"],
    identityAttestation: json["identityAttestation"],
  };
}

export function RegisterUserRequestToJSON(json: any): RegisterUserRequest {
  return RegisterUserRequestToJSONTyped(json, false);
}

export function RegisterUserRequestToJSONTyped(
  value?: RegisterUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    externalId: value["externalId"],
    email: value["email"],
    name: value["name"],
    role: value["role"],
    roles: value["roles"],
    profileDetails: RegisterUserRequestProfileDetailsToJSON(value["profileDetails"]),
    npi: value["npi"],
    licenses:
      value["licenses"] == null
        ? undefined
        : (value["licenses"] as Array<any>).map(RegisterUserRequestLicensesInnerToJSON),
    legalName: value["legalName"],
    displayName: value["displayName"],
    credentials: value["credentials"],
    address: RegisterUserRequestAddressToJSON(value["address"]),
    phone: value["phone"],
    locationIds: value["locationIds"],
    identityAttestation: value["identityAttestation"],
  };
}
