/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegisterUserRequestProfileDetailsOtherNamesInner
 */
export interface RegisterUserRequestProfileDetailsOtherNamesInner {
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequestProfileDetailsOtherNamesInner
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequestProfileDetailsOtherNamesInner
   */
  credentials: string;
  /**
   *
   * @type {string}
   * @memberof RegisterUserRequestProfileDetailsOtherNamesInner
   */
  type: string;
}

/**
 * Check if a given object implements the RegisterUserRequestProfileDetailsOtherNamesInner interface.
 */
export function instanceOfRegisterUserRequestProfileDetailsOtherNamesInner(
  value: object,
): value is RegisterUserRequestProfileDetailsOtherNamesInner {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("credentials" in value) || value["credentials"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function RegisterUserRequestProfileDetailsOtherNamesInnerFromJSON(
  json: any,
): RegisterUserRequestProfileDetailsOtherNamesInner {
  return RegisterUserRequestProfileDetailsOtherNamesInnerFromJSONTyped(json, false);
}

export function RegisterUserRequestProfileDetailsOtherNamesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterUserRequestProfileDetailsOtherNamesInner {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    credentials: json["credentials"],
    type: json["type"],
  };
}

export function RegisterUserRequestProfileDetailsOtherNamesInnerToJSON(
  json: any,
): RegisterUserRequestProfileDetailsOtherNamesInner {
  return RegisterUserRequestProfileDetailsOtherNamesInnerToJSONTyped(json, false);
}

export function RegisterUserRequestProfileDetailsOtherNamesInnerToJSONTyped(
  value?: RegisterUserRequestProfileDetailsOtherNamesInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    credentials: value["credentials"],
    type: value["type"],
  };
}
