/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RetrievePrescribingOptionsResponseOptionsDoseUnitsInner } from "./RetrievePrescribingOptionsResponseOptionsDoseUnitsInner";
import {
  RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerFromJSON,
  RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerFromJSONTyped,
  RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerToJSON,
  RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerToJSONTyped,
} from "./RetrievePrescribingOptionsResponseOptionsDoseUnitsInner";

/**
 *
 * @export
 * @interface RetrievePrescribingOptionsResponseOptions
 */
export interface RetrievePrescribingOptionsResponseOptions {
  /**
   *
   * @type {Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>}
   * @memberof RetrievePrescribingOptionsResponseOptions
   */
  doseUnits: Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>;
  /**
   *
   * @type {Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>}
   * @memberof RetrievePrescribingOptionsResponseOptions
   */
  doses: Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>;
  /**
   *
   * @type {Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>}
   * @memberof RetrievePrescribingOptionsResponseOptions
   */
  frequencies: Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>;
  /**
   *
   * @type {Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>}
   * @memberof RetrievePrescribingOptionsResponseOptions
   */
  routes: Array<RetrievePrescribingOptionsResponseOptionsDoseUnitsInner>;
}

/**
 * Check if a given object implements the RetrievePrescribingOptionsResponseOptions interface.
 */
export function instanceOfRetrievePrescribingOptionsResponseOptions(
  value: object,
): value is RetrievePrescribingOptionsResponseOptions {
  if (!("doseUnits" in value) || value["doseUnits"] === undefined) return false;
  if (!("doses" in value) || value["doses"] === undefined) return false;
  if (!("frequencies" in value) || value["frequencies"] === undefined) return false;
  if (!("routes" in value) || value["routes"] === undefined) return false;
  return true;
}

export function RetrievePrescribingOptionsResponseOptionsFromJSON(
  json: any,
): RetrievePrescribingOptionsResponseOptions {
  return RetrievePrescribingOptionsResponseOptionsFromJSONTyped(json, false);
}

export function RetrievePrescribingOptionsResponseOptionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RetrievePrescribingOptionsResponseOptions {
  if (json == null) {
    return json;
  }
  return {
    doseUnits: (json["doseUnits"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerFromJSON,
    ),
    doses: (json["doses"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerFromJSON,
    ),
    frequencies: (json["frequencies"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerFromJSON,
    ),
    routes: (json["routes"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerFromJSON,
    ),
  };
}

export function RetrievePrescribingOptionsResponseOptionsToJSON(
  json: any,
): RetrievePrescribingOptionsResponseOptions {
  return RetrievePrescribingOptionsResponseOptionsToJSONTyped(json, false);
}

export function RetrievePrescribingOptionsResponseOptionsToJSONTyped(
  value?: RetrievePrescribingOptionsResponseOptions | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    doseUnits: (value["doseUnits"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerToJSON,
    ),
    doses: (value["doses"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerToJSON,
    ),
    frequencies: (value["frequencies"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerToJSON,
    ),
    routes: (value["routes"] as Array<any>).map(
      RetrievePrescribingOptionsResponseOptionsDoseUnitsInnerToJSON,
    ),
  };
}
