/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SignOrderResponse
 */
export interface SignOrderResponse {
  /**
   *
   * @type {string}
   * @memberof SignOrderResponse
   */
  orderId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof SignOrderResponse
   */
  prescriptions: Array<string>;
  /**
   *
   * @type {string}
   * @memberof SignOrderResponse
   */
  signedAt: string;
  /**
   *
   * @type {SignOrderResponseStatusEnum}
   * @memberof SignOrderResponse
   */
  status: SignOrderResponseStatusEnum;
}

/**
 * @export
 */
export const SignOrderResponseStatusEnum = {
  Signed: "signed",
} as const;
export type SignOrderResponseStatusEnum =
  (typeof SignOrderResponseStatusEnum)[keyof typeof SignOrderResponseStatusEnum];

/**
 * Check if a given object implements the SignOrderResponse interface.
 */
export function instanceOfSignOrderResponse(value: object): value is SignOrderResponse {
  if (!("orderId" in value) || value["orderId"] === undefined) return false;
  if (!("prescriptions" in value) || value["prescriptions"] === undefined) return false;
  if (!("signedAt" in value) || value["signedAt"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function SignOrderResponseFromJSON(json: any): SignOrderResponse {
  return SignOrderResponseFromJSONTyped(json, false);
}

export function SignOrderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignOrderResponse {
  if (json == null) {
    return json;
  }
  return {
    orderId: json["orderId"],
    prescriptions: json["prescriptions"],
    signedAt: json["signedAt"],
    status: json["status"],
  };
}

export function SignOrderResponseToJSON(json: any): SignOrderResponse {
  return SignOrderResponseToJSONTyped(json, false);
}

export function SignOrderResponseToJSONTyped(
  value?: SignOrderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    orderId: value["orderId"],
    prescriptions: value["prescriptions"],
    signedAt: value["signedAt"],
    status: value["status"],
  };
}
