/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SignOrderRequestExpectedVersionsInner } from "./SignOrderRequestExpectedVersionsInner";
import {
  SignOrderRequestExpectedVersionsInnerFromJSON,
  SignOrderRequestExpectedVersionsInnerFromJSONTyped,
  SignOrderRequestExpectedVersionsInnerToJSON,
  SignOrderRequestExpectedVersionsInnerToJSONTyped,
} from "./SignOrderRequestExpectedVersionsInner";

/**
 *
 * @export
 * @interface SignOrderRequest
 */
export interface SignOrderRequest {
  /**
   *
   * @type {string}
   * @memberof SignOrderRequest
   */
  practiceId: string | null;
  /**
   *
   * @type {string}
   * @memberof SignOrderRequest
   */
  userId: string;
  /**
   *
   * @type {SignOrderRequestSignatureAttestationEnum}
   * @memberof SignOrderRequest
   */
  signatureAttestation: SignOrderRequestSignatureAttestationEnum;
  /**
   *
   * @type {Array<SignOrderRequestExpectedVersionsInner>}
   * @memberof SignOrderRequest
   */
  expectedVersions: Array<SignOrderRequestExpectedVersionsInner>;
}

/**
 * @export
 */
export const SignOrderRequestSignatureAttestationEnum = {
  True: true,
} as const;
export type SignOrderRequestSignatureAttestationEnum =
  (typeof SignOrderRequestSignatureAttestationEnum)[keyof typeof SignOrderRequestSignatureAttestationEnum];

/**
 * Check if a given object implements the SignOrderRequest interface.
 */
export function instanceOfSignOrderRequest(value: object): value is SignOrderRequest {
  if (!("practiceId" in value) || value["practiceId"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("signatureAttestation" in value) || value["signatureAttestation"] === undefined)
    return false;
  if (!("expectedVersions" in value) || value["expectedVersions"] === undefined) return false;
  return true;
}

export function SignOrderRequestFromJSON(json: any): SignOrderRequest {
  return SignOrderRequestFromJSONTyped(json, false);
}

export function SignOrderRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignOrderRequest {
  if (json == null) {
    return json;
  }
  return {
    practiceId: json["practiceId"],
    userId: json["userId"],
    signatureAttestation: json["signatureAttestation"],
    expectedVersions: (json["expectedVersions"] as Array<any>).map(
      SignOrderRequestExpectedVersionsInnerFromJSON,
    ),
  };
}

export function SignOrderRequestToJSON(json: any): SignOrderRequest {
  return SignOrderRequestToJSONTyped(json, false);
}

export function SignOrderRequestToJSONTyped(
  value?: SignOrderRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    practiceId: value["practiceId"],
    userId: value["userId"],
    signatureAttestation: value["signatureAttestation"],
    expectedVersions: (value["expectedVersions"] as Array<any>).map(
      SignOrderRequestExpectedVersionsInnerToJSON,
    ),
  };
}
