/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network. A practice is the customer organization, a provider is an individual clinician or prescriber, and a location is a physical practice site. The API covers practice management, catalog discovery, prescription-order submission, fulfillment tracking, and webhooks.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateProviderMappingResponse
 */
export interface UpdateProviderMappingResponse {
  /**
   *
   * @type {Date}
   * @memberof UpdateProviderMappingResponse
   */
  createdAt: Date;
  /**
   * Your platform's stable identifier for this provider.
   * @type {string}
   * @memberof UpdateProviderMappingResponse
   */
  externalId: string;
  /**
   * The Affinity provider mapping ID. Store this pmap_ value and send it as providerMappingId when you create component or hosted sessions.
   * @type {string}
   * @memberof UpdateProviderMappingResponse
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof UpdateProviderMappingResponse
   */
  livemode: boolean;
  /**
   * The provider's 10-digit individual NPI.
   * @type {string}
   * @memberof UpdateProviderMappingResponse
   */
  npi: string;
  /**
   *
   * @type {UpdateProviderMappingResponseObjectEnum}
   * @memberof UpdateProviderMappingResponse
   */
  object: UpdateProviderMappingResponseObjectEnum;
  /**
   * The Affinity practice where this provider is authorized to act.
   * @type {string}
   * @memberof UpdateProviderMappingResponse
   */
  practiceId: string;
  /**
   * The mapping's verification state. Prescribing sessions require verified status.
   * @type {UpdateProviderMappingResponseStatusEnum}
   * @memberof UpdateProviderMappingResponse
   */
  status: UpdateProviderMappingResponseStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof UpdateProviderMappingResponse
   */
  updatedAt: Date;
  /**
   * The Affinity user record for the person your platform authenticated.
   * @type {string}
   * @memberof UpdateProviderMappingResponse
   */
  userId: string;
  /**
   * When Affinity verified this mapping, or null until verification is complete.
   * @type {Date}
   * @memberof UpdateProviderMappingResponse
   */
  verifiedAt: Date | null;
}

/**
 * @export
 */
export const UpdateProviderMappingResponseObjectEnum = {
  ProviderMapping: "provider_mapping",
} as const;
export type UpdateProviderMappingResponseObjectEnum =
  (typeof UpdateProviderMappingResponseObjectEnum)[keyof typeof UpdateProviderMappingResponseObjectEnum];

/**
 * @export
 */
export const UpdateProviderMappingResponseStatusEnum = {
  Pending: "pending",
  Verified: "verified",
  Revoked: "revoked",
} as const;
export type UpdateProviderMappingResponseStatusEnum =
  (typeof UpdateProviderMappingResponseStatusEnum)[keyof typeof UpdateProviderMappingResponseStatusEnum];

/**
 * Check if a given object implements the UpdateProviderMappingResponse interface.
 */
export function instanceOfUpdateProviderMappingResponse(
  value: object,
): value is UpdateProviderMappingResponse {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("externalId" in value) || value["externalId"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("livemode" in value) || value["livemode"] === undefined) return false;
  if (!("npi" in value) || value["npi"] === undefined) return false;
  if (!("object" in value) || value["object"] === undefined) return false;
  if (!("practiceId" in value) || value["practiceId"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("verifiedAt" in value) || value["verifiedAt"] === undefined) return false;
  return true;
}

export function UpdateProviderMappingResponseFromJSON(json: any): UpdateProviderMappingResponse {
  return UpdateProviderMappingResponseFromJSONTyped(json, false);
}

export function UpdateProviderMappingResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateProviderMappingResponse {
  if (json == null) {
    return json;
  }
  return {
    createdAt: new Date(json["createdAt"]),
    externalId: json["externalId"],
    id: json["id"],
    livemode: json["livemode"],
    npi: json["npi"],
    object: json["object"],
    practiceId: json["practiceId"],
    status: json["status"],
    updatedAt: new Date(json["updatedAt"]),
    userId: json["userId"],
    verifiedAt: json["verifiedAt"] == null ? null : new Date(json["verifiedAt"]),
  };
}

export function UpdateProviderMappingResponseToJSON(json: any): UpdateProviderMappingResponse {
  return UpdateProviderMappingResponseToJSONTyped(json, false);
}

export function UpdateProviderMappingResponseToJSONTyped(
  value?: UpdateProviderMappingResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    createdAt: value["createdAt"].toISOString(),
    externalId: value["externalId"],
    id: value["id"],
    livemode: value["livemode"],
    npi: value["npi"],
    object: value["object"],
    practiceId: value["practiceId"],
    status: value["status"],
    updatedAt: value["updatedAt"].toISOString(),
    userId: value["userId"],
    verifiedAt:
      value["verifiedAt"] == null ? value["verifiedAt"] : value["verifiedAt"].toISOString(),
  };
}
