/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for software platforms connecting practices to the compounder network.
 *
 * The version of the OpenAPI document: 2026-07-29
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreatePracticeRequestPrescribersInner } from "./CreatePracticeRequestPrescribersInner";
import {
  CreatePracticeRequestPrescribersInnerFromJSON,
  CreatePracticeRequestPrescribersInnerFromJSONTyped,
  CreatePracticeRequestPrescribersInnerToJSON,
  CreatePracticeRequestPrescribersInnerToJSONTyped,
} from "./CreatePracticeRequestPrescribersInner";
import type { UpdatePracticeRequestAttestations } from "./UpdatePracticeRequestAttestations";
import {
  UpdatePracticeRequestAttestationsFromJSON,
  UpdatePracticeRequestAttestationsFromJSONTyped,
  UpdatePracticeRequestAttestationsToJSON,
  UpdatePracticeRequestAttestationsToJSONTyped,
} from "./UpdatePracticeRequestAttestations";
import type { CreatePracticeRequestAddress } from "./CreatePracticeRequestAddress";
import {
  CreatePracticeRequestAddressFromJSON,
  CreatePracticeRequestAddressFromJSONTyped,
  CreatePracticeRequestAddressToJSON,
  CreatePracticeRequestAddressToJSONTyped,
} from "./CreatePracticeRequestAddress";
import type { ListPracticesResponseDataInnerContactsPrimary } from "./ListPracticesResponseDataInnerContactsPrimary";
import {
  ListPracticesResponseDataInnerContactsPrimaryFromJSON,
  ListPracticesResponseDataInnerContactsPrimaryFromJSONTyped,
  ListPracticesResponseDataInnerContactsPrimaryToJSON,
  ListPracticesResponseDataInnerContactsPrimaryToJSONTyped,
} from "./ListPracticesResponseDataInnerContactsPrimary";

/**
 *
 * @export
 * @interface UpdatePracticeRequest
 */
export interface UpdatePracticeRequest {
  /**
   *
   * @type {CreatePracticeRequestAddress}
   * @memberof UpdatePracticeRequest
   */
  address?: CreatePracticeRequestAddress;
  /**
   *
   * @type {UpdatePracticeRequestAttestations}
   * @memberof UpdatePracticeRequest
   */
  attestations?: UpdatePracticeRequestAttestations;
  /**
   *
   * @type {ListPracticesResponseDataInnerContactsPrimary}
   * @memberof UpdatePracticeRequest
   */
  complianceContact?: ListPracticesResponseDataInnerContactsPrimary | null;
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof UpdatePracticeRequest
   */
  externalId?: string | null;
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof UpdatePracticeRequest
   */
  legalName?: string | null;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof UpdatePracticeRequest
   */
  metadata?: { [key: string]: any };
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof UpdatePracticeRequest
   */
  name?: string | null;
  /**
   *
   * @type {Array<CreatePracticeRequestPrescribersInner>}
   * @memberof UpdatePracticeRequest
   */
  prescribers?: Array<CreatePracticeRequestPrescribersInner>;
  /**
   *
   * @type {ListPracticesResponseDataInnerContactsPrimary}
   * @memberof UpdatePracticeRequest
   */
  primaryContact?: ListPracticesResponseDataInnerContactsPrimary | null;
  /**
   *
   * @type {string}
   * @memberof UpdatePracticeRequest
   */
  supportEmail?: string | null;
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof UpdatePracticeRequest
   */
  supportPhone?: string | null;
  /**
   * a string that will be trimmed
   * @type {string}
   * @memberof UpdatePracticeRequest
   */
  timezone?: string | null;
}

/**
 * Check if a given object implements the UpdatePracticeRequest interface.
 */
export function instanceOfUpdatePracticeRequest(value: object): value is UpdatePracticeRequest {
  return true;
}

export function UpdatePracticeRequestFromJSON(json: any): UpdatePracticeRequest {
  return UpdatePracticeRequestFromJSONTyped(json, false);
}

export function UpdatePracticeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePracticeRequest {
  if (json == null) {
    return json;
  }
  return {
    address:
      json["address"] == null ? undefined : CreatePracticeRequestAddressFromJSON(json["address"]),
    attestations:
      json["attestations"] == null
        ? undefined
        : UpdatePracticeRequestAttestationsFromJSON(json["attestations"]),
    complianceContact:
      json["complianceContact"] == null
        ? undefined
        : ListPracticesResponseDataInnerContactsPrimaryFromJSON(json["complianceContact"]),
    externalId: json["externalId"] == null ? undefined : json["externalId"],
    legalName: json["legalName"] == null ? undefined : json["legalName"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
    name: json["name"] == null ? undefined : json["name"],
    prescribers:
      json["prescribers"] == null
        ? undefined
        : (json["prescribers"] as Array<any>).map(CreatePracticeRequestPrescribersInnerFromJSON),
    primaryContact:
      json["primaryContact"] == null
        ? undefined
        : ListPracticesResponseDataInnerContactsPrimaryFromJSON(json["primaryContact"]),
    supportEmail: json["supportEmail"] == null ? undefined : json["supportEmail"],
    supportPhone: json["supportPhone"] == null ? undefined : json["supportPhone"],
    timezone: json["timezone"] == null ? undefined : json["timezone"],
  };
}

export function UpdatePracticeRequestToJSON(json: any): UpdatePracticeRequest {
  return UpdatePracticeRequestToJSONTyped(json, false);
}

export function UpdatePracticeRequestToJSONTyped(
  value?: UpdatePracticeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: CreatePracticeRequestAddressToJSON(value["address"]),
    attestations: UpdatePracticeRequestAttestationsToJSON(value["attestations"]),
    complianceContact: ListPracticesResponseDataInnerContactsPrimaryToJSON(
      value["complianceContact"],
    ),
    externalId: value["externalId"],
    legalName: value["legalName"],
    metadata: value["metadata"],
    name: value["name"],
    prescribers:
      value["prescribers"] == null
        ? undefined
        : (value["prescribers"] as Array<any>).map(CreatePracticeRequestPrescribersInnerToJSON),
    primaryContact: ListPracticesResponseDataInnerContactsPrimaryToJSON(value["primaryContact"]),
    supportEmail: value["supportEmail"],
    supportPhone: value["supportPhone"],
    timezone: value["timezone"],
  };
}
