/* tslint:disable */
/* eslint-disable */
/**
 * Affinity API
 * Affinity API for practices and software platforms connecting to the pharmacy network.
 *
 * The version of the OpenAPI document: 2026-08-11
 * Contact: support@joinaffinityai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RegisterUserRequestAddress } from "./RegisterUserRequestAddress";
import {
  RegisterUserRequestAddressFromJSON,
  RegisterUserRequestAddressFromJSONTyped,
  RegisterUserRequestAddressToJSON,
  RegisterUserRequestAddressToJSONTyped,
} from "./RegisterUserRequestAddress";

/**
 *
 * @export
 * @interface UpdatePracticeTeamPrescriberRequest
 */
export interface UpdatePracticeTeamPrescriberRequest {
  /**
   *
   * @type {string}
   * @memberof UpdatePracticeTeamPrescriberRequest
   */
  displayName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdatePracticeTeamPrescriberRequest
   */
  legalName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdatePracticeTeamPrescriberRequest
   */
  credentials?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdatePracticeTeamPrescriberRequest
   */
  phone?: string | null;
  /**
   *
   * @type {RegisterUserRequestAddress}
   * @memberof UpdatePracticeTeamPrescriberRequest
   */
  address?: RegisterUserRequestAddress | null;
}

/**
 * Check if a given object implements the UpdatePracticeTeamPrescriberRequest interface.
 */
export function instanceOfUpdatePracticeTeamPrescriberRequest(
  value: object,
): value is UpdatePracticeTeamPrescriberRequest {
  return true;
}

export function UpdatePracticeTeamPrescriberRequestFromJSON(
  json: any,
): UpdatePracticeTeamPrescriberRequest {
  return UpdatePracticeTeamPrescriberRequestFromJSONTyped(json, false);
}

export function UpdatePracticeTeamPrescriberRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatePracticeTeamPrescriberRequest {
  if (json == null) {
    return json;
  }
  return {
    displayName: json["displayName"] == null ? undefined : json["displayName"],
    legalName: json["legalName"] == null ? undefined : json["legalName"],
    credentials: json["credentials"] == null ? undefined : json["credentials"],
    phone: json["phone"] == null ? undefined : json["phone"],
    address:
      json["address"] == null ? undefined : RegisterUserRequestAddressFromJSON(json["address"]),
  };
}

export function UpdatePracticeTeamPrescriberRequestToJSON(
  json: any,
): UpdatePracticeTeamPrescriberRequest {
  return UpdatePracticeTeamPrescriberRequestToJSONTyped(json, false);
}

export function UpdatePracticeTeamPrescriberRequestToJSONTyped(
  value?: UpdatePracticeTeamPrescriberRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    displayName: value["displayName"],
    legalName: value["legalName"],
    credentials: value["credentials"],
    phone: value["phone"],
    address: RegisterUserRequestAddressToJSON(value["address"]),
  };
}
