// This file was auto-generated by Fern from our API Definition.

export type ListItemsRequestRoutes =
  | ("injectable" | "nasal" | "oral" | "sublingual" | "topical" | "unknown")
  | ("injectable" | "nasal" | "oral" | "sublingual" | "topical" | "unknown")[];
