// This file was auto-generated by Fern from our API Definition.

export const ListItemsRequestView = {
  Offers: "offers",
  Medications: "medications",
} as const;
export type ListItemsRequestView = (typeof ListItemsRequestView)[keyof typeof ListItemsRequestView];
