// This file was auto-generated by Fern from our API Definition.

import type * as AffinityApi from "../../../../index.js";

/**
 * @example
 *     {
 *         catalogItemId: "cat_01j2y8m6jcc9tt24af5pw9x1bc",
 *         destinationState: "destinationState"
 *     }
 */
export interface ListShippingOptionsRequest {
  catalogItemId: string;
  destinationState: string;
  destinationType?: AffinityApi.ListShippingOptionsRequestDestinationType | null;
}
